// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: gnef/proto/embdding.proto
// Protobuf C++ Version: 5.29.5

#ifndef gnef_2fproto_2fembdding_2eproto_2epb_2eh
#define gnef_2fproto_2fembdding_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029005
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_gnef_2fproto_2fembdding_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_gnef_2fproto_2fembdding_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_gnef_2fproto_2fembdding_2eproto;
namespace kumo {
namespace nlp {
class EmbeddingRequest;
struct EmbeddingRequestDefaultTypeInternal;
extern EmbeddingRequestDefaultTypeInternal _EmbeddingRequest_default_instance_;
class EmbeddingResponse;
struct EmbeddingResponseDefaultTypeInternal;
extern EmbeddingResponseDefaultTypeInternal _EmbeddingResponse_default_instance_;
class EmbeddingSetting;
struct EmbeddingSettingDefaultTypeInternal;
extern EmbeddingSettingDefaultTypeInternal _EmbeddingSetting_default_instance_;
}  // namespace nlp
}  // namespace kumo
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace kumo {
namespace nlp {

// ===================================================================


// -------------------------------------------------------------------

class EmbeddingSetting final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:kumo.nlp.EmbeddingSetting) */ {
 public:
  inline EmbeddingSetting() : EmbeddingSetting(nullptr) {}
  ~EmbeddingSetting() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(EmbeddingSetting* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(EmbeddingSetting));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR EmbeddingSetting(
      ::google::protobuf::internal::ConstantInitialized);

  inline EmbeddingSetting(const EmbeddingSetting& from) : EmbeddingSetting(nullptr, from) {}
  inline EmbeddingSetting(EmbeddingSetting&& from) noexcept
      : EmbeddingSetting(nullptr, std::move(from)) {}
  inline EmbeddingSetting& operator=(const EmbeddingSetting& from) {
    CopyFrom(from);
    return *this;
  }
  inline EmbeddingSetting& operator=(EmbeddingSetting&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const EmbeddingSetting& default_instance() {
    return *internal_default_instance();
  }
  static inline const EmbeddingSetting* internal_default_instance() {
    return reinterpret_cast<const EmbeddingSetting*>(
        &_EmbeddingSetting_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(EmbeddingSetting& a, EmbeddingSetting& b) { a.Swap(&b); }
  inline void Swap(EmbeddingSetting* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(EmbeddingSetting* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  EmbeddingSetting* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<EmbeddingSetting>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const EmbeddingSetting& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const EmbeddingSetting& from) { EmbeddingSetting::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(EmbeddingSetting* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "kumo.nlp.EmbeddingSetting"; }

 protected:
  explicit EmbeddingSetting(::google::protobuf::Arena* arena);
  EmbeddingSetting(::google::protobuf::Arena* arena, const EmbeddingSetting& from);
  EmbeddingSetting(::google::protobuf::Arena* arena, EmbeddingSetting&& from) noexcept
      : EmbeddingSetting(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kModelFieldNumber = 1,
  };
  // string model = 1;
  void clear_model() ;
  const std::string& model() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_model(Arg_&& arg, Args_... args);
  std::string* mutable_model();
  PROTOBUF_NODISCARD std::string* release_model();
  void set_allocated_model(std::string* value);

  private:
  const std::string& _internal_model() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_model(
      const std::string& value);
  std::string* _internal_mutable_model();

  public:
  // @@protoc_insertion_point(class_scope:kumo.nlp.EmbeddingSetting)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      39, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const EmbeddingSetting& from_msg);
    ::google::protobuf::internal::ArenaStringPtr model_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_gnef_2fproto_2fembdding_2eproto;
};
// -------------------------------------------------------------------

class EmbeddingResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:kumo.nlp.EmbeddingResponse) */ {
 public:
  inline EmbeddingResponse() : EmbeddingResponse(nullptr) {}
  ~EmbeddingResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(EmbeddingResponse* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(EmbeddingResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR EmbeddingResponse(
      ::google::protobuf::internal::ConstantInitialized);

  inline EmbeddingResponse(const EmbeddingResponse& from) : EmbeddingResponse(nullptr, from) {}
  inline EmbeddingResponse(EmbeddingResponse&& from) noexcept
      : EmbeddingResponse(nullptr, std::move(from)) {}
  inline EmbeddingResponse& operator=(const EmbeddingResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline EmbeddingResponse& operator=(EmbeddingResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const EmbeddingResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const EmbeddingResponse* internal_default_instance() {
    return reinterpret_cast<const EmbeddingResponse*>(
        &_EmbeddingResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(EmbeddingResponse& a, EmbeddingResponse& b) { a.Swap(&b); }
  inline void Swap(EmbeddingResponse* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(EmbeddingResponse* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  EmbeddingResponse* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<EmbeddingResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const EmbeddingResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const EmbeddingResponse& from) { EmbeddingResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(EmbeddingResponse* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "kumo.nlp.EmbeddingResponse"; }

 protected:
  explicit EmbeddingResponse(::google::protobuf::Arena* arena);
  EmbeddingResponse(::google::protobuf::Arena* arena, const EmbeddingResponse& from);
  EmbeddingResponse(::google::protobuf::Arena* arena, EmbeddingResponse&& from) noexcept
      : EmbeddingResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kFeatureFieldNumber = 1,
  };
  // repeated float feature = 1;
  int feature_size() const;
  private:
  int _internal_feature_size() const;

  public:
  void clear_feature() ;
  float feature(int index) const;
  void set_feature(int index, float value);
  void add_feature(float value);
  const ::google::protobuf::RepeatedField<float>& feature() const;
  ::google::protobuf::RepeatedField<float>* mutable_feature();

  private:
  const ::google::protobuf::RepeatedField<float>& _internal_feature() const;
  ::google::protobuf::RepeatedField<float>* _internal_mutable_feature();

  public:
  // @@protoc_insertion_point(class_scope:kumo.nlp.EmbeddingResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const EmbeddingResponse& from_msg);
    ::google::protobuf::RepeatedField<float> feature_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_gnef_2fproto_2fembdding_2eproto;
};
// -------------------------------------------------------------------

class EmbeddingRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:kumo.nlp.EmbeddingRequest) */ {
 public:
  inline EmbeddingRequest() : EmbeddingRequest(nullptr) {}
  ~EmbeddingRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(EmbeddingRequest* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(EmbeddingRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR EmbeddingRequest(
      ::google::protobuf::internal::ConstantInitialized);

  inline EmbeddingRequest(const EmbeddingRequest& from) : EmbeddingRequest(nullptr, from) {}
  inline EmbeddingRequest(EmbeddingRequest&& from) noexcept
      : EmbeddingRequest(nullptr, std::move(from)) {}
  inline EmbeddingRequest& operator=(const EmbeddingRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline EmbeddingRequest& operator=(EmbeddingRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const EmbeddingRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const EmbeddingRequest* internal_default_instance() {
    return reinterpret_cast<const EmbeddingRequest*>(
        &_EmbeddingRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(EmbeddingRequest& a, EmbeddingRequest& b) { a.Swap(&b); }
  inline void Swap(EmbeddingRequest* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(EmbeddingRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  EmbeddingRequest* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<EmbeddingRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const EmbeddingRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const EmbeddingRequest& from) { EmbeddingRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(EmbeddingRequest* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "kumo.nlp.EmbeddingRequest"; }

 protected:
  explicit EmbeddingRequest(::google::protobuf::Arena* arena);
  EmbeddingRequest(::google::protobuf::Arena* arena, const EmbeddingRequest& from);
  EmbeddingRequest(::google::protobuf::Arena* arena, EmbeddingRequest&& from) noexcept
      : EmbeddingRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kQueryFieldNumber = 1,
    kSettingFieldNumber = 2,
  };
  // string query = 1;
  void clear_query() ;
  const std::string& query() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_query(Arg_&& arg, Args_... args);
  std::string* mutable_query();
  PROTOBUF_NODISCARD std::string* release_query();
  void set_allocated_query(std::string* value);

  private:
  const std::string& _internal_query() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_query(
      const std::string& value);
  std::string* _internal_mutable_query();

  public:
  // .kumo.nlp.EmbeddingSetting setting = 2;
  bool has_setting() const;
  void clear_setting() ;
  const ::kumo::nlp::EmbeddingSetting& setting() const;
  PROTOBUF_NODISCARD ::kumo::nlp::EmbeddingSetting* release_setting();
  ::kumo::nlp::EmbeddingSetting* mutable_setting();
  void set_allocated_setting(::kumo::nlp::EmbeddingSetting* value);
  void unsafe_arena_set_allocated_setting(::kumo::nlp::EmbeddingSetting* value);
  ::kumo::nlp::EmbeddingSetting* unsafe_arena_release_setting();

  private:
  const ::kumo::nlp::EmbeddingSetting& _internal_setting() const;
  ::kumo::nlp::EmbeddingSetting* _internal_mutable_setting();

  public:
  // @@protoc_insertion_point(class_scope:kumo.nlp.EmbeddingRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 1,
      39, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const EmbeddingRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr query_;
    ::kumo::nlp::EmbeddingSetting* setting_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_gnef_2fproto_2fembdding_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// EmbeddingSetting

// string model = 1;
inline void EmbeddingSetting::clear_model() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.model_.ClearToEmpty();
}
inline const std::string& EmbeddingSetting::model() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:kumo.nlp.EmbeddingSetting.model)
  return _internal_model();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void EmbeddingSetting::set_model(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.model_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:kumo.nlp.EmbeddingSetting.model)
}
inline std::string* EmbeddingSetting::mutable_model() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_model();
  // @@protoc_insertion_point(field_mutable:kumo.nlp.EmbeddingSetting.model)
  return _s;
}
inline const std::string& EmbeddingSetting::_internal_model() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.model_.Get();
}
inline void EmbeddingSetting::_internal_set_model(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.model_.Set(value, GetArena());
}
inline std::string* EmbeddingSetting::_internal_mutable_model() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.model_.Mutable( GetArena());
}
inline std::string* EmbeddingSetting::release_model() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:kumo.nlp.EmbeddingSetting.model)
  return _impl_.model_.Release();
}
inline void EmbeddingSetting::set_allocated_model(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.model_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.model_.IsDefault()) {
    _impl_.model_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:kumo.nlp.EmbeddingSetting.model)
}

// -------------------------------------------------------------------

// EmbeddingRequest

// string query = 1;
inline void EmbeddingRequest::clear_query() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.query_.ClearToEmpty();
}
inline const std::string& EmbeddingRequest::query() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:kumo.nlp.EmbeddingRequest.query)
  return _internal_query();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void EmbeddingRequest::set_query(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.query_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:kumo.nlp.EmbeddingRequest.query)
}
inline std::string* EmbeddingRequest::mutable_query() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_query();
  // @@protoc_insertion_point(field_mutable:kumo.nlp.EmbeddingRequest.query)
  return _s;
}
inline const std::string& EmbeddingRequest::_internal_query() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.query_.Get();
}
inline void EmbeddingRequest::_internal_set_query(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.query_.Set(value, GetArena());
}
inline std::string* EmbeddingRequest::_internal_mutable_query() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.query_.Mutable( GetArena());
}
inline std::string* EmbeddingRequest::release_query() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:kumo.nlp.EmbeddingRequest.query)
  return _impl_.query_.Release();
}
inline void EmbeddingRequest::set_allocated_query(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.query_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.query_.IsDefault()) {
    _impl_.query_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:kumo.nlp.EmbeddingRequest.query)
}

// .kumo.nlp.EmbeddingSetting setting = 2;
inline bool EmbeddingRequest::has_setting() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.setting_ != nullptr);
  return value;
}
inline void EmbeddingRequest::clear_setting() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.setting_ != nullptr) _impl_.setting_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::kumo::nlp::EmbeddingSetting& EmbeddingRequest::_internal_setting() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::kumo::nlp::EmbeddingSetting* p = _impl_.setting_;
  return p != nullptr ? *p : reinterpret_cast<const ::kumo::nlp::EmbeddingSetting&>(::kumo::nlp::_EmbeddingSetting_default_instance_);
}
inline const ::kumo::nlp::EmbeddingSetting& EmbeddingRequest::setting() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:kumo.nlp.EmbeddingRequest.setting)
  return _internal_setting();
}
inline void EmbeddingRequest::unsafe_arena_set_allocated_setting(::kumo::nlp::EmbeddingSetting* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.setting_);
  }
  _impl_.setting_ = reinterpret_cast<::kumo::nlp::EmbeddingSetting*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:kumo.nlp.EmbeddingRequest.setting)
}
inline ::kumo::nlp::EmbeddingSetting* EmbeddingRequest::release_setting() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::kumo::nlp::EmbeddingSetting* released = _impl_.setting_;
  _impl_.setting_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::kumo::nlp::EmbeddingSetting* EmbeddingRequest::unsafe_arena_release_setting() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:kumo.nlp.EmbeddingRequest.setting)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::kumo::nlp::EmbeddingSetting* temp = _impl_.setting_;
  _impl_.setting_ = nullptr;
  return temp;
}
inline ::kumo::nlp::EmbeddingSetting* EmbeddingRequest::_internal_mutable_setting() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.setting_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::kumo::nlp::EmbeddingSetting>(GetArena());
    _impl_.setting_ = reinterpret_cast<::kumo::nlp::EmbeddingSetting*>(p);
  }
  return _impl_.setting_;
}
inline ::kumo::nlp::EmbeddingSetting* EmbeddingRequest::mutable_setting() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::kumo::nlp::EmbeddingSetting* _msg = _internal_mutable_setting();
  // @@protoc_insertion_point(field_mutable:kumo.nlp.EmbeddingRequest.setting)
  return _msg;
}
inline void EmbeddingRequest::set_allocated_setting(::kumo::nlp::EmbeddingSetting* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete (_impl_.setting_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = (value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.setting_ = reinterpret_cast<::kumo::nlp::EmbeddingSetting*>(value);
  // @@protoc_insertion_point(field_set_allocated:kumo.nlp.EmbeddingRequest.setting)
}

// -------------------------------------------------------------------

// EmbeddingResponse

// repeated float feature = 1;
inline int EmbeddingResponse::_internal_feature_size() const {
  return _internal_feature().size();
}
inline int EmbeddingResponse::feature_size() const {
  return _internal_feature_size();
}
inline void EmbeddingResponse::clear_feature() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.feature_.Clear();
}
inline float EmbeddingResponse::feature(int index) const {
  // @@protoc_insertion_point(field_get:kumo.nlp.EmbeddingResponse.feature)
  return _internal_feature().Get(index);
}
inline void EmbeddingResponse::set_feature(int index, float value) {
  _internal_mutable_feature()->Set(index, value);
  // @@protoc_insertion_point(field_set:kumo.nlp.EmbeddingResponse.feature)
}
inline void EmbeddingResponse::add_feature(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_feature()->Add(value);
  // @@protoc_insertion_point(field_add:kumo.nlp.EmbeddingResponse.feature)
}
inline const ::google::protobuf::RepeatedField<float>& EmbeddingResponse::feature() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:kumo.nlp.EmbeddingResponse.feature)
  return _internal_feature();
}
inline ::google::protobuf::RepeatedField<float>* EmbeddingResponse::mutable_feature()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:kumo.nlp.EmbeddingResponse.feature)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_feature();
}
inline const ::google::protobuf::RepeatedField<float>&
EmbeddingResponse::_internal_feature() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.feature_;
}
inline ::google::protobuf::RepeatedField<float>* EmbeddingResponse::_internal_mutable_feature() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.feature_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace nlp
}  // namespace kumo


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // gnef_2fproto_2fembdding_2eproto_2epb_2eh
