// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: gnef/proto/embdding.proto
// Protobuf C++ Version: 5.29.5

#include "gnef/proto/embdding.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace kumo {
namespace nlp {

inline constexpr EmbeddingSetting::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : model_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR EmbeddingSetting::EmbeddingSetting(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct EmbeddingSettingDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EmbeddingSettingDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~EmbeddingSettingDefaultTypeInternal() {}
  union {
    EmbeddingSetting _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EmbeddingSettingDefaultTypeInternal _EmbeddingSetting_default_instance_;

inline constexpr EmbeddingResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : feature_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR EmbeddingResponse::EmbeddingResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct EmbeddingResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EmbeddingResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~EmbeddingResponseDefaultTypeInternal() {}
  union {
    EmbeddingResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EmbeddingResponseDefaultTypeInternal _EmbeddingResponse_default_instance_;

inline constexpr EmbeddingRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        query_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        setting_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR EmbeddingRequest::EmbeddingRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct EmbeddingRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EmbeddingRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~EmbeddingRequestDefaultTypeInternal() {}
  union {
    EmbeddingRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EmbeddingRequestDefaultTypeInternal _EmbeddingRequest_default_instance_;
}  // namespace nlp
}  // namespace kumo
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_gnef_2fproto_2fembdding_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_gnef_2fproto_2fembdding_2eproto = nullptr;
const ::uint32_t
    TableStruct_gnef_2fproto_2fembdding_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::kumo::nlp::EmbeddingSetting, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::kumo::nlp::EmbeddingSetting, _impl_.model_),
        PROTOBUF_FIELD_OFFSET(::kumo::nlp::EmbeddingRequest, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::kumo::nlp::EmbeddingRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::kumo::nlp::EmbeddingRequest, _impl_.query_),
        PROTOBUF_FIELD_OFFSET(::kumo::nlp::EmbeddingRequest, _impl_.setting_),
        ~0u,
        0,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::kumo::nlp::EmbeddingResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::kumo::nlp::EmbeddingResponse, _impl_.feature_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::kumo::nlp::EmbeddingSetting)},
        {9, 19, -1, sizeof(::kumo::nlp::EmbeddingRequest)},
        {21, -1, -1, sizeof(::kumo::nlp::EmbeddingResponse)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::kumo::nlp::_EmbeddingSetting_default_instance_._instance,
    &::kumo::nlp::_EmbeddingRequest_default_instance_._instance,
    &::kumo::nlp::_EmbeddingResponse_default_instance_._instance,
};
const char descriptor_table_protodef_gnef_2fproto_2fembdding_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\031gnef/proto/embdding.proto\022\010kumo.nlp\"!\n"
    "\020EmbeddingSetting\022\r\n\005model\030\001 \001(\t\"N\n\020Embe"
    "ddingRequest\022\r\n\005query\030\001 \001(\t\022+\n\007setting\030\002"
    " \001(\0132\032.kumo.nlp.EmbeddingSetting\"$\n\021Embe"
    "ddingResponse\022\017\n\007feature\030\001 \003(\002b\006proto3"
};
static ::absl::once_flag descriptor_table_gnef_2fproto_2fembdding_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_gnef_2fproto_2fembdding_2eproto = {
    false,
    false,
    198,
    descriptor_table_protodef_gnef_2fproto_2fembdding_2eproto,
    "gnef/proto/embdding.proto",
    &descriptor_table_gnef_2fproto_2fembdding_2eproto_once,
    nullptr,
    0,
    3,
    schemas,
    file_default_instances,
    TableStruct_gnef_2fproto_2fembdding_2eproto::offsets,
    file_level_enum_descriptors_gnef_2fproto_2fembdding_2eproto,
    file_level_service_descriptors_gnef_2fproto_2fembdding_2eproto,
};
namespace kumo {
namespace nlp {
// ===================================================================

class EmbeddingSetting::_Internal {
 public:
};

EmbeddingSetting::EmbeddingSetting(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:kumo.nlp.EmbeddingSetting)
}
inline PROTOBUF_NDEBUG_INLINE EmbeddingSetting::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::kumo::nlp::EmbeddingSetting& from_msg)
      : model_(arena, from.model_),
        _cached_size_{0} {}

EmbeddingSetting::EmbeddingSetting(
    ::google::protobuf::Arena* arena,
    const EmbeddingSetting& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  EmbeddingSetting* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:kumo.nlp.EmbeddingSetting)
}
inline PROTOBUF_NDEBUG_INLINE EmbeddingSetting::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : model_(arena),
        _cached_size_{0} {}

inline void EmbeddingSetting::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
EmbeddingSetting::~EmbeddingSetting() {
  // @@protoc_insertion_point(destructor:kumo.nlp.EmbeddingSetting)
  SharedDtor(*this);
}
inline void EmbeddingSetting::SharedDtor(MessageLite& self) {
  EmbeddingSetting& this_ = static_cast<EmbeddingSetting&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.model_.Destroy();
  this_._impl_.~Impl_();
}

inline void* EmbeddingSetting::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) EmbeddingSetting(arena);
}
constexpr auto EmbeddingSetting::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(EmbeddingSetting),
                                            alignof(EmbeddingSetting));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull EmbeddingSetting::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_EmbeddingSetting_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &EmbeddingSetting::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<EmbeddingSetting>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &EmbeddingSetting::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<EmbeddingSetting>(), &EmbeddingSetting::ByteSizeLong,
            &EmbeddingSetting::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(EmbeddingSetting, _impl_._cached_size_),
        false,
    },
    &EmbeddingSetting::kDescriptorMethods,
    &descriptor_table_gnef_2fproto_2fembdding_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* EmbeddingSetting::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 39, 2> EmbeddingSetting::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::kumo::nlp::EmbeddingSetting>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string model = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(EmbeddingSetting, _impl_.model_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string model = 1;
    {PROTOBUF_FIELD_OFFSET(EmbeddingSetting, _impl_.model_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\31\5\0\0\0\0\0\0"
    "kumo.nlp.EmbeddingSetting"
    "model"
  }},
};

PROTOBUF_NOINLINE void EmbeddingSetting::Clear() {
// @@protoc_insertion_point(message_clear_start:kumo.nlp.EmbeddingSetting)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.model_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* EmbeddingSetting::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const EmbeddingSetting& this_ = static_cast<const EmbeddingSetting&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* EmbeddingSetting::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const EmbeddingSetting& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:kumo.nlp.EmbeddingSetting)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string model = 1;
          if (!this_._internal_model().empty()) {
            const std::string& _s = this_._internal_model();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "kumo.nlp.EmbeddingSetting.model");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:kumo.nlp.EmbeddingSetting)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t EmbeddingSetting::ByteSizeLong(const MessageLite& base) {
          const EmbeddingSetting& this_ = static_cast<const EmbeddingSetting&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t EmbeddingSetting::ByteSizeLong() const {
          const EmbeddingSetting& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:kumo.nlp.EmbeddingSetting)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // string model = 1;
            if (!this_._internal_model().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_model());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void EmbeddingSetting::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<EmbeddingSetting*>(&to_msg);
  auto& from = static_cast<const EmbeddingSetting&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:kumo.nlp.EmbeddingSetting)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_model().empty()) {
    _this->_internal_set_model(from._internal_model());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void EmbeddingSetting::CopyFrom(const EmbeddingSetting& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:kumo.nlp.EmbeddingSetting)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void EmbeddingSetting::InternalSwap(EmbeddingSetting* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.model_, &other->_impl_.model_, arena);
}

::google::protobuf::Metadata EmbeddingSetting::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class EmbeddingRequest::_Internal {
 public:
  using HasBits =
      decltype(std::declval<EmbeddingRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(EmbeddingRequest, _impl_._has_bits_);
};

EmbeddingRequest::EmbeddingRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:kumo.nlp.EmbeddingRequest)
}
inline PROTOBUF_NDEBUG_INLINE EmbeddingRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::kumo::nlp::EmbeddingRequest& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        query_(arena, from.query_) {}

EmbeddingRequest::EmbeddingRequest(
    ::google::protobuf::Arena* arena,
    const EmbeddingRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  EmbeddingRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.setting_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::kumo::nlp::EmbeddingSetting>(
                              arena, *from._impl_.setting_)
                        : nullptr;

  // @@protoc_insertion_point(copy_constructor:kumo.nlp.EmbeddingRequest)
}
inline PROTOBUF_NDEBUG_INLINE EmbeddingRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        query_(arena) {}

inline void EmbeddingRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.setting_ = {};
}
EmbeddingRequest::~EmbeddingRequest() {
  // @@protoc_insertion_point(destructor:kumo.nlp.EmbeddingRequest)
  SharedDtor(*this);
}
inline void EmbeddingRequest::SharedDtor(MessageLite& self) {
  EmbeddingRequest& this_ = static_cast<EmbeddingRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.query_.Destroy();
  delete this_._impl_.setting_;
  this_._impl_.~Impl_();
}

inline void* EmbeddingRequest::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) EmbeddingRequest(arena);
}
constexpr auto EmbeddingRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(EmbeddingRequest),
                                            alignof(EmbeddingRequest));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull EmbeddingRequest::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_EmbeddingRequest_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &EmbeddingRequest::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<EmbeddingRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &EmbeddingRequest::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<EmbeddingRequest>(), &EmbeddingRequest::ByteSizeLong,
            &EmbeddingRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(EmbeddingRequest, _impl_._cached_size_),
        false,
    },
    &EmbeddingRequest::kDescriptorMethods,
    &descriptor_table_gnef_2fproto_2fembdding_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* EmbeddingRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 39, 2> EmbeddingRequest::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(EmbeddingRequest, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::kumo::nlp::EmbeddingRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .kumo.nlp.EmbeddingSetting setting = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(EmbeddingRequest, _impl_.setting_)}},
    // string query = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(EmbeddingRequest, _impl_.query_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string query = 1;
    {PROTOBUF_FIELD_OFFSET(EmbeddingRequest, _impl_.query_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .kumo.nlp.EmbeddingSetting setting = 2;
    {PROTOBUF_FIELD_OFFSET(EmbeddingRequest, _impl_.setting_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::kumo::nlp::EmbeddingSetting>()},
  }}, {{
    "\31\5\0\0\0\0\0\0"
    "kumo.nlp.EmbeddingRequest"
    "query"
  }},
};

PROTOBUF_NOINLINE void EmbeddingRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:kumo.nlp.EmbeddingRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.query_.ClearToEmpty();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.setting_ != nullptr);
    _impl_.setting_->Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* EmbeddingRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const EmbeddingRequest& this_ = static_cast<const EmbeddingRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* EmbeddingRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const EmbeddingRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:kumo.nlp.EmbeddingRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string query = 1;
          if (!this_._internal_query().empty()) {
            const std::string& _s = this_._internal_query();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "kumo.nlp.EmbeddingRequest.query");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          cached_has_bits = this_._impl_._has_bits_[0];
          // .kumo.nlp.EmbeddingSetting setting = 2;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                2, *this_._impl_.setting_, this_._impl_.setting_->GetCachedSize(), target,
                stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:kumo.nlp.EmbeddingRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t EmbeddingRequest::ByteSizeLong(const MessageLite& base) {
          const EmbeddingRequest& this_ = static_cast<const EmbeddingRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t EmbeddingRequest::ByteSizeLong() const {
          const EmbeddingRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:kumo.nlp.EmbeddingRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string query = 1;
            if (!this_._internal_query().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_query());
            }
          }
           {
            // .kumo.nlp.EmbeddingSetting setting = 2;
            cached_has_bits = this_._impl_._has_bits_[0];
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.setting_);
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void EmbeddingRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<EmbeddingRequest*>(&to_msg);
  auto& from = static_cast<const EmbeddingRequest&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:kumo.nlp.EmbeddingRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_query().empty()) {
    _this->_internal_set_query(from._internal_query());
  }
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(from._impl_.setting_ != nullptr);
    if (_this->_impl_.setting_ == nullptr) {
      _this->_impl_.setting_ =
          ::google::protobuf::Message::CopyConstruct<::kumo::nlp::EmbeddingSetting>(arena, *from._impl_.setting_);
    } else {
      _this->_impl_.setting_->MergeFrom(*from._impl_.setting_);
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void EmbeddingRequest::CopyFrom(const EmbeddingRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:kumo.nlp.EmbeddingRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void EmbeddingRequest::InternalSwap(EmbeddingRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.query_, &other->_impl_.query_, arena);
  swap(_impl_.setting_, other->_impl_.setting_);
}

::google::protobuf::Metadata EmbeddingRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class EmbeddingResponse::_Internal {
 public:
};

EmbeddingResponse::EmbeddingResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:kumo.nlp.EmbeddingResponse)
}
inline PROTOBUF_NDEBUG_INLINE EmbeddingResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::kumo::nlp::EmbeddingResponse& from_msg)
      : feature_{visibility, arena, from.feature_},
        _cached_size_{0} {}

EmbeddingResponse::EmbeddingResponse(
    ::google::protobuf::Arena* arena,
    const EmbeddingResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  EmbeddingResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:kumo.nlp.EmbeddingResponse)
}
inline PROTOBUF_NDEBUG_INLINE EmbeddingResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : feature_{visibility, arena},
        _cached_size_{0} {}

inline void EmbeddingResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
EmbeddingResponse::~EmbeddingResponse() {
  // @@protoc_insertion_point(destructor:kumo.nlp.EmbeddingResponse)
  SharedDtor(*this);
}
inline void EmbeddingResponse::SharedDtor(MessageLite& self) {
  EmbeddingResponse& this_ = static_cast<EmbeddingResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* EmbeddingResponse::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) EmbeddingResponse(arena);
}
constexpr auto EmbeddingResponse::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(EmbeddingResponse, _impl_.feature_) +
          decltype(EmbeddingResponse::_impl_.feature_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(EmbeddingResponse), alignof(EmbeddingResponse), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&EmbeddingResponse::PlacementNew_,
                                 sizeof(EmbeddingResponse),
                                 alignof(EmbeddingResponse));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull EmbeddingResponse::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_EmbeddingResponse_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &EmbeddingResponse::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<EmbeddingResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &EmbeddingResponse::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<EmbeddingResponse>(), &EmbeddingResponse::ByteSizeLong,
            &EmbeddingResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(EmbeddingResponse, _impl_._cached_size_),
        false,
    },
    &EmbeddingResponse::kDescriptorMethods,
    &descriptor_table_gnef_2fproto_2fembdding_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* EmbeddingResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> EmbeddingResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::kumo::nlp::EmbeddingResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated float feature = 1;
    {::_pbi::TcParser::FastF32P1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(EmbeddingResponse, _impl_.feature_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated float feature = 1;
    {PROTOBUF_FIELD_OFFSET(EmbeddingResponse, _impl_.feature_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedFloat)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void EmbeddingResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:kumo.nlp.EmbeddingResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.feature_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* EmbeddingResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const EmbeddingResponse& this_ = static_cast<const EmbeddingResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* EmbeddingResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const EmbeddingResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:kumo.nlp.EmbeddingResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // repeated float feature = 1;
          if (this_._internal_feature_size() > 0) {
            target = stream->WriteFixedPacked(1, this_._internal_feature(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:kumo.nlp.EmbeddingResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t EmbeddingResponse::ByteSizeLong(const MessageLite& base) {
          const EmbeddingResponse& this_ = static_cast<const EmbeddingResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t EmbeddingResponse::ByteSizeLong() const {
          const EmbeddingResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:kumo.nlp.EmbeddingResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated float feature = 1;
            {
              std::size_t data_size = std::size_t{4} *
                  ::_pbi::FromIntSize(this_._internal_feature_size());
              std::size_t tag_size = data_size == 0
                  ? 0
                  : 1 + ::_pbi::WireFormatLite::Int32Size(
                                      static_cast<int32_t>(data_size));
              total_size += tag_size + data_size;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void EmbeddingResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<EmbeddingResponse*>(&to_msg);
  auto& from = static_cast<const EmbeddingResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:kumo.nlp.EmbeddingResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_feature()->MergeFrom(from._internal_feature());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void EmbeddingResponse::CopyFrom(const EmbeddingResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:kumo.nlp.EmbeddingResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void EmbeddingResponse::InternalSwap(EmbeddingResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.feature_.InternalSwap(&other->_impl_.feature_);
}

::google::protobuf::Metadata EmbeddingResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace nlp
}  // namespace kumo
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_gnef_2fproto_2fembdding_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
