// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: gnef/proto/normalize.proto
// Protobuf C++ Version: 5.29.5

#include "gnef/proto/normalize.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace kumo {
namespace nlp {

inline constexpr NormalizeSetting::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : full_to_half_{false},
        upper_to_lower_{false},
        blank_to_one_{false},
        lang_detect_{false},
        remove_bad_char_{false},
        remove_emoji_{false},
        punctuation_to_space_{false},
        remove_punctuation_{false},
        zh_to_pin_{false},
        zh_to_pin_short_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR NormalizeSetting::NormalizeSetting(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct NormalizeSettingDefaultTypeInternal {
  PROTOBUF_CONSTEXPR NormalizeSettingDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~NormalizeSettingDefaultTypeInternal() {}
  union {
    NormalizeSetting _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 NormalizeSettingDefaultTypeInternal _NormalizeSetting_default_instance_;

inline constexpr NormalizeResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : query_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        pinyin_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        pinyin_short_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR NormalizeResponse::NormalizeResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct NormalizeResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR NormalizeResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~NormalizeResponseDefaultTypeInternal() {}
  union {
    NormalizeResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 NormalizeResponseDefaultTypeInternal _NormalizeResponse_default_instance_;

inline constexpr NormalizeRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        query_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        setting_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR NormalizeRequest::NormalizeRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct NormalizeRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR NormalizeRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~NormalizeRequestDefaultTypeInternal() {}
  union {
    NormalizeRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 NormalizeRequestDefaultTypeInternal _NormalizeRequest_default_instance_;
}  // namespace nlp
}  // namespace kumo
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_gnef_2fproto_2fnormalize_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_gnef_2fproto_2fnormalize_2eproto = nullptr;
const ::uint32_t
    TableStruct_gnef_2fproto_2fnormalize_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::kumo::nlp::NormalizeSetting, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::kumo::nlp::NormalizeSetting, _impl_.full_to_half_),
        PROTOBUF_FIELD_OFFSET(::kumo::nlp::NormalizeSetting, _impl_.upper_to_lower_),
        PROTOBUF_FIELD_OFFSET(::kumo::nlp::NormalizeSetting, _impl_.blank_to_one_),
        PROTOBUF_FIELD_OFFSET(::kumo::nlp::NormalizeSetting, _impl_.lang_detect_),
        PROTOBUF_FIELD_OFFSET(::kumo::nlp::NormalizeSetting, _impl_.remove_bad_char_),
        PROTOBUF_FIELD_OFFSET(::kumo::nlp::NormalizeSetting, _impl_.remove_emoji_),
        PROTOBUF_FIELD_OFFSET(::kumo::nlp::NormalizeSetting, _impl_.punctuation_to_space_),
        PROTOBUF_FIELD_OFFSET(::kumo::nlp::NormalizeSetting, _impl_.remove_punctuation_),
        PROTOBUF_FIELD_OFFSET(::kumo::nlp::NormalizeSetting, _impl_.zh_to_pin_),
        PROTOBUF_FIELD_OFFSET(::kumo::nlp::NormalizeSetting, _impl_.zh_to_pin_short_),
        PROTOBUF_FIELD_OFFSET(::kumo::nlp::NormalizeRequest, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::kumo::nlp::NormalizeRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::kumo::nlp::NormalizeRequest, _impl_.query_),
        PROTOBUF_FIELD_OFFSET(::kumo::nlp::NormalizeRequest, _impl_.setting_),
        ~0u,
        0,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::kumo::nlp::NormalizeResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::kumo::nlp::NormalizeResponse, _impl_.query_),
        PROTOBUF_FIELD_OFFSET(::kumo::nlp::NormalizeResponse, _impl_.pinyin_),
        PROTOBUF_FIELD_OFFSET(::kumo::nlp::NormalizeResponse, _impl_.pinyin_short_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::kumo::nlp::NormalizeSetting)},
        {18, 28, -1, sizeof(::kumo::nlp::NormalizeRequest)},
        {30, -1, -1, sizeof(::kumo::nlp::NormalizeResponse)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::kumo::nlp::_NormalizeSetting_default_instance_._instance,
    &::kumo::nlp::_NormalizeRequest_default_instance_._instance,
    &::kumo::nlp::_NormalizeResponse_default_instance_._instance,
};
const char descriptor_table_protodef_gnef_2fproto_2fnormalize_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\032gnef/proto/normalize.proto\022\010kumo.nlp\"\200"
    "\002\n\020NormalizeSetting\022\024\n\014full_to_half\030\001 \001("
    "\010\022\026\n\016upper_to_lower\030\002 \001(\010\022\024\n\014blank_to_on"
    "e\030\003 \001(\010\022\023\n\013lang_detect\030\004 \001(\010\022\027\n\017remove_b"
    "ad_char\030\005 \001(\010\022\024\n\014remove_emoji\030\006 \001(\010\022\034\n\024p"
    "unctuation_to_space\030\007 \001(\010\022\032\n\022remove_punc"
    "tuation\030\010 \001(\010\022\021\n\tzh_to_pin\030\t \001(\010\022\027\n\017zh_t"
    "o_pin_short\030\n \001(\010\"N\n\020NormalizeRequest\022\r\n"
    "\005query\030\001 \001(\t\022+\n\007setting\030\002 \001(\0132\032.kumo.nlp"
    ".NormalizeSetting\"H\n\021NormalizeResponse\022\r"
    "\n\005query\030\001 \001(\t\022\016\n\006pinyin\030\002 \001(\t\022\024\n\014pinyin_"
    "short\030\003 \001(\t*\307\001\n\017NormalizeOption\022\022\n\016NORMA"
    "LIZE_NONE\020\000\022 \n\034NORMALIZE_FULL_WIDTH_TO_H"
    "ALF\020\001\022!\n\035NORMALIZE_UPPER_CASE_TO_LOWER\020\002"
    "\022 \n\034NORMALIZE_BLANK_TO_ONE_SPACE\020\004\022\035\n\031NO"
    "RMALIZE_REMOVE_BAD_CHAR\020\010\022\032\n\026NORMALIZE_R"
    "EMOVE_EMOJI\020\020b\006proto3"
};
static ::absl::once_flag descriptor_table_gnef_2fproto_2fnormalize_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_gnef_2fproto_2fnormalize_2eproto = {
    false,
    false,
    661,
    descriptor_table_protodef_gnef_2fproto_2fnormalize_2eproto,
    "gnef/proto/normalize.proto",
    &descriptor_table_gnef_2fproto_2fnormalize_2eproto_once,
    nullptr,
    0,
    3,
    schemas,
    file_default_instances,
    TableStruct_gnef_2fproto_2fnormalize_2eproto::offsets,
    file_level_enum_descriptors_gnef_2fproto_2fnormalize_2eproto,
    file_level_service_descriptors_gnef_2fproto_2fnormalize_2eproto,
};
namespace kumo {
namespace nlp {
const ::google::protobuf::EnumDescriptor* NormalizeOption_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_gnef_2fproto_2fnormalize_2eproto);
  return file_level_enum_descriptors_gnef_2fproto_2fnormalize_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t NormalizeOption_internal_data_[] = {
    196608u, 32u, 8226u, };
bool NormalizeOption_IsValid(int value) {
  return 0 <= value && value <= 16 && ((65815u >> value) & 1) != 0;
}
// ===================================================================

class NormalizeSetting::_Internal {
 public:
};

NormalizeSetting::NormalizeSetting(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:kumo.nlp.NormalizeSetting)
}
NormalizeSetting::NormalizeSetting(
    ::google::protobuf::Arena* arena, const NormalizeSetting& from)
    : NormalizeSetting(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE NormalizeSetting::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void NormalizeSetting::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, full_to_half_),
           0,
           offsetof(Impl_, zh_to_pin_short_) -
               offsetof(Impl_, full_to_half_) +
               sizeof(Impl_::zh_to_pin_short_));
}
NormalizeSetting::~NormalizeSetting() {
  // @@protoc_insertion_point(destructor:kumo.nlp.NormalizeSetting)
  SharedDtor(*this);
}
inline void NormalizeSetting::SharedDtor(MessageLite& self) {
  NormalizeSetting& this_ = static_cast<NormalizeSetting&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* NormalizeSetting::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) NormalizeSetting(arena);
}
constexpr auto NormalizeSetting::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(NormalizeSetting),
                                            alignof(NormalizeSetting));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull NormalizeSetting::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_NormalizeSetting_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &NormalizeSetting::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<NormalizeSetting>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &NormalizeSetting::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<NormalizeSetting>(), &NormalizeSetting::ByteSizeLong,
            &NormalizeSetting::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(NormalizeSetting, _impl_._cached_size_),
        false,
    },
    &NormalizeSetting::kDescriptorMethods,
    &descriptor_table_gnef_2fproto_2fnormalize_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* NormalizeSetting::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<4, 10, 0, 0, 2> NormalizeSetting::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    10, 120,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294966272,  // skipmap
    offsetof(decltype(_table_), field_entries),
    10,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::kumo::nlp::NormalizeSetting>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // bool full_to_half = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(NormalizeSetting, _impl_.full_to_half_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(NormalizeSetting, _impl_.full_to_half_)}},
    // bool upper_to_lower = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(NormalizeSetting, _impl_.upper_to_lower_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(NormalizeSetting, _impl_.upper_to_lower_)}},
    // bool blank_to_one = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(NormalizeSetting, _impl_.blank_to_one_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(NormalizeSetting, _impl_.blank_to_one_)}},
    // bool lang_detect = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(NormalizeSetting, _impl_.lang_detect_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(NormalizeSetting, _impl_.lang_detect_)}},
    // bool remove_bad_char = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(NormalizeSetting, _impl_.remove_bad_char_), 63>(),
     {40, 63, 0, PROTOBUF_FIELD_OFFSET(NormalizeSetting, _impl_.remove_bad_char_)}},
    // bool remove_emoji = 6;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(NormalizeSetting, _impl_.remove_emoji_), 63>(),
     {48, 63, 0, PROTOBUF_FIELD_OFFSET(NormalizeSetting, _impl_.remove_emoji_)}},
    // bool punctuation_to_space = 7;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(NormalizeSetting, _impl_.punctuation_to_space_), 63>(),
     {56, 63, 0, PROTOBUF_FIELD_OFFSET(NormalizeSetting, _impl_.punctuation_to_space_)}},
    // bool remove_punctuation = 8;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(NormalizeSetting, _impl_.remove_punctuation_), 63>(),
     {64, 63, 0, PROTOBUF_FIELD_OFFSET(NormalizeSetting, _impl_.remove_punctuation_)}},
    // bool zh_to_pin = 9;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(NormalizeSetting, _impl_.zh_to_pin_), 63>(),
     {72, 63, 0, PROTOBUF_FIELD_OFFSET(NormalizeSetting, _impl_.zh_to_pin_)}},
    // bool zh_to_pin_short = 10;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(NormalizeSetting, _impl_.zh_to_pin_short_), 63>(),
     {80, 63, 0, PROTOBUF_FIELD_OFFSET(NormalizeSetting, _impl_.zh_to_pin_short_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // bool full_to_half = 1;
    {PROTOBUF_FIELD_OFFSET(NormalizeSetting, _impl_.full_to_half_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // bool upper_to_lower = 2;
    {PROTOBUF_FIELD_OFFSET(NormalizeSetting, _impl_.upper_to_lower_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // bool blank_to_one = 3;
    {PROTOBUF_FIELD_OFFSET(NormalizeSetting, _impl_.blank_to_one_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // bool lang_detect = 4;
    {PROTOBUF_FIELD_OFFSET(NormalizeSetting, _impl_.lang_detect_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // bool remove_bad_char = 5;
    {PROTOBUF_FIELD_OFFSET(NormalizeSetting, _impl_.remove_bad_char_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // bool remove_emoji = 6;
    {PROTOBUF_FIELD_OFFSET(NormalizeSetting, _impl_.remove_emoji_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // bool punctuation_to_space = 7;
    {PROTOBUF_FIELD_OFFSET(NormalizeSetting, _impl_.punctuation_to_space_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // bool remove_punctuation = 8;
    {PROTOBUF_FIELD_OFFSET(NormalizeSetting, _impl_.remove_punctuation_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // bool zh_to_pin = 9;
    {PROTOBUF_FIELD_OFFSET(NormalizeSetting, _impl_.zh_to_pin_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // bool zh_to_pin_short = 10;
    {PROTOBUF_FIELD_OFFSET(NormalizeSetting, _impl_.zh_to_pin_short_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void NormalizeSetting::Clear() {
// @@protoc_insertion_point(message_clear_start:kumo.nlp.NormalizeSetting)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.full_to_half_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.zh_to_pin_short_) -
      reinterpret_cast<char*>(&_impl_.full_to_half_)) + sizeof(_impl_.zh_to_pin_short_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* NormalizeSetting::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const NormalizeSetting& this_ = static_cast<const NormalizeSetting&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* NormalizeSetting::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const NormalizeSetting& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:kumo.nlp.NormalizeSetting)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // bool full_to_half = 1;
          if (this_._internal_full_to_half() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                1, this_._internal_full_to_half(), target);
          }

          // bool upper_to_lower = 2;
          if (this_._internal_upper_to_lower() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                2, this_._internal_upper_to_lower(), target);
          }

          // bool blank_to_one = 3;
          if (this_._internal_blank_to_one() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                3, this_._internal_blank_to_one(), target);
          }

          // bool lang_detect = 4;
          if (this_._internal_lang_detect() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                4, this_._internal_lang_detect(), target);
          }

          // bool remove_bad_char = 5;
          if (this_._internal_remove_bad_char() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                5, this_._internal_remove_bad_char(), target);
          }

          // bool remove_emoji = 6;
          if (this_._internal_remove_emoji() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                6, this_._internal_remove_emoji(), target);
          }

          // bool punctuation_to_space = 7;
          if (this_._internal_punctuation_to_space() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                7, this_._internal_punctuation_to_space(), target);
          }

          // bool remove_punctuation = 8;
          if (this_._internal_remove_punctuation() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                8, this_._internal_remove_punctuation(), target);
          }

          // bool zh_to_pin = 9;
          if (this_._internal_zh_to_pin() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                9, this_._internal_zh_to_pin(), target);
          }

          // bool zh_to_pin_short = 10;
          if (this_._internal_zh_to_pin_short() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                10, this_._internal_zh_to_pin_short(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:kumo.nlp.NormalizeSetting)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t NormalizeSetting::ByteSizeLong(const MessageLite& base) {
          const NormalizeSetting& this_ = static_cast<const NormalizeSetting&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t NormalizeSetting::ByteSizeLong() const {
          const NormalizeSetting& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:kumo.nlp.NormalizeSetting)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // bool full_to_half = 1;
            if (this_._internal_full_to_half() != 0) {
              total_size += 2;
            }
            // bool upper_to_lower = 2;
            if (this_._internal_upper_to_lower() != 0) {
              total_size += 2;
            }
            // bool blank_to_one = 3;
            if (this_._internal_blank_to_one() != 0) {
              total_size += 2;
            }
            // bool lang_detect = 4;
            if (this_._internal_lang_detect() != 0) {
              total_size += 2;
            }
            // bool remove_bad_char = 5;
            if (this_._internal_remove_bad_char() != 0) {
              total_size += 2;
            }
            // bool remove_emoji = 6;
            if (this_._internal_remove_emoji() != 0) {
              total_size += 2;
            }
            // bool punctuation_to_space = 7;
            if (this_._internal_punctuation_to_space() != 0) {
              total_size += 2;
            }
            // bool remove_punctuation = 8;
            if (this_._internal_remove_punctuation() != 0) {
              total_size += 2;
            }
            // bool zh_to_pin = 9;
            if (this_._internal_zh_to_pin() != 0) {
              total_size += 2;
            }
            // bool zh_to_pin_short = 10;
            if (this_._internal_zh_to_pin_short() != 0) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void NormalizeSetting::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<NormalizeSetting*>(&to_msg);
  auto& from = static_cast<const NormalizeSetting&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:kumo.nlp.NormalizeSetting)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_full_to_half() != 0) {
    _this->_impl_.full_to_half_ = from._impl_.full_to_half_;
  }
  if (from._internal_upper_to_lower() != 0) {
    _this->_impl_.upper_to_lower_ = from._impl_.upper_to_lower_;
  }
  if (from._internal_blank_to_one() != 0) {
    _this->_impl_.blank_to_one_ = from._impl_.blank_to_one_;
  }
  if (from._internal_lang_detect() != 0) {
    _this->_impl_.lang_detect_ = from._impl_.lang_detect_;
  }
  if (from._internal_remove_bad_char() != 0) {
    _this->_impl_.remove_bad_char_ = from._impl_.remove_bad_char_;
  }
  if (from._internal_remove_emoji() != 0) {
    _this->_impl_.remove_emoji_ = from._impl_.remove_emoji_;
  }
  if (from._internal_punctuation_to_space() != 0) {
    _this->_impl_.punctuation_to_space_ = from._impl_.punctuation_to_space_;
  }
  if (from._internal_remove_punctuation() != 0) {
    _this->_impl_.remove_punctuation_ = from._impl_.remove_punctuation_;
  }
  if (from._internal_zh_to_pin() != 0) {
    _this->_impl_.zh_to_pin_ = from._impl_.zh_to_pin_;
  }
  if (from._internal_zh_to_pin_short() != 0) {
    _this->_impl_.zh_to_pin_short_ = from._impl_.zh_to_pin_short_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void NormalizeSetting::CopyFrom(const NormalizeSetting& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:kumo.nlp.NormalizeSetting)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void NormalizeSetting::InternalSwap(NormalizeSetting* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(NormalizeSetting, _impl_.zh_to_pin_short_)
      + sizeof(NormalizeSetting::_impl_.zh_to_pin_short_)
      - PROTOBUF_FIELD_OFFSET(NormalizeSetting, _impl_.full_to_half_)>(
          reinterpret_cast<char*>(&_impl_.full_to_half_),
          reinterpret_cast<char*>(&other->_impl_.full_to_half_));
}

::google::protobuf::Metadata NormalizeSetting::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class NormalizeRequest::_Internal {
 public:
  using HasBits =
      decltype(std::declval<NormalizeRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(NormalizeRequest, _impl_._has_bits_);
};

NormalizeRequest::NormalizeRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:kumo.nlp.NormalizeRequest)
}
inline PROTOBUF_NDEBUG_INLINE NormalizeRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::kumo::nlp::NormalizeRequest& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        query_(arena, from.query_) {}

NormalizeRequest::NormalizeRequest(
    ::google::protobuf::Arena* arena,
    const NormalizeRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  NormalizeRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.setting_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::kumo::nlp::NormalizeSetting>(
                              arena, *from._impl_.setting_)
                        : nullptr;

  // @@protoc_insertion_point(copy_constructor:kumo.nlp.NormalizeRequest)
}
inline PROTOBUF_NDEBUG_INLINE NormalizeRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        query_(arena) {}

inline void NormalizeRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.setting_ = {};
}
NormalizeRequest::~NormalizeRequest() {
  // @@protoc_insertion_point(destructor:kumo.nlp.NormalizeRequest)
  SharedDtor(*this);
}
inline void NormalizeRequest::SharedDtor(MessageLite& self) {
  NormalizeRequest& this_ = static_cast<NormalizeRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.query_.Destroy();
  delete this_._impl_.setting_;
  this_._impl_.~Impl_();
}

inline void* NormalizeRequest::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) NormalizeRequest(arena);
}
constexpr auto NormalizeRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(NormalizeRequest),
                                            alignof(NormalizeRequest));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull NormalizeRequest::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_NormalizeRequest_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &NormalizeRequest::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<NormalizeRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &NormalizeRequest::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<NormalizeRequest>(), &NormalizeRequest::ByteSizeLong,
            &NormalizeRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(NormalizeRequest, _impl_._cached_size_),
        false,
    },
    &NormalizeRequest::kDescriptorMethods,
    &descriptor_table_gnef_2fproto_2fnormalize_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* NormalizeRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 39, 2> NormalizeRequest::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(NormalizeRequest, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::kumo::nlp::NormalizeRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .kumo.nlp.NormalizeSetting setting = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(NormalizeRequest, _impl_.setting_)}},
    // string query = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(NormalizeRequest, _impl_.query_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string query = 1;
    {PROTOBUF_FIELD_OFFSET(NormalizeRequest, _impl_.query_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .kumo.nlp.NormalizeSetting setting = 2;
    {PROTOBUF_FIELD_OFFSET(NormalizeRequest, _impl_.setting_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::kumo::nlp::NormalizeSetting>()},
  }}, {{
    "\31\5\0\0\0\0\0\0"
    "kumo.nlp.NormalizeRequest"
    "query"
  }},
};

PROTOBUF_NOINLINE void NormalizeRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:kumo.nlp.NormalizeRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.query_.ClearToEmpty();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.setting_ != nullptr);
    _impl_.setting_->Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* NormalizeRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const NormalizeRequest& this_ = static_cast<const NormalizeRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* NormalizeRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const NormalizeRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:kumo.nlp.NormalizeRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string query = 1;
          if (!this_._internal_query().empty()) {
            const std::string& _s = this_._internal_query();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "kumo.nlp.NormalizeRequest.query");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          cached_has_bits = this_._impl_._has_bits_[0];
          // .kumo.nlp.NormalizeSetting setting = 2;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                2, *this_._impl_.setting_, this_._impl_.setting_->GetCachedSize(), target,
                stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:kumo.nlp.NormalizeRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t NormalizeRequest::ByteSizeLong(const MessageLite& base) {
          const NormalizeRequest& this_ = static_cast<const NormalizeRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t NormalizeRequest::ByteSizeLong() const {
          const NormalizeRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:kumo.nlp.NormalizeRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string query = 1;
            if (!this_._internal_query().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_query());
            }
          }
           {
            // .kumo.nlp.NormalizeSetting setting = 2;
            cached_has_bits = this_._impl_._has_bits_[0];
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.setting_);
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void NormalizeRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<NormalizeRequest*>(&to_msg);
  auto& from = static_cast<const NormalizeRequest&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:kumo.nlp.NormalizeRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_query().empty()) {
    _this->_internal_set_query(from._internal_query());
  }
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(from._impl_.setting_ != nullptr);
    if (_this->_impl_.setting_ == nullptr) {
      _this->_impl_.setting_ =
          ::google::protobuf::Message::CopyConstruct<::kumo::nlp::NormalizeSetting>(arena, *from._impl_.setting_);
    } else {
      _this->_impl_.setting_->MergeFrom(*from._impl_.setting_);
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void NormalizeRequest::CopyFrom(const NormalizeRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:kumo.nlp.NormalizeRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void NormalizeRequest::InternalSwap(NormalizeRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.query_, &other->_impl_.query_, arena);
  swap(_impl_.setting_, other->_impl_.setting_);
}

::google::protobuf::Metadata NormalizeRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class NormalizeResponse::_Internal {
 public:
};

NormalizeResponse::NormalizeResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:kumo.nlp.NormalizeResponse)
}
inline PROTOBUF_NDEBUG_INLINE NormalizeResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::kumo::nlp::NormalizeResponse& from_msg)
      : query_(arena, from.query_),
        pinyin_(arena, from.pinyin_),
        pinyin_short_(arena, from.pinyin_short_),
        _cached_size_{0} {}

NormalizeResponse::NormalizeResponse(
    ::google::protobuf::Arena* arena,
    const NormalizeResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  NormalizeResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:kumo.nlp.NormalizeResponse)
}
inline PROTOBUF_NDEBUG_INLINE NormalizeResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : query_(arena),
        pinyin_(arena),
        pinyin_short_(arena),
        _cached_size_{0} {}

inline void NormalizeResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
NormalizeResponse::~NormalizeResponse() {
  // @@protoc_insertion_point(destructor:kumo.nlp.NormalizeResponse)
  SharedDtor(*this);
}
inline void NormalizeResponse::SharedDtor(MessageLite& self) {
  NormalizeResponse& this_ = static_cast<NormalizeResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.query_.Destroy();
  this_._impl_.pinyin_.Destroy();
  this_._impl_.pinyin_short_.Destroy();
  this_._impl_.~Impl_();
}

inline void* NormalizeResponse::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) NormalizeResponse(arena);
}
constexpr auto NormalizeResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(NormalizeResponse),
                                            alignof(NormalizeResponse));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull NormalizeResponse::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_NormalizeResponse_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &NormalizeResponse::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<NormalizeResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &NormalizeResponse::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<NormalizeResponse>(), &NormalizeResponse::ByteSizeLong,
            &NormalizeResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(NormalizeResponse, _impl_._cached_size_),
        false,
    },
    &NormalizeResponse::kDescriptorMethods,
    &descriptor_table_gnef_2fproto_2fnormalize_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* NormalizeResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 58, 2> NormalizeResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::kumo::nlp::NormalizeResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string query = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(NormalizeResponse, _impl_.query_)}},
    // string pinyin = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(NormalizeResponse, _impl_.pinyin_)}},
    // string pinyin_short = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(NormalizeResponse, _impl_.pinyin_short_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string query = 1;
    {PROTOBUF_FIELD_OFFSET(NormalizeResponse, _impl_.query_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string pinyin = 2;
    {PROTOBUF_FIELD_OFFSET(NormalizeResponse, _impl_.pinyin_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string pinyin_short = 3;
    {PROTOBUF_FIELD_OFFSET(NormalizeResponse, _impl_.pinyin_short_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\32\5\6\14\0\0\0\0"
    "kumo.nlp.NormalizeResponse"
    "query"
    "pinyin"
    "pinyin_short"
  }},
};

PROTOBUF_NOINLINE void NormalizeResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:kumo.nlp.NormalizeResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.query_.ClearToEmpty();
  _impl_.pinyin_.ClearToEmpty();
  _impl_.pinyin_short_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* NormalizeResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const NormalizeResponse& this_ = static_cast<const NormalizeResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* NormalizeResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const NormalizeResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:kumo.nlp.NormalizeResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string query = 1;
          if (!this_._internal_query().empty()) {
            const std::string& _s = this_._internal_query();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "kumo.nlp.NormalizeResponse.query");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // string pinyin = 2;
          if (!this_._internal_pinyin().empty()) {
            const std::string& _s = this_._internal_pinyin();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "kumo.nlp.NormalizeResponse.pinyin");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          // string pinyin_short = 3;
          if (!this_._internal_pinyin_short().empty()) {
            const std::string& _s = this_._internal_pinyin_short();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "kumo.nlp.NormalizeResponse.pinyin_short");
            target = stream->WriteStringMaybeAliased(3, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:kumo.nlp.NormalizeResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t NormalizeResponse::ByteSizeLong(const MessageLite& base) {
          const NormalizeResponse& this_ = static_cast<const NormalizeResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t NormalizeResponse::ByteSizeLong() const {
          const NormalizeResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:kumo.nlp.NormalizeResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string query = 1;
            if (!this_._internal_query().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_query());
            }
            // string pinyin = 2;
            if (!this_._internal_pinyin().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_pinyin());
            }
            // string pinyin_short = 3;
            if (!this_._internal_pinyin_short().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_pinyin_short());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void NormalizeResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<NormalizeResponse*>(&to_msg);
  auto& from = static_cast<const NormalizeResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:kumo.nlp.NormalizeResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_query().empty()) {
    _this->_internal_set_query(from._internal_query());
  }
  if (!from._internal_pinyin().empty()) {
    _this->_internal_set_pinyin(from._internal_pinyin());
  }
  if (!from._internal_pinyin_short().empty()) {
    _this->_internal_set_pinyin_short(from._internal_pinyin_short());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void NormalizeResponse::CopyFrom(const NormalizeResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:kumo.nlp.NormalizeResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void NormalizeResponse::InternalSwap(NormalizeResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.query_, &other->_impl_.query_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.pinyin_, &other->_impl_.pinyin_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.pinyin_short_, &other->_impl_.pinyin_short_, arena);
}

::google::protobuf::Metadata NormalizeResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace nlp
}  // namespace kumo
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_gnef_2fproto_2fnormalize_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
