// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: gnef/proto/normalize.proto
// Protobuf C++ Version: 5.29.5

#ifndef gnef_2fproto_2fnormalize_2eproto_2epb_2eh
#define gnef_2fproto_2fnormalize_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029005
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_gnef_2fproto_2fnormalize_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_gnef_2fproto_2fnormalize_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_gnef_2fproto_2fnormalize_2eproto;
namespace kumo {
namespace nlp {
class NormalizeRequest;
struct NormalizeRequestDefaultTypeInternal;
extern NormalizeRequestDefaultTypeInternal _NormalizeRequest_default_instance_;
class NormalizeResponse;
struct NormalizeResponseDefaultTypeInternal;
extern NormalizeResponseDefaultTypeInternal _NormalizeResponse_default_instance_;
class NormalizeSetting;
struct NormalizeSettingDefaultTypeInternal;
extern NormalizeSettingDefaultTypeInternal _NormalizeSetting_default_instance_;
}  // namespace nlp
}  // namespace kumo
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace kumo {
namespace nlp {
enum NormalizeOption : int {
  NORMALIZE_NONE = 0,
  NORMALIZE_FULL_WIDTH_TO_HALF = 1,
  NORMALIZE_UPPER_CASE_TO_LOWER = 2,
  NORMALIZE_BLANK_TO_ONE_SPACE = 4,
  NORMALIZE_REMOVE_BAD_CHAR = 8,
  NORMALIZE_REMOVE_EMOJI = 16,
  NormalizeOption_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  NormalizeOption_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool NormalizeOption_IsValid(int value);
extern const uint32_t NormalizeOption_internal_data_[];
constexpr NormalizeOption NormalizeOption_MIN = static_cast<NormalizeOption>(0);
constexpr NormalizeOption NormalizeOption_MAX = static_cast<NormalizeOption>(16);
constexpr int NormalizeOption_ARRAYSIZE = 16 + 1;
const ::google::protobuf::EnumDescriptor*
NormalizeOption_descriptor();
template <typename T>
const std::string& NormalizeOption_Name(T value) {
  static_assert(std::is_same<T, NormalizeOption>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to NormalizeOption_Name().");
  return ::google::protobuf::internal::NameOfEnum(NormalizeOption_descriptor(), value);
}
inline bool NormalizeOption_Parse(absl::string_view name, NormalizeOption* value) {
  return ::google::protobuf::internal::ParseNamedEnum<NormalizeOption>(
      NormalizeOption_descriptor(), name, value);
}

// ===================================================================


// -------------------------------------------------------------------

class NormalizeSetting final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:kumo.nlp.NormalizeSetting) */ {
 public:
  inline NormalizeSetting() : NormalizeSetting(nullptr) {}
  ~NormalizeSetting() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(NormalizeSetting* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(NormalizeSetting));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR NormalizeSetting(
      ::google::protobuf::internal::ConstantInitialized);

  inline NormalizeSetting(const NormalizeSetting& from) : NormalizeSetting(nullptr, from) {}
  inline NormalizeSetting(NormalizeSetting&& from) noexcept
      : NormalizeSetting(nullptr, std::move(from)) {}
  inline NormalizeSetting& operator=(const NormalizeSetting& from) {
    CopyFrom(from);
    return *this;
  }
  inline NormalizeSetting& operator=(NormalizeSetting&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const NormalizeSetting& default_instance() {
    return *internal_default_instance();
  }
  static inline const NormalizeSetting* internal_default_instance() {
    return reinterpret_cast<const NormalizeSetting*>(
        &_NormalizeSetting_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(NormalizeSetting& a, NormalizeSetting& b) { a.Swap(&b); }
  inline void Swap(NormalizeSetting* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(NormalizeSetting* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  NormalizeSetting* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<NormalizeSetting>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const NormalizeSetting& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const NormalizeSetting& from) { NormalizeSetting::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(NormalizeSetting* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "kumo.nlp.NormalizeSetting"; }

 protected:
  explicit NormalizeSetting(::google::protobuf::Arena* arena);
  NormalizeSetting(::google::protobuf::Arena* arena, const NormalizeSetting& from);
  NormalizeSetting(::google::protobuf::Arena* arena, NormalizeSetting&& from) noexcept
      : NormalizeSetting(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kFullToHalfFieldNumber = 1,
    kUpperToLowerFieldNumber = 2,
    kBlankToOneFieldNumber = 3,
    kLangDetectFieldNumber = 4,
    kRemoveBadCharFieldNumber = 5,
    kRemoveEmojiFieldNumber = 6,
    kPunctuationToSpaceFieldNumber = 7,
    kRemovePunctuationFieldNumber = 8,
    kZhToPinFieldNumber = 9,
    kZhToPinShortFieldNumber = 10,
  };
  // bool full_to_half = 1;
  void clear_full_to_half() ;
  bool full_to_half() const;
  void set_full_to_half(bool value);

  private:
  bool _internal_full_to_half() const;
  void _internal_set_full_to_half(bool value);

  public:
  // bool upper_to_lower = 2;
  void clear_upper_to_lower() ;
  bool upper_to_lower() const;
  void set_upper_to_lower(bool value);

  private:
  bool _internal_upper_to_lower() const;
  void _internal_set_upper_to_lower(bool value);

  public:
  // bool blank_to_one = 3;
  void clear_blank_to_one() ;
  bool blank_to_one() const;
  void set_blank_to_one(bool value);

  private:
  bool _internal_blank_to_one() const;
  void _internal_set_blank_to_one(bool value);

  public:
  // bool lang_detect = 4;
  void clear_lang_detect() ;
  bool lang_detect() const;
  void set_lang_detect(bool value);

  private:
  bool _internal_lang_detect() const;
  void _internal_set_lang_detect(bool value);

  public:
  // bool remove_bad_char = 5;
  void clear_remove_bad_char() ;
  bool remove_bad_char() const;
  void set_remove_bad_char(bool value);

  private:
  bool _internal_remove_bad_char() const;
  void _internal_set_remove_bad_char(bool value);

  public:
  // bool remove_emoji = 6;
  void clear_remove_emoji() ;
  bool remove_emoji() const;
  void set_remove_emoji(bool value);

  private:
  bool _internal_remove_emoji() const;
  void _internal_set_remove_emoji(bool value);

  public:
  // bool punctuation_to_space = 7;
  void clear_punctuation_to_space() ;
  bool punctuation_to_space() const;
  void set_punctuation_to_space(bool value);

  private:
  bool _internal_punctuation_to_space() const;
  void _internal_set_punctuation_to_space(bool value);

  public:
  // bool remove_punctuation = 8;
  void clear_remove_punctuation() ;
  bool remove_punctuation() const;
  void set_remove_punctuation(bool value);

  private:
  bool _internal_remove_punctuation() const;
  void _internal_set_remove_punctuation(bool value);

  public:
  // bool zh_to_pin = 9;
  void clear_zh_to_pin() ;
  bool zh_to_pin() const;
  void set_zh_to_pin(bool value);

  private:
  bool _internal_zh_to_pin() const;
  void _internal_set_zh_to_pin(bool value);

  public:
  // bool zh_to_pin_short = 10;
  void clear_zh_to_pin_short() ;
  bool zh_to_pin_short() const;
  void set_zh_to_pin_short(bool value);

  private:
  bool _internal_zh_to_pin_short() const;
  void _internal_set_zh_to_pin_short(bool value);

  public:
  // @@protoc_insertion_point(class_scope:kumo.nlp.NormalizeSetting)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      4, 10, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const NormalizeSetting& from_msg);
    bool full_to_half_;
    bool upper_to_lower_;
    bool blank_to_one_;
    bool lang_detect_;
    bool remove_bad_char_;
    bool remove_emoji_;
    bool punctuation_to_space_;
    bool remove_punctuation_;
    bool zh_to_pin_;
    bool zh_to_pin_short_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_gnef_2fproto_2fnormalize_2eproto;
};
// -------------------------------------------------------------------

class NormalizeResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:kumo.nlp.NormalizeResponse) */ {
 public:
  inline NormalizeResponse() : NormalizeResponse(nullptr) {}
  ~NormalizeResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(NormalizeResponse* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(NormalizeResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR NormalizeResponse(
      ::google::protobuf::internal::ConstantInitialized);

  inline NormalizeResponse(const NormalizeResponse& from) : NormalizeResponse(nullptr, from) {}
  inline NormalizeResponse(NormalizeResponse&& from) noexcept
      : NormalizeResponse(nullptr, std::move(from)) {}
  inline NormalizeResponse& operator=(const NormalizeResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline NormalizeResponse& operator=(NormalizeResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const NormalizeResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const NormalizeResponse* internal_default_instance() {
    return reinterpret_cast<const NormalizeResponse*>(
        &_NormalizeResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(NormalizeResponse& a, NormalizeResponse& b) { a.Swap(&b); }
  inline void Swap(NormalizeResponse* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(NormalizeResponse* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  NormalizeResponse* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<NormalizeResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const NormalizeResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const NormalizeResponse& from) { NormalizeResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(NormalizeResponse* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "kumo.nlp.NormalizeResponse"; }

 protected:
  explicit NormalizeResponse(::google::protobuf::Arena* arena);
  NormalizeResponse(::google::protobuf::Arena* arena, const NormalizeResponse& from);
  NormalizeResponse(::google::protobuf::Arena* arena, NormalizeResponse&& from) noexcept
      : NormalizeResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kQueryFieldNumber = 1,
    kPinyinFieldNumber = 2,
    kPinyinShortFieldNumber = 3,
  };
  // string query = 1;
  void clear_query() ;
  const std::string& query() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_query(Arg_&& arg, Args_... args);
  std::string* mutable_query();
  PROTOBUF_NODISCARD std::string* release_query();
  void set_allocated_query(std::string* value);

  private:
  const std::string& _internal_query() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_query(
      const std::string& value);
  std::string* _internal_mutable_query();

  public:
  // string pinyin = 2;
  void clear_pinyin() ;
  const std::string& pinyin() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_pinyin(Arg_&& arg, Args_... args);
  std::string* mutable_pinyin();
  PROTOBUF_NODISCARD std::string* release_pinyin();
  void set_allocated_pinyin(std::string* value);

  private:
  const std::string& _internal_pinyin() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_pinyin(
      const std::string& value);
  std::string* _internal_mutable_pinyin();

  public:
  // string pinyin_short = 3;
  void clear_pinyin_short() ;
  const std::string& pinyin_short() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_pinyin_short(Arg_&& arg, Args_... args);
  std::string* mutable_pinyin_short();
  PROTOBUF_NODISCARD std::string* release_pinyin_short();
  void set_allocated_pinyin_short(std::string* value);

  private:
  const std::string& _internal_pinyin_short() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_pinyin_short(
      const std::string& value);
  std::string* _internal_mutable_pinyin_short();

  public:
  // @@protoc_insertion_point(class_scope:kumo.nlp.NormalizeResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      58, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const NormalizeResponse& from_msg);
    ::google::protobuf::internal::ArenaStringPtr query_;
    ::google::protobuf::internal::ArenaStringPtr pinyin_;
    ::google::protobuf::internal::ArenaStringPtr pinyin_short_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_gnef_2fproto_2fnormalize_2eproto;
};
// -------------------------------------------------------------------

class NormalizeRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:kumo.nlp.NormalizeRequest) */ {
 public:
  inline NormalizeRequest() : NormalizeRequest(nullptr) {}
  ~NormalizeRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(NormalizeRequest* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(NormalizeRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR NormalizeRequest(
      ::google::protobuf::internal::ConstantInitialized);

  inline NormalizeRequest(const NormalizeRequest& from) : NormalizeRequest(nullptr, from) {}
  inline NormalizeRequest(NormalizeRequest&& from) noexcept
      : NormalizeRequest(nullptr, std::move(from)) {}
  inline NormalizeRequest& operator=(const NormalizeRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline NormalizeRequest& operator=(NormalizeRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const NormalizeRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const NormalizeRequest* internal_default_instance() {
    return reinterpret_cast<const NormalizeRequest*>(
        &_NormalizeRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(NormalizeRequest& a, NormalizeRequest& b) { a.Swap(&b); }
  inline void Swap(NormalizeRequest* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(NormalizeRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  NormalizeRequest* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<NormalizeRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const NormalizeRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const NormalizeRequest& from) { NormalizeRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(NormalizeRequest* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "kumo.nlp.NormalizeRequest"; }

 protected:
  explicit NormalizeRequest(::google::protobuf::Arena* arena);
  NormalizeRequest(::google::protobuf::Arena* arena, const NormalizeRequest& from);
  NormalizeRequest(::google::protobuf::Arena* arena, NormalizeRequest&& from) noexcept
      : NormalizeRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kQueryFieldNumber = 1,
    kSettingFieldNumber = 2,
  };
  // string query = 1;
  void clear_query() ;
  const std::string& query() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_query(Arg_&& arg, Args_... args);
  std::string* mutable_query();
  PROTOBUF_NODISCARD std::string* release_query();
  void set_allocated_query(std::string* value);

  private:
  const std::string& _internal_query() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_query(
      const std::string& value);
  std::string* _internal_mutable_query();

  public:
  // .kumo.nlp.NormalizeSetting setting = 2;
  bool has_setting() const;
  void clear_setting() ;
  const ::kumo::nlp::NormalizeSetting& setting() const;
  PROTOBUF_NODISCARD ::kumo::nlp::NormalizeSetting* release_setting();
  ::kumo::nlp::NormalizeSetting* mutable_setting();
  void set_allocated_setting(::kumo::nlp::NormalizeSetting* value);
  void unsafe_arena_set_allocated_setting(::kumo::nlp::NormalizeSetting* value);
  ::kumo::nlp::NormalizeSetting* unsafe_arena_release_setting();

  private:
  const ::kumo::nlp::NormalizeSetting& _internal_setting() const;
  ::kumo::nlp::NormalizeSetting* _internal_mutable_setting();

  public:
  // @@protoc_insertion_point(class_scope:kumo.nlp.NormalizeRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 1,
      39, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const NormalizeRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr query_;
    ::kumo::nlp::NormalizeSetting* setting_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_gnef_2fproto_2fnormalize_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// NormalizeSetting

// bool full_to_half = 1;
inline void NormalizeSetting::clear_full_to_half() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.full_to_half_ = false;
}
inline bool NormalizeSetting::full_to_half() const {
  // @@protoc_insertion_point(field_get:kumo.nlp.NormalizeSetting.full_to_half)
  return _internal_full_to_half();
}
inline void NormalizeSetting::set_full_to_half(bool value) {
  _internal_set_full_to_half(value);
  // @@protoc_insertion_point(field_set:kumo.nlp.NormalizeSetting.full_to_half)
}
inline bool NormalizeSetting::_internal_full_to_half() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.full_to_half_;
}
inline void NormalizeSetting::_internal_set_full_to_half(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.full_to_half_ = value;
}

// bool upper_to_lower = 2;
inline void NormalizeSetting::clear_upper_to_lower() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.upper_to_lower_ = false;
}
inline bool NormalizeSetting::upper_to_lower() const {
  // @@protoc_insertion_point(field_get:kumo.nlp.NormalizeSetting.upper_to_lower)
  return _internal_upper_to_lower();
}
inline void NormalizeSetting::set_upper_to_lower(bool value) {
  _internal_set_upper_to_lower(value);
  // @@protoc_insertion_point(field_set:kumo.nlp.NormalizeSetting.upper_to_lower)
}
inline bool NormalizeSetting::_internal_upper_to_lower() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.upper_to_lower_;
}
inline void NormalizeSetting::_internal_set_upper_to_lower(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.upper_to_lower_ = value;
}

// bool blank_to_one = 3;
inline void NormalizeSetting::clear_blank_to_one() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.blank_to_one_ = false;
}
inline bool NormalizeSetting::blank_to_one() const {
  // @@protoc_insertion_point(field_get:kumo.nlp.NormalizeSetting.blank_to_one)
  return _internal_blank_to_one();
}
inline void NormalizeSetting::set_blank_to_one(bool value) {
  _internal_set_blank_to_one(value);
  // @@protoc_insertion_point(field_set:kumo.nlp.NormalizeSetting.blank_to_one)
}
inline bool NormalizeSetting::_internal_blank_to_one() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.blank_to_one_;
}
inline void NormalizeSetting::_internal_set_blank_to_one(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.blank_to_one_ = value;
}

// bool lang_detect = 4;
inline void NormalizeSetting::clear_lang_detect() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.lang_detect_ = false;
}
inline bool NormalizeSetting::lang_detect() const {
  // @@protoc_insertion_point(field_get:kumo.nlp.NormalizeSetting.lang_detect)
  return _internal_lang_detect();
}
inline void NormalizeSetting::set_lang_detect(bool value) {
  _internal_set_lang_detect(value);
  // @@protoc_insertion_point(field_set:kumo.nlp.NormalizeSetting.lang_detect)
}
inline bool NormalizeSetting::_internal_lang_detect() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.lang_detect_;
}
inline void NormalizeSetting::_internal_set_lang_detect(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.lang_detect_ = value;
}

// bool remove_bad_char = 5;
inline void NormalizeSetting::clear_remove_bad_char() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.remove_bad_char_ = false;
}
inline bool NormalizeSetting::remove_bad_char() const {
  // @@protoc_insertion_point(field_get:kumo.nlp.NormalizeSetting.remove_bad_char)
  return _internal_remove_bad_char();
}
inline void NormalizeSetting::set_remove_bad_char(bool value) {
  _internal_set_remove_bad_char(value);
  // @@protoc_insertion_point(field_set:kumo.nlp.NormalizeSetting.remove_bad_char)
}
inline bool NormalizeSetting::_internal_remove_bad_char() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.remove_bad_char_;
}
inline void NormalizeSetting::_internal_set_remove_bad_char(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.remove_bad_char_ = value;
}

// bool remove_emoji = 6;
inline void NormalizeSetting::clear_remove_emoji() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.remove_emoji_ = false;
}
inline bool NormalizeSetting::remove_emoji() const {
  // @@protoc_insertion_point(field_get:kumo.nlp.NormalizeSetting.remove_emoji)
  return _internal_remove_emoji();
}
inline void NormalizeSetting::set_remove_emoji(bool value) {
  _internal_set_remove_emoji(value);
  // @@protoc_insertion_point(field_set:kumo.nlp.NormalizeSetting.remove_emoji)
}
inline bool NormalizeSetting::_internal_remove_emoji() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.remove_emoji_;
}
inline void NormalizeSetting::_internal_set_remove_emoji(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.remove_emoji_ = value;
}

// bool punctuation_to_space = 7;
inline void NormalizeSetting::clear_punctuation_to_space() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.punctuation_to_space_ = false;
}
inline bool NormalizeSetting::punctuation_to_space() const {
  // @@protoc_insertion_point(field_get:kumo.nlp.NormalizeSetting.punctuation_to_space)
  return _internal_punctuation_to_space();
}
inline void NormalizeSetting::set_punctuation_to_space(bool value) {
  _internal_set_punctuation_to_space(value);
  // @@protoc_insertion_point(field_set:kumo.nlp.NormalizeSetting.punctuation_to_space)
}
inline bool NormalizeSetting::_internal_punctuation_to_space() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.punctuation_to_space_;
}
inline void NormalizeSetting::_internal_set_punctuation_to_space(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.punctuation_to_space_ = value;
}

// bool remove_punctuation = 8;
inline void NormalizeSetting::clear_remove_punctuation() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.remove_punctuation_ = false;
}
inline bool NormalizeSetting::remove_punctuation() const {
  // @@protoc_insertion_point(field_get:kumo.nlp.NormalizeSetting.remove_punctuation)
  return _internal_remove_punctuation();
}
inline void NormalizeSetting::set_remove_punctuation(bool value) {
  _internal_set_remove_punctuation(value);
  // @@protoc_insertion_point(field_set:kumo.nlp.NormalizeSetting.remove_punctuation)
}
inline bool NormalizeSetting::_internal_remove_punctuation() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.remove_punctuation_;
}
inline void NormalizeSetting::_internal_set_remove_punctuation(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.remove_punctuation_ = value;
}

// bool zh_to_pin = 9;
inline void NormalizeSetting::clear_zh_to_pin() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.zh_to_pin_ = false;
}
inline bool NormalizeSetting::zh_to_pin() const {
  // @@protoc_insertion_point(field_get:kumo.nlp.NormalizeSetting.zh_to_pin)
  return _internal_zh_to_pin();
}
inline void NormalizeSetting::set_zh_to_pin(bool value) {
  _internal_set_zh_to_pin(value);
  // @@protoc_insertion_point(field_set:kumo.nlp.NormalizeSetting.zh_to_pin)
}
inline bool NormalizeSetting::_internal_zh_to_pin() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.zh_to_pin_;
}
inline void NormalizeSetting::_internal_set_zh_to_pin(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.zh_to_pin_ = value;
}

// bool zh_to_pin_short = 10;
inline void NormalizeSetting::clear_zh_to_pin_short() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.zh_to_pin_short_ = false;
}
inline bool NormalizeSetting::zh_to_pin_short() const {
  // @@protoc_insertion_point(field_get:kumo.nlp.NormalizeSetting.zh_to_pin_short)
  return _internal_zh_to_pin_short();
}
inline void NormalizeSetting::set_zh_to_pin_short(bool value) {
  _internal_set_zh_to_pin_short(value);
  // @@protoc_insertion_point(field_set:kumo.nlp.NormalizeSetting.zh_to_pin_short)
}
inline bool NormalizeSetting::_internal_zh_to_pin_short() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.zh_to_pin_short_;
}
inline void NormalizeSetting::_internal_set_zh_to_pin_short(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.zh_to_pin_short_ = value;
}

// -------------------------------------------------------------------

// NormalizeRequest

// string query = 1;
inline void NormalizeRequest::clear_query() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.query_.ClearToEmpty();
}
inline const std::string& NormalizeRequest::query() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:kumo.nlp.NormalizeRequest.query)
  return _internal_query();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void NormalizeRequest::set_query(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.query_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:kumo.nlp.NormalizeRequest.query)
}
inline std::string* NormalizeRequest::mutable_query() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_query();
  // @@protoc_insertion_point(field_mutable:kumo.nlp.NormalizeRequest.query)
  return _s;
}
inline const std::string& NormalizeRequest::_internal_query() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.query_.Get();
}
inline void NormalizeRequest::_internal_set_query(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.query_.Set(value, GetArena());
}
inline std::string* NormalizeRequest::_internal_mutable_query() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.query_.Mutable( GetArena());
}
inline std::string* NormalizeRequest::release_query() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:kumo.nlp.NormalizeRequest.query)
  return _impl_.query_.Release();
}
inline void NormalizeRequest::set_allocated_query(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.query_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.query_.IsDefault()) {
    _impl_.query_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:kumo.nlp.NormalizeRequest.query)
}

// .kumo.nlp.NormalizeSetting setting = 2;
inline bool NormalizeRequest::has_setting() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.setting_ != nullptr);
  return value;
}
inline void NormalizeRequest::clear_setting() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.setting_ != nullptr) _impl_.setting_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::kumo::nlp::NormalizeSetting& NormalizeRequest::_internal_setting() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::kumo::nlp::NormalizeSetting* p = _impl_.setting_;
  return p != nullptr ? *p : reinterpret_cast<const ::kumo::nlp::NormalizeSetting&>(::kumo::nlp::_NormalizeSetting_default_instance_);
}
inline const ::kumo::nlp::NormalizeSetting& NormalizeRequest::setting() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:kumo.nlp.NormalizeRequest.setting)
  return _internal_setting();
}
inline void NormalizeRequest::unsafe_arena_set_allocated_setting(::kumo::nlp::NormalizeSetting* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.setting_);
  }
  _impl_.setting_ = reinterpret_cast<::kumo::nlp::NormalizeSetting*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:kumo.nlp.NormalizeRequest.setting)
}
inline ::kumo::nlp::NormalizeSetting* NormalizeRequest::release_setting() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::kumo::nlp::NormalizeSetting* released = _impl_.setting_;
  _impl_.setting_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::kumo::nlp::NormalizeSetting* NormalizeRequest::unsafe_arena_release_setting() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:kumo.nlp.NormalizeRequest.setting)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::kumo::nlp::NormalizeSetting* temp = _impl_.setting_;
  _impl_.setting_ = nullptr;
  return temp;
}
inline ::kumo::nlp::NormalizeSetting* NormalizeRequest::_internal_mutable_setting() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.setting_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::kumo::nlp::NormalizeSetting>(GetArena());
    _impl_.setting_ = reinterpret_cast<::kumo::nlp::NormalizeSetting*>(p);
  }
  return _impl_.setting_;
}
inline ::kumo::nlp::NormalizeSetting* NormalizeRequest::mutable_setting() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::kumo::nlp::NormalizeSetting* _msg = _internal_mutable_setting();
  // @@protoc_insertion_point(field_mutable:kumo.nlp.NormalizeRequest.setting)
  return _msg;
}
inline void NormalizeRequest::set_allocated_setting(::kumo::nlp::NormalizeSetting* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete (_impl_.setting_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = (value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.setting_ = reinterpret_cast<::kumo::nlp::NormalizeSetting*>(value);
  // @@protoc_insertion_point(field_set_allocated:kumo.nlp.NormalizeRequest.setting)
}

// -------------------------------------------------------------------

// NormalizeResponse

// string query = 1;
inline void NormalizeResponse::clear_query() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.query_.ClearToEmpty();
}
inline const std::string& NormalizeResponse::query() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:kumo.nlp.NormalizeResponse.query)
  return _internal_query();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void NormalizeResponse::set_query(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.query_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:kumo.nlp.NormalizeResponse.query)
}
inline std::string* NormalizeResponse::mutable_query() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_query();
  // @@protoc_insertion_point(field_mutable:kumo.nlp.NormalizeResponse.query)
  return _s;
}
inline const std::string& NormalizeResponse::_internal_query() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.query_.Get();
}
inline void NormalizeResponse::_internal_set_query(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.query_.Set(value, GetArena());
}
inline std::string* NormalizeResponse::_internal_mutable_query() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.query_.Mutable( GetArena());
}
inline std::string* NormalizeResponse::release_query() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:kumo.nlp.NormalizeResponse.query)
  return _impl_.query_.Release();
}
inline void NormalizeResponse::set_allocated_query(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.query_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.query_.IsDefault()) {
    _impl_.query_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:kumo.nlp.NormalizeResponse.query)
}

// string pinyin = 2;
inline void NormalizeResponse::clear_pinyin() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pinyin_.ClearToEmpty();
}
inline const std::string& NormalizeResponse::pinyin() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:kumo.nlp.NormalizeResponse.pinyin)
  return _internal_pinyin();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void NormalizeResponse::set_pinyin(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pinyin_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:kumo.nlp.NormalizeResponse.pinyin)
}
inline std::string* NormalizeResponse::mutable_pinyin() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_pinyin();
  // @@protoc_insertion_point(field_mutable:kumo.nlp.NormalizeResponse.pinyin)
  return _s;
}
inline const std::string& NormalizeResponse::_internal_pinyin() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pinyin_.Get();
}
inline void NormalizeResponse::_internal_set_pinyin(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pinyin_.Set(value, GetArena());
}
inline std::string* NormalizeResponse::_internal_mutable_pinyin() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.pinyin_.Mutable( GetArena());
}
inline std::string* NormalizeResponse::release_pinyin() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:kumo.nlp.NormalizeResponse.pinyin)
  return _impl_.pinyin_.Release();
}
inline void NormalizeResponse::set_allocated_pinyin(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pinyin_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.pinyin_.IsDefault()) {
    _impl_.pinyin_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:kumo.nlp.NormalizeResponse.pinyin)
}

// string pinyin_short = 3;
inline void NormalizeResponse::clear_pinyin_short() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pinyin_short_.ClearToEmpty();
}
inline const std::string& NormalizeResponse::pinyin_short() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:kumo.nlp.NormalizeResponse.pinyin_short)
  return _internal_pinyin_short();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void NormalizeResponse::set_pinyin_short(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pinyin_short_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:kumo.nlp.NormalizeResponse.pinyin_short)
}
inline std::string* NormalizeResponse::mutable_pinyin_short() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_pinyin_short();
  // @@protoc_insertion_point(field_mutable:kumo.nlp.NormalizeResponse.pinyin_short)
  return _s;
}
inline const std::string& NormalizeResponse::_internal_pinyin_short() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pinyin_short_.Get();
}
inline void NormalizeResponse::_internal_set_pinyin_short(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pinyin_short_.Set(value, GetArena());
}
inline std::string* NormalizeResponse::_internal_mutable_pinyin_short() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.pinyin_short_.Mutable( GetArena());
}
inline std::string* NormalizeResponse::release_pinyin_short() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:kumo.nlp.NormalizeResponse.pinyin_short)
  return _impl_.pinyin_short_.Release();
}
inline void NormalizeResponse::set_allocated_pinyin_short(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pinyin_short_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.pinyin_short_.IsDefault()) {
    _impl_.pinyin_short_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:kumo.nlp.NormalizeResponse.pinyin_short)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace nlp
}  // namespace kumo


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::kumo::nlp::NormalizeOption> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::kumo::nlp::NormalizeOption>() {
  return ::kumo::nlp::NormalizeOption_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // gnef_2fproto_2fnormalize_2eproto_2epb_2eh
