// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: gnef/proto/rewrite.proto
// Protobuf C++ Version: 5.29.5

#ifndef gnef_2fproto_2frewrite_2eproto_2epb_2eh
#define gnef_2fproto_2frewrite_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029005
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "gnef/proto/segment.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_gnef_2fproto_2frewrite_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_gnef_2fproto_2frewrite_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_gnef_2fproto_2frewrite_2eproto;
namespace kumo {
namespace nlp {
class RewriteQueryInfo;
struct RewriteQueryInfoDefaultTypeInternal;
extern RewriteQueryInfoDefaultTypeInternal _RewriteQueryInfo_default_instance_;
class RewriteSetting;
struct RewriteSettingDefaultTypeInternal;
extern RewriteSettingDefaultTypeInternal _RewriteSetting_default_instance_;
}  // namespace nlp
}  // namespace kumo
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace kumo {
namespace nlp {

// ===================================================================


// -------------------------------------------------------------------

class RewriteSetting final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:kumo.nlp.RewriteSetting) */ {
 public:
  inline RewriteSetting() : RewriteSetting(nullptr) {}
  ~RewriteSetting() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(RewriteSetting* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(RewriteSetting));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR RewriteSetting(
      ::google::protobuf::internal::ConstantInitialized);

  inline RewriteSetting(const RewriteSetting& from) : RewriteSetting(nullptr, from) {}
  inline RewriteSetting(RewriteSetting&& from) noexcept
      : RewriteSetting(nullptr, std::move(from)) {}
  inline RewriteSetting& operator=(const RewriteSetting& from) {
    CopyFrom(from);
    return *this;
  }
  inline RewriteSetting& operator=(RewriteSetting&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RewriteSetting& default_instance() {
    return *internal_default_instance();
  }
  static inline const RewriteSetting* internal_default_instance() {
    return reinterpret_cast<const RewriteSetting*>(
        &_RewriteSetting_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(RewriteSetting& a, RewriteSetting& b) { a.Swap(&b); }
  inline void Swap(RewriteSetting* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RewriteSetting* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RewriteSetting* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<RewriteSetting>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const RewriteSetting& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const RewriteSetting& from) { RewriteSetting::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(RewriteSetting* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "kumo.nlp.RewriteSetting"; }

 protected:
  explicit RewriteSetting(::google::protobuf::Arena* arena);
  RewriteSetting(::google::protobuf::Arena* arena, const RewriteSetting& from);
  RewriteSetting(::google::protobuf::Arena* arena, RewriteSetting&& from) noexcept
      : RewriteSetting(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kEnableSynonymFieldNumber = 1,
    kEnableCorrectFieldNumber = 2,
  };
  // bool enable_synonym = 1;
  void clear_enable_synonym() ;
  bool enable_synonym() const;
  void set_enable_synonym(bool value);

  private:
  bool _internal_enable_synonym() const;
  void _internal_set_enable_synonym(bool value);

  public:
  // bool enable_correct = 2;
  void clear_enable_correct() ;
  bool enable_correct() const;
  void set_enable_correct(bool value);

  private:
  bool _internal_enable_correct() const;
  void _internal_set_enable_correct(bool value);

  public:
  // @@protoc_insertion_point(class_scope:kumo.nlp.RewriteSetting)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const RewriteSetting& from_msg);
    bool enable_synonym_;
    bool enable_correct_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_gnef_2fproto_2frewrite_2eproto;
};
// -------------------------------------------------------------------

class RewriteQueryInfo final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:kumo.nlp.RewriteQueryInfo) */ {
 public:
  inline RewriteQueryInfo() : RewriteQueryInfo(nullptr) {}
  ~RewriteQueryInfo() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(RewriteQueryInfo* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(RewriteQueryInfo));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR RewriteQueryInfo(
      ::google::protobuf::internal::ConstantInitialized);

  inline RewriteQueryInfo(const RewriteQueryInfo& from) : RewriteQueryInfo(nullptr, from) {}
  inline RewriteQueryInfo(RewriteQueryInfo&& from) noexcept
      : RewriteQueryInfo(nullptr, std::move(from)) {}
  inline RewriteQueryInfo& operator=(const RewriteQueryInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline RewriteQueryInfo& operator=(RewriteQueryInfo&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RewriteQueryInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const RewriteQueryInfo* internal_default_instance() {
    return reinterpret_cast<const RewriteQueryInfo*>(
        &_RewriteQueryInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(RewriteQueryInfo& a, RewriteQueryInfo& b) { a.Swap(&b); }
  inline void Swap(RewriteQueryInfo* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RewriteQueryInfo* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RewriteQueryInfo* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<RewriteQueryInfo>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const RewriteQueryInfo& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const RewriteQueryInfo& from) { RewriteQueryInfo::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(RewriteQueryInfo* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "kumo.nlp.RewriteQueryInfo"; }

 protected:
  explicit RewriteQueryInfo(::google::protobuf::Arena* arena);
  RewriteQueryInfo(::google::protobuf::Arena* arena, const RewriteQueryInfo& from);
  RewriteQueryInfo(::google::protobuf::Arena* arena, RewriteQueryInfo&& from) noexcept
      : RewriteQueryInfo(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kExtraJsonFieldNumber = 6,
    kDebugInfoFieldNumber = 7,
    kOriginFieldNumber = 3,
    kRewriteTermFieldNumber = 4,
    kBeliefFieldNumber = 1,
    kLevelFieldNumber = 2,
    kIsRecallFieldNumber = 5,
  };
  // string extra_json = 6;
  void clear_extra_json() ;
  const std::string& extra_json() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_extra_json(Arg_&& arg, Args_... args);
  std::string* mutable_extra_json();
  PROTOBUF_NODISCARD std::string* release_extra_json();
  void set_allocated_extra_json(std::string* value);

  private:
  const std::string& _internal_extra_json() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_extra_json(
      const std::string& value);
  std::string* _internal_mutable_extra_json();

  public:
  // string debug_info = 7;
  void clear_debug_info() ;
  const std::string& debug_info() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_debug_info(Arg_&& arg, Args_... args);
  std::string* mutable_debug_info();
  PROTOBUF_NODISCARD std::string* release_debug_info();
  void set_allocated_debug_info(std::string* value);

  private:
  const std::string& _internal_debug_info() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_debug_info(
      const std::string& value);
  std::string* _internal_mutable_debug_info();

  public:
  // .kumo.nlp.TermInfo origin = 3;
  bool has_origin() const;
  void clear_origin() ;
  const ::kumo::nlp::TermInfo& origin() const;
  PROTOBUF_NODISCARD ::kumo::nlp::TermInfo* release_origin();
  ::kumo::nlp::TermInfo* mutable_origin();
  void set_allocated_origin(::kumo::nlp::TermInfo* value);
  void unsafe_arena_set_allocated_origin(::kumo::nlp::TermInfo* value);
  ::kumo::nlp::TermInfo* unsafe_arena_release_origin();

  private:
  const ::kumo::nlp::TermInfo& _internal_origin() const;
  ::kumo::nlp::TermInfo* _internal_mutable_origin();

  public:
  // .kumo.nlp.TermInfo rewrite_term = 4;
  bool has_rewrite_term() const;
  void clear_rewrite_term() ;
  const ::kumo::nlp::TermInfo& rewrite_term() const;
  PROTOBUF_NODISCARD ::kumo::nlp::TermInfo* release_rewrite_term();
  ::kumo::nlp::TermInfo* mutable_rewrite_term();
  void set_allocated_rewrite_term(::kumo::nlp::TermInfo* value);
  void unsafe_arena_set_allocated_rewrite_term(::kumo::nlp::TermInfo* value);
  ::kumo::nlp::TermInfo* unsafe_arena_release_rewrite_term();

  private:
  const ::kumo::nlp::TermInfo& _internal_rewrite_term() const;
  ::kumo::nlp::TermInfo* _internal_mutable_rewrite_term();

  public:
  // double belief = 1;
  void clear_belief() ;
  double belief() const;
  void set_belief(double value);

  private:
  double _internal_belief() const;
  void _internal_set_belief(double value);

  public:
  // int32 level = 2;
  void clear_level() ;
  ::int32_t level() const;
  void set_level(::int32_t value);

  private:
  ::int32_t _internal_level() const;
  void _internal_set_level(::int32_t value);

  public:
  // bool is_recall = 5;
  void clear_is_recall() ;
  bool is_recall() const;
  void set_is_recall(bool value);

  private:
  bool _internal_is_recall() const;
  void _internal_set_is_recall(bool value);

  public:
  // @@protoc_insertion_point(class_scope:kumo.nlp.RewriteQueryInfo)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 7, 2,
      54, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const RewriteQueryInfo& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr extra_json_;
    ::google::protobuf::internal::ArenaStringPtr debug_info_;
    ::kumo::nlp::TermInfo* origin_;
    ::kumo::nlp::TermInfo* rewrite_term_;
    double belief_;
    ::int32_t level_;
    bool is_recall_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_gnef_2fproto_2frewrite_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// RewriteSetting

// bool enable_synonym = 1;
inline void RewriteSetting::clear_enable_synonym() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.enable_synonym_ = false;
}
inline bool RewriteSetting::enable_synonym() const {
  // @@protoc_insertion_point(field_get:kumo.nlp.RewriteSetting.enable_synonym)
  return _internal_enable_synonym();
}
inline void RewriteSetting::set_enable_synonym(bool value) {
  _internal_set_enable_synonym(value);
  // @@protoc_insertion_point(field_set:kumo.nlp.RewriteSetting.enable_synonym)
}
inline bool RewriteSetting::_internal_enable_synonym() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.enable_synonym_;
}
inline void RewriteSetting::_internal_set_enable_synonym(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.enable_synonym_ = value;
}

// bool enable_correct = 2;
inline void RewriteSetting::clear_enable_correct() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.enable_correct_ = false;
}
inline bool RewriteSetting::enable_correct() const {
  // @@protoc_insertion_point(field_get:kumo.nlp.RewriteSetting.enable_correct)
  return _internal_enable_correct();
}
inline void RewriteSetting::set_enable_correct(bool value) {
  _internal_set_enable_correct(value);
  // @@protoc_insertion_point(field_set:kumo.nlp.RewriteSetting.enable_correct)
}
inline bool RewriteSetting::_internal_enable_correct() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.enable_correct_;
}
inline void RewriteSetting::_internal_set_enable_correct(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.enable_correct_ = value;
}

// -------------------------------------------------------------------

// RewriteQueryInfo

// double belief = 1;
inline void RewriteQueryInfo::clear_belief() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.belief_ = 0;
}
inline double RewriteQueryInfo::belief() const {
  // @@protoc_insertion_point(field_get:kumo.nlp.RewriteQueryInfo.belief)
  return _internal_belief();
}
inline void RewriteQueryInfo::set_belief(double value) {
  _internal_set_belief(value);
  // @@protoc_insertion_point(field_set:kumo.nlp.RewriteQueryInfo.belief)
}
inline double RewriteQueryInfo::_internal_belief() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.belief_;
}
inline void RewriteQueryInfo::_internal_set_belief(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.belief_ = value;
}

// int32 level = 2;
inline void RewriteQueryInfo::clear_level() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.level_ = 0;
}
inline ::int32_t RewriteQueryInfo::level() const {
  // @@protoc_insertion_point(field_get:kumo.nlp.RewriteQueryInfo.level)
  return _internal_level();
}
inline void RewriteQueryInfo::set_level(::int32_t value) {
  _internal_set_level(value);
  // @@protoc_insertion_point(field_set:kumo.nlp.RewriteQueryInfo.level)
}
inline ::int32_t RewriteQueryInfo::_internal_level() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.level_;
}
inline void RewriteQueryInfo::_internal_set_level(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.level_ = value;
}

// .kumo.nlp.TermInfo origin = 3;
inline bool RewriteQueryInfo::has_origin() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.origin_ != nullptr);
  return value;
}
inline const ::kumo::nlp::TermInfo& RewriteQueryInfo::_internal_origin() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::kumo::nlp::TermInfo* p = _impl_.origin_;
  return p != nullptr ? *p : reinterpret_cast<const ::kumo::nlp::TermInfo&>(::kumo::nlp::_TermInfo_default_instance_);
}
inline const ::kumo::nlp::TermInfo& RewriteQueryInfo::origin() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:kumo.nlp.RewriteQueryInfo.origin)
  return _internal_origin();
}
inline void RewriteQueryInfo::unsafe_arena_set_allocated_origin(::kumo::nlp::TermInfo* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.origin_);
  }
  _impl_.origin_ = reinterpret_cast<::kumo::nlp::TermInfo*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:kumo.nlp.RewriteQueryInfo.origin)
}
inline ::kumo::nlp::TermInfo* RewriteQueryInfo::release_origin() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::kumo::nlp::TermInfo* released = _impl_.origin_;
  _impl_.origin_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::kumo::nlp::TermInfo* RewriteQueryInfo::unsafe_arena_release_origin() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:kumo.nlp.RewriteQueryInfo.origin)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::kumo::nlp::TermInfo* temp = _impl_.origin_;
  _impl_.origin_ = nullptr;
  return temp;
}
inline ::kumo::nlp::TermInfo* RewriteQueryInfo::_internal_mutable_origin() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.origin_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::kumo::nlp::TermInfo>(GetArena());
    _impl_.origin_ = reinterpret_cast<::kumo::nlp::TermInfo*>(p);
  }
  return _impl_.origin_;
}
inline ::kumo::nlp::TermInfo* RewriteQueryInfo::mutable_origin() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::kumo::nlp::TermInfo* _msg = _internal_mutable_origin();
  // @@protoc_insertion_point(field_mutable:kumo.nlp.RewriteQueryInfo.origin)
  return _msg;
}
inline void RewriteQueryInfo::set_allocated_origin(::kumo::nlp::TermInfo* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.origin_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.origin_ = reinterpret_cast<::kumo::nlp::TermInfo*>(value);
  // @@protoc_insertion_point(field_set_allocated:kumo.nlp.RewriteQueryInfo.origin)
}

// .kumo.nlp.TermInfo rewrite_term = 4;
inline bool RewriteQueryInfo::has_rewrite_term() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.rewrite_term_ != nullptr);
  return value;
}
inline const ::kumo::nlp::TermInfo& RewriteQueryInfo::_internal_rewrite_term() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::kumo::nlp::TermInfo* p = _impl_.rewrite_term_;
  return p != nullptr ? *p : reinterpret_cast<const ::kumo::nlp::TermInfo&>(::kumo::nlp::_TermInfo_default_instance_);
}
inline const ::kumo::nlp::TermInfo& RewriteQueryInfo::rewrite_term() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:kumo.nlp.RewriteQueryInfo.rewrite_term)
  return _internal_rewrite_term();
}
inline void RewriteQueryInfo::unsafe_arena_set_allocated_rewrite_term(::kumo::nlp::TermInfo* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.rewrite_term_);
  }
  _impl_.rewrite_term_ = reinterpret_cast<::kumo::nlp::TermInfo*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:kumo.nlp.RewriteQueryInfo.rewrite_term)
}
inline ::kumo::nlp::TermInfo* RewriteQueryInfo::release_rewrite_term() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::kumo::nlp::TermInfo* released = _impl_.rewrite_term_;
  _impl_.rewrite_term_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::kumo::nlp::TermInfo* RewriteQueryInfo::unsafe_arena_release_rewrite_term() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:kumo.nlp.RewriteQueryInfo.rewrite_term)

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::kumo::nlp::TermInfo* temp = _impl_.rewrite_term_;
  _impl_.rewrite_term_ = nullptr;
  return temp;
}
inline ::kumo::nlp::TermInfo* RewriteQueryInfo::_internal_mutable_rewrite_term() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.rewrite_term_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::kumo::nlp::TermInfo>(GetArena());
    _impl_.rewrite_term_ = reinterpret_cast<::kumo::nlp::TermInfo*>(p);
  }
  return _impl_.rewrite_term_;
}
inline ::kumo::nlp::TermInfo* RewriteQueryInfo::mutable_rewrite_term() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000002u;
  ::kumo::nlp::TermInfo* _msg = _internal_mutable_rewrite_term();
  // @@protoc_insertion_point(field_mutable:kumo.nlp.RewriteQueryInfo.rewrite_term)
  return _msg;
}
inline void RewriteQueryInfo::set_allocated_rewrite_term(::kumo::nlp::TermInfo* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.rewrite_term_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }

  _impl_.rewrite_term_ = reinterpret_cast<::kumo::nlp::TermInfo*>(value);
  // @@protoc_insertion_point(field_set_allocated:kumo.nlp.RewriteQueryInfo.rewrite_term)
}

// bool is_recall = 5;
inline void RewriteQueryInfo::clear_is_recall() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.is_recall_ = false;
}
inline bool RewriteQueryInfo::is_recall() const {
  // @@protoc_insertion_point(field_get:kumo.nlp.RewriteQueryInfo.is_recall)
  return _internal_is_recall();
}
inline void RewriteQueryInfo::set_is_recall(bool value) {
  _internal_set_is_recall(value);
  // @@protoc_insertion_point(field_set:kumo.nlp.RewriteQueryInfo.is_recall)
}
inline bool RewriteQueryInfo::_internal_is_recall() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.is_recall_;
}
inline void RewriteQueryInfo::_internal_set_is_recall(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.is_recall_ = value;
}

// string extra_json = 6;
inline void RewriteQueryInfo::clear_extra_json() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.extra_json_.ClearToEmpty();
}
inline const std::string& RewriteQueryInfo::extra_json() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:kumo.nlp.RewriteQueryInfo.extra_json)
  return _internal_extra_json();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void RewriteQueryInfo::set_extra_json(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.extra_json_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:kumo.nlp.RewriteQueryInfo.extra_json)
}
inline std::string* RewriteQueryInfo::mutable_extra_json() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_extra_json();
  // @@protoc_insertion_point(field_mutable:kumo.nlp.RewriteQueryInfo.extra_json)
  return _s;
}
inline const std::string& RewriteQueryInfo::_internal_extra_json() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.extra_json_.Get();
}
inline void RewriteQueryInfo::_internal_set_extra_json(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.extra_json_.Set(value, GetArena());
}
inline std::string* RewriteQueryInfo::_internal_mutable_extra_json() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.extra_json_.Mutable( GetArena());
}
inline std::string* RewriteQueryInfo::release_extra_json() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:kumo.nlp.RewriteQueryInfo.extra_json)
  return _impl_.extra_json_.Release();
}
inline void RewriteQueryInfo::set_allocated_extra_json(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.extra_json_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.extra_json_.IsDefault()) {
    _impl_.extra_json_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:kumo.nlp.RewriteQueryInfo.extra_json)
}

// string debug_info = 7;
inline void RewriteQueryInfo::clear_debug_info() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.debug_info_.ClearToEmpty();
}
inline const std::string& RewriteQueryInfo::debug_info() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:kumo.nlp.RewriteQueryInfo.debug_info)
  return _internal_debug_info();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void RewriteQueryInfo::set_debug_info(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.debug_info_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:kumo.nlp.RewriteQueryInfo.debug_info)
}
inline std::string* RewriteQueryInfo::mutable_debug_info() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_debug_info();
  // @@protoc_insertion_point(field_mutable:kumo.nlp.RewriteQueryInfo.debug_info)
  return _s;
}
inline const std::string& RewriteQueryInfo::_internal_debug_info() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.debug_info_.Get();
}
inline void RewriteQueryInfo::_internal_set_debug_info(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.debug_info_.Set(value, GetArena());
}
inline std::string* RewriteQueryInfo::_internal_mutable_debug_info() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.debug_info_.Mutable( GetArena());
}
inline std::string* RewriteQueryInfo::release_debug_info() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:kumo.nlp.RewriteQueryInfo.debug_info)
  return _impl_.debug_info_.Release();
}
inline void RewriteQueryInfo::set_allocated_debug_info(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.debug_info_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.debug_info_.IsDefault()) {
    _impl_.debug_info_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:kumo.nlp.RewriteQueryInfo.debug_info)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace nlp
}  // namespace kumo


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // gnef_2fproto_2frewrite_2eproto_2epb_2eh
