// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: gnef/proto/rewrite.proto
// Protobuf C++ Version: 5.29.5

#include "gnef/proto/rewrite.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace kumo {
namespace nlp {

inline constexpr RewriteSetting::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : enable_synonym_{false},
        enable_correct_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR RewriteSetting::RewriteSetting(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct RewriteSettingDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RewriteSettingDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RewriteSettingDefaultTypeInternal() {}
  union {
    RewriteSetting _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RewriteSettingDefaultTypeInternal _RewriteSetting_default_instance_;

inline constexpr RewriteQueryInfo::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        extra_json_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        debug_info_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        origin_{nullptr},
        rewrite_term_{nullptr},
        belief_{0},
        level_{0},
        is_recall_{false} {}

template <typename>
PROTOBUF_CONSTEXPR RewriteQueryInfo::RewriteQueryInfo(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct RewriteQueryInfoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RewriteQueryInfoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RewriteQueryInfoDefaultTypeInternal() {}
  union {
    RewriteQueryInfo _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RewriteQueryInfoDefaultTypeInternal _RewriteQueryInfo_default_instance_;
}  // namespace nlp
}  // namespace kumo
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_gnef_2fproto_2frewrite_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_gnef_2fproto_2frewrite_2eproto = nullptr;
const ::uint32_t
    TableStruct_gnef_2fproto_2frewrite_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::kumo::nlp::RewriteSetting, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::kumo::nlp::RewriteSetting, _impl_.enable_synonym_),
        PROTOBUF_FIELD_OFFSET(::kumo::nlp::RewriteSetting, _impl_.enable_correct_),
        PROTOBUF_FIELD_OFFSET(::kumo::nlp::RewriteQueryInfo, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::kumo::nlp::RewriteQueryInfo, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::kumo::nlp::RewriteQueryInfo, _impl_.belief_),
        PROTOBUF_FIELD_OFFSET(::kumo::nlp::RewriteQueryInfo, _impl_.level_),
        PROTOBUF_FIELD_OFFSET(::kumo::nlp::RewriteQueryInfo, _impl_.origin_),
        PROTOBUF_FIELD_OFFSET(::kumo::nlp::RewriteQueryInfo, _impl_.rewrite_term_),
        PROTOBUF_FIELD_OFFSET(::kumo::nlp::RewriteQueryInfo, _impl_.is_recall_),
        PROTOBUF_FIELD_OFFSET(::kumo::nlp::RewriteQueryInfo, _impl_.extra_json_),
        PROTOBUF_FIELD_OFFSET(::kumo::nlp::RewriteQueryInfo, _impl_.debug_info_),
        ~0u,
        ~0u,
        0,
        1,
        ~0u,
        ~0u,
        ~0u,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::kumo::nlp::RewriteSetting)},
        {10, 25, -1, sizeof(::kumo::nlp::RewriteQueryInfo)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::kumo::nlp::_RewriteSetting_default_instance_._instance,
    &::kumo::nlp::_RewriteQueryInfo_default_instance_._instance,
};
const char descriptor_table_protodef_gnef_2fproto_2frewrite_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\030gnef/proto/rewrite.proto\022\010kumo.nlp\032\030gn"
    "ef/proto/segment.proto\"@\n\016RewriteSetting"
    "\022\026\n\016enable_synonym\030\001 \001(\010\022\026\n\016enable_corre"
    "ct\030\002 \001(\010\"\272\001\n\020RewriteQueryInfo\022\016\n\006belief\030"
    "\001 \001(\001\022\r\n\005level\030\002 \001(\005\022\"\n\006origin\030\003 \001(\0132\022.k"
    "umo.nlp.TermInfo\022(\n\014rewrite_term\030\004 \001(\0132\022"
    ".kumo.nlp.TermInfo\022\021\n\tis_recall\030\005 \001(\010\022\022\n"
    "\nextra_json\030\006 \001(\t\022\022\n\ndebug_info\030\007 \001(\tb\006p"
    "roto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_gnef_2fproto_2frewrite_2eproto_deps[1] =
    {
        &::descriptor_table_gnef_2fproto_2fsegment_2eproto,
};
static ::absl::once_flag descriptor_table_gnef_2fproto_2frewrite_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_gnef_2fproto_2frewrite_2eproto = {
    false,
    false,
    325,
    descriptor_table_protodef_gnef_2fproto_2frewrite_2eproto,
    "gnef/proto/rewrite.proto",
    &descriptor_table_gnef_2fproto_2frewrite_2eproto_once,
    descriptor_table_gnef_2fproto_2frewrite_2eproto_deps,
    1,
    2,
    schemas,
    file_default_instances,
    TableStruct_gnef_2fproto_2frewrite_2eproto::offsets,
    file_level_enum_descriptors_gnef_2fproto_2frewrite_2eproto,
    file_level_service_descriptors_gnef_2fproto_2frewrite_2eproto,
};
namespace kumo {
namespace nlp {
// ===================================================================

class RewriteSetting::_Internal {
 public:
};

RewriteSetting::RewriteSetting(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:kumo.nlp.RewriteSetting)
}
RewriteSetting::RewriteSetting(
    ::google::protobuf::Arena* arena, const RewriteSetting& from)
    : RewriteSetting(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE RewriteSetting::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void RewriteSetting::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, enable_synonym_),
           0,
           offsetof(Impl_, enable_correct_) -
               offsetof(Impl_, enable_synonym_) +
               sizeof(Impl_::enable_correct_));
}
RewriteSetting::~RewriteSetting() {
  // @@protoc_insertion_point(destructor:kumo.nlp.RewriteSetting)
  SharedDtor(*this);
}
inline void RewriteSetting::SharedDtor(MessageLite& self) {
  RewriteSetting& this_ = static_cast<RewriteSetting&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* RewriteSetting::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) RewriteSetting(arena);
}
constexpr auto RewriteSetting::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(RewriteSetting),
                                            alignof(RewriteSetting));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull RewriteSetting::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_RewriteSetting_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &RewriteSetting::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<RewriteSetting>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &RewriteSetting::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<RewriteSetting>(), &RewriteSetting::ByteSizeLong,
            &RewriteSetting::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(RewriteSetting, _impl_._cached_size_),
        false,
    },
    &RewriteSetting::kDescriptorMethods,
    &descriptor_table_gnef_2fproto_2frewrite_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* RewriteSetting::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> RewriteSetting::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::kumo::nlp::RewriteSetting>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bool enable_correct = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(RewriteSetting, _impl_.enable_correct_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(RewriteSetting, _impl_.enable_correct_)}},
    // bool enable_synonym = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(RewriteSetting, _impl_.enable_synonym_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(RewriteSetting, _impl_.enable_synonym_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool enable_synonym = 1;
    {PROTOBUF_FIELD_OFFSET(RewriteSetting, _impl_.enable_synonym_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // bool enable_correct = 2;
    {PROTOBUF_FIELD_OFFSET(RewriteSetting, _impl_.enable_correct_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void RewriteSetting::Clear() {
// @@protoc_insertion_point(message_clear_start:kumo.nlp.RewriteSetting)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.enable_synonym_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.enable_correct_) -
      reinterpret_cast<char*>(&_impl_.enable_synonym_)) + sizeof(_impl_.enable_correct_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* RewriteSetting::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const RewriteSetting& this_ = static_cast<const RewriteSetting&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* RewriteSetting::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const RewriteSetting& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:kumo.nlp.RewriteSetting)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // bool enable_synonym = 1;
          if (this_._internal_enable_synonym() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                1, this_._internal_enable_synonym(), target);
          }

          // bool enable_correct = 2;
          if (this_._internal_enable_correct() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                2, this_._internal_enable_correct(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:kumo.nlp.RewriteSetting)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t RewriteSetting::ByteSizeLong(const MessageLite& base) {
          const RewriteSetting& this_ = static_cast<const RewriteSetting&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t RewriteSetting::ByteSizeLong() const {
          const RewriteSetting& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:kumo.nlp.RewriteSetting)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // bool enable_synonym = 1;
            if (this_._internal_enable_synonym() != 0) {
              total_size += 2;
            }
            // bool enable_correct = 2;
            if (this_._internal_enable_correct() != 0) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void RewriteSetting::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<RewriteSetting*>(&to_msg);
  auto& from = static_cast<const RewriteSetting&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:kumo.nlp.RewriteSetting)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_enable_synonym() != 0) {
    _this->_impl_.enable_synonym_ = from._impl_.enable_synonym_;
  }
  if (from._internal_enable_correct() != 0) {
    _this->_impl_.enable_correct_ = from._impl_.enable_correct_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void RewriteSetting::CopyFrom(const RewriteSetting& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:kumo.nlp.RewriteSetting)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void RewriteSetting::InternalSwap(RewriteSetting* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(RewriteSetting, _impl_.enable_correct_)
      + sizeof(RewriteSetting::_impl_.enable_correct_)
      - PROTOBUF_FIELD_OFFSET(RewriteSetting, _impl_.enable_synonym_)>(
          reinterpret_cast<char*>(&_impl_.enable_synonym_),
          reinterpret_cast<char*>(&other->_impl_.enable_synonym_));
}

::google::protobuf::Metadata RewriteSetting::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class RewriteQueryInfo::_Internal {
 public:
  using HasBits =
      decltype(std::declval<RewriteQueryInfo>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(RewriteQueryInfo, _impl_._has_bits_);
};

void RewriteQueryInfo::clear_origin() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.origin_ != nullptr) _impl_.origin_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
void RewriteQueryInfo::clear_rewrite_term() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.rewrite_term_ != nullptr) _impl_.rewrite_term_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
RewriteQueryInfo::RewriteQueryInfo(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:kumo.nlp.RewriteQueryInfo)
}
inline PROTOBUF_NDEBUG_INLINE RewriteQueryInfo::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::kumo::nlp::RewriteQueryInfo& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        extra_json_(arena, from.extra_json_),
        debug_info_(arena, from.debug_info_) {}

RewriteQueryInfo::RewriteQueryInfo(
    ::google::protobuf::Arena* arena,
    const RewriteQueryInfo& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  RewriteQueryInfo* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.origin_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::kumo::nlp::TermInfo>(
                              arena, *from._impl_.origin_)
                        : nullptr;
  _impl_.rewrite_term_ = (cached_has_bits & 0x00000002u) ? ::google::protobuf::Message::CopyConstruct<::kumo::nlp::TermInfo>(
                              arena, *from._impl_.rewrite_term_)
                        : nullptr;
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, belief_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, belief_),
           offsetof(Impl_, is_recall_) -
               offsetof(Impl_, belief_) +
               sizeof(Impl_::is_recall_));

  // @@protoc_insertion_point(copy_constructor:kumo.nlp.RewriteQueryInfo)
}
inline PROTOBUF_NDEBUG_INLINE RewriteQueryInfo::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        extra_json_(arena),
        debug_info_(arena) {}

inline void RewriteQueryInfo::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, origin_),
           0,
           offsetof(Impl_, is_recall_) -
               offsetof(Impl_, origin_) +
               sizeof(Impl_::is_recall_));
}
RewriteQueryInfo::~RewriteQueryInfo() {
  // @@protoc_insertion_point(destructor:kumo.nlp.RewriteQueryInfo)
  SharedDtor(*this);
}
inline void RewriteQueryInfo::SharedDtor(MessageLite& self) {
  RewriteQueryInfo& this_ = static_cast<RewriteQueryInfo&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.extra_json_.Destroy();
  this_._impl_.debug_info_.Destroy();
  delete this_._impl_.origin_;
  delete this_._impl_.rewrite_term_;
  this_._impl_.~Impl_();
}

inline void* RewriteQueryInfo::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) RewriteQueryInfo(arena);
}
constexpr auto RewriteQueryInfo::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(RewriteQueryInfo),
                                            alignof(RewriteQueryInfo));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull RewriteQueryInfo::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_RewriteQueryInfo_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &RewriteQueryInfo::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<RewriteQueryInfo>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &RewriteQueryInfo::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<RewriteQueryInfo>(), &RewriteQueryInfo::ByteSizeLong,
            &RewriteQueryInfo::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(RewriteQueryInfo, _impl_._cached_size_),
        false,
    },
    &RewriteQueryInfo::kDescriptorMethods,
    &descriptor_table_gnef_2fproto_2frewrite_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* RewriteQueryInfo::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 7, 2, 54, 2> RewriteQueryInfo::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(RewriteQueryInfo, _impl_._has_bits_),
    0, // no _extensions_
    7, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967168,  // skipmap
    offsetof(decltype(_table_), field_entries),
    7,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::kumo::nlp::RewriteQueryInfo>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // double belief = 1;
    {::_pbi::TcParser::FastF64S1,
     {9, 63, 0, PROTOBUF_FIELD_OFFSET(RewriteQueryInfo, _impl_.belief_)}},
    // int32 level = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(RewriteQueryInfo, _impl_.level_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(RewriteQueryInfo, _impl_.level_)}},
    // .kumo.nlp.TermInfo origin = 3;
    {::_pbi::TcParser::FastMtS1,
     {26, 0, 0, PROTOBUF_FIELD_OFFSET(RewriteQueryInfo, _impl_.origin_)}},
    // .kumo.nlp.TermInfo rewrite_term = 4;
    {::_pbi::TcParser::FastMtS1,
     {34, 1, 1, PROTOBUF_FIELD_OFFSET(RewriteQueryInfo, _impl_.rewrite_term_)}},
    // bool is_recall = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(RewriteQueryInfo, _impl_.is_recall_), 63>(),
     {40, 63, 0, PROTOBUF_FIELD_OFFSET(RewriteQueryInfo, _impl_.is_recall_)}},
    // string extra_json = 6;
    {::_pbi::TcParser::FastUS1,
     {50, 63, 0, PROTOBUF_FIELD_OFFSET(RewriteQueryInfo, _impl_.extra_json_)}},
    // string debug_info = 7;
    {::_pbi::TcParser::FastUS1,
     {58, 63, 0, PROTOBUF_FIELD_OFFSET(RewriteQueryInfo, _impl_.debug_info_)}},
  }}, {{
    65535, 65535
  }}, {{
    // double belief = 1;
    {PROTOBUF_FIELD_OFFSET(RewriteQueryInfo, _impl_.belief_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // int32 level = 2;
    {PROTOBUF_FIELD_OFFSET(RewriteQueryInfo, _impl_.level_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // .kumo.nlp.TermInfo origin = 3;
    {PROTOBUF_FIELD_OFFSET(RewriteQueryInfo, _impl_.origin_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .kumo.nlp.TermInfo rewrite_term = 4;
    {PROTOBUF_FIELD_OFFSET(RewriteQueryInfo, _impl_.rewrite_term_), _Internal::kHasBitsOffset + 1, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // bool is_recall = 5;
    {PROTOBUF_FIELD_OFFSET(RewriteQueryInfo, _impl_.is_recall_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // string extra_json = 6;
    {PROTOBUF_FIELD_OFFSET(RewriteQueryInfo, _impl_.extra_json_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string debug_info = 7;
    {PROTOBUF_FIELD_OFFSET(RewriteQueryInfo, _impl_.debug_info_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }}, {{
    {::_pbi::TcParser::GetTable<::kumo::nlp::TermInfo>()},
    {::_pbi::TcParser::GetTable<::kumo::nlp::TermInfo>()},
  }}, {{
    "\31\0\0\0\0\0\12\12"
    "kumo.nlp.RewriteQueryInfo"
    "extra_json"
    "debug_info"
  }},
};

PROTOBUF_NOINLINE void RewriteQueryInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:kumo.nlp.RewriteQueryInfo)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.extra_json_.ClearToEmpty();
  _impl_.debug_info_.ClearToEmpty();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(_impl_.origin_ != nullptr);
      _impl_.origin_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(_impl_.rewrite_term_ != nullptr);
      _impl_.rewrite_term_->Clear();
    }
  }
  ::memset(&_impl_.belief_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.is_recall_) -
      reinterpret_cast<char*>(&_impl_.belief_)) + sizeof(_impl_.is_recall_));
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* RewriteQueryInfo::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const RewriteQueryInfo& this_ = static_cast<const RewriteQueryInfo&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* RewriteQueryInfo::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const RewriteQueryInfo& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:kumo.nlp.RewriteQueryInfo)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // double belief = 1;
          if (::absl::bit_cast<::uint64_t>(this_._internal_belief()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                1, this_._internal_belief(), target);
          }

          // int32 level = 2;
          if (this_._internal_level() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<2>(
                    stream, this_._internal_level(), target);
          }

          cached_has_bits = this_._impl_._has_bits_[0];
          // .kumo.nlp.TermInfo origin = 3;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                3, *this_._impl_.origin_, this_._impl_.origin_->GetCachedSize(), target,
                stream);
          }

          // .kumo.nlp.TermInfo rewrite_term = 4;
          if (cached_has_bits & 0x00000002u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                4, *this_._impl_.rewrite_term_, this_._impl_.rewrite_term_->GetCachedSize(), target,
                stream);
          }

          // bool is_recall = 5;
          if (this_._internal_is_recall() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                5, this_._internal_is_recall(), target);
          }

          // string extra_json = 6;
          if (!this_._internal_extra_json().empty()) {
            const std::string& _s = this_._internal_extra_json();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "kumo.nlp.RewriteQueryInfo.extra_json");
            target = stream->WriteStringMaybeAliased(6, _s, target);
          }

          // string debug_info = 7;
          if (!this_._internal_debug_info().empty()) {
            const std::string& _s = this_._internal_debug_info();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "kumo.nlp.RewriteQueryInfo.debug_info");
            target = stream->WriteStringMaybeAliased(7, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:kumo.nlp.RewriteQueryInfo)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t RewriteQueryInfo::ByteSizeLong(const MessageLite& base) {
          const RewriteQueryInfo& this_ = static_cast<const RewriteQueryInfo&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t RewriteQueryInfo::ByteSizeLong() const {
          const RewriteQueryInfo& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:kumo.nlp.RewriteQueryInfo)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string extra_json = 6;
            if (!this_._internal_extra_json().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_extra_json());
            }
            // string debug_info = 7;
            if (!this_._internal_debug_info().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_debug_info());
            }
          }
          cached_has_bits = this_._impl_._has_bits_[0];
          if (cached_has_bits & 0x00000003u) {
            // .kumo.nlp.TermInfo origin = 3;
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.origin_);
            }
            // .kumo.nlp.TermInfo rewrite_term = 4;
            if (cached_has_bits & 0x00000002u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.rewrite_term_);
            }
          }
           {
            // double belief = 1;
            if (::absl::bit_cast<::uint64_t>(this_._internal_belief()) != 0) {
              total_size += 9;
            }
            // int32 level = 2;
            if (this_._internal_level() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_level());
            }
            // bool is_recall = 5;
            if (this_._internal_is_recall() != 0) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void RewriteQueryInfo::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<RewriteQueryInfo*>(&to_msg);
  auto& from = static_cast<const RewriteQueryInfo&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:kumo.nlp.RewriteQueryInfo)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_extra_json().empty()) {
    _this->_internal_set_extra_json(from._internal_extra_json());
  }
  if (!from._internal_debug_info().empty()) {
    _this->_internal_set_debug_info(from._internal_debug_info());
  }
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(from._impl_.origin_ != nullptr);
      if (_this->_impl_.origin_ == nullptr) {
        _this->_impl_.origin_ =
            ::google::protobuf::Message::CopyConstruct<::kumo::nlp::TermInfo>(arena, *from._impl_.origin_);
      } else {
        _this->_impl_.origin_->MergeFrom(*from._impl_.origin_);
      }
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(from._impl_.rewrite_term_ != nullptr);
      if (_this->_impl_.rewrite_term_ == nullptr) {
        _this->_impl_.rewrite_term_ =
            ::google::protobuf::Message::CopyConstruct<::kumo::nlp::TermInfo>(arena, *from._impl_.rewrite_term_);
      } else {
        _this->_impl_.rewrite_term_->MergeFrom(*from._impl_.rewrite_term_);
      }
    }
  }
  if (::absl::bit_cast<::uint64_t>(from._internal_belief()) != 0) {
    _this->_impl_.belief_ = from._impl_.belief_;
  }
  if (from._internal_level() != 0) {
    _this->_impl_.level_ = from._impl_.level_;
  }
  if (from._internal_is_recall() != 0) {
    _this->_impl_.is_recall_ = from._impl_.is_recall_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void RewriteQueryInfo::CopyFrom(const RewriteQueryInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:kumo.nlp.RewriteQueryInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void RewriteQueryInfo::InternalSwap(RewriteQueryInfo* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.extra_json_, &other->_impl_.extra_json_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.debug_info_, &other->_impl_.debug_info_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(RewriteQueryInfo, _impl_.is_recall_)
      + sizeof(RewriteQueryInfo::_impl_.is_recall_)
      - PROTOBUF_FIELD_OFFSET(RewriteQueryInfo, _impl_.origin_)>(
          reinterpret_cast<char*>(&_impl_.origin_),
          reinterpret_cast<char*>(&other->_impl_.origin_));
}

::google::protobuf::Metadata RewriteQueryInfo::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace nlp
}  // namespace kumo
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_gnef_2fproto_2frewrite_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
