// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: gnef/proto/search.proto
// Protobuf C++ Version: 5.29.5

#include "gnef/proto/search.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace kumo {
namespace nlp {

inline constexpr NlpSetting::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        normalize_setting_{nullptr},
        segment_setting_{nullptr},
        ner_setting_{nullptr},
        embedding_setting_{nullptr},
        ngram_setting_{nullptr},
        rewrite_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR NlpSetting::NlpSetting(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct NlpSettingDefaultTypeInternal {
  PROTOBUF_CONSTEXPR NlpSettingDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~NlpSettingDefaultTypeInternal() {}
  union {
    NlpSetting _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 NlpSettingDefaultTypeInternal _NlpSetting_default_instance_;

inline constexpr NlpRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        query_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        setting_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR NlpRequest::NlpRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct NlpRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR NlpRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~NlpRequestDefaultTypeInternal() {}
  union {
    NlpRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 NlpRequestDefaultTypeInternal _NlpRequest_default_instance_;

inline constexpr NlpResult::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        entities_{},
        feature_{},
        ngram_{},
        tokens_{},
        rewrite_{},
        raw_query_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        lang_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        query_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        pinyin_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        pinyin_short_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        terms_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR NlpResult::NlpResult(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct NlpResultDefaultTypeInternal {
  PROTOBUF_CONSTEXPR NlpResultDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~NlpResultDefaultTypeInternal() {}
  union {
    NlpResult _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 NlpResultDefaultTypeInternal _NlpResult_default_instance_;
}  // namespace nlp
}  // namespace kumo
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_gnef_2fproto_2fsearch_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_gnef_2fproto_2fsearch_2eproto = nullptr;
const ::uint32_t
    TableStruct_gnef_2fproto_2fsearch_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::kumo::nlp::NlpSetting, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::kumo::nlp::NlpSetting, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::kumo::nlp::NlpSetting, _impl_.name_),
        PROTOBUF_FIELD_OFFSET(::kumo::nlp::NlpSetting, _impl_.normalize_setting_),
        PROTOBUF_FIELD_OFFSET(::kumo::nlp::NlpSetting, _impl_.segment_setting_),
        PROTOBUF_FIELD_OFFSET(::kumo::nlp::NlpSetting, _impl_.ner_setting_),
        PROTOBUF_FIELD_OFFSET(::kumo::nlp::NlpSetting, _impl_.embedding_setting_),
        PROTOBUF_FIELD_OFFSET(::kumo::nlp::NlpSetting, _impl_.ngram_setting_),
        PROTOBUF_FIELD_OFFSET(::kumo::nlp::NlpSetting, _impl_.rewrite_),
        ~0u,
        0,
        1,
        2,
        3,
        4,
        5,
        PROTOBUF_FIELD_OFFSET(::kumo::nlp::NlpRequest, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::kumo::nlp::NlpRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::kumo::nlp::NlpRequest, _impl_.query_),
        PROTOBUF_FIELD_OFFSET(::kumo::nlp::NlpRequest, _impl_.setting_),
        ~0u,
        0,
        PROTOBUF_FIELD_OFFSET(::kumo::nlp::NlpResult, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::kumo::nlp::NlpResult, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::kumo::nlp::NlpResult, _impl_.raw_query_),
        PROTOBUF_FIELD_OFFSET(::kumo::nlp::NlpResult, _impl_.lang_),
        PROTOBUF_FIELD_OFFSET(::kumo::nlp::NlpResult, _impl_.query_),
        PROTOBUF_FIELD_OFFSET(::kumo::nlp::NlpResult, _impl_.pinyin_),
        PROTOBUF_FIELD_OFFSET(::kumo::nlp::NlpResult, _impl_.pinyin_short_),
        PROTOBUF_FIELD_OFFSET(::kumo::nlp::NlpResult, _impl_.terms_),
        PROTOBUF_FIELD_OFFSET(::kumo::nlp::NlpResult, _impl_.entities_),
        PROTOBUF_FIELD_OFFSET(::kumo::nlp::NlpResult, _impl_.feature_),
        PROTOBUF_FIELD_OFFSET(::kumo::nlp::NlpResult, _impl_.ngram_),
        PROTOBUF_FIELD_OFFSET(::kumo::nlp::NlpResult, _impl_.tokens_),
        PROTOBUF_FIELD_OFFSET(::kumo::nlp::NlpResult, _impl_.rewrite_),
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        0,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 15, -1, sizeof(::kumo::nlp::NlpSetting)},
        {22, 32, -1, sizeof(::kumo::nlp::NlpRequest)},
        {34, 53, -1, sizeof(::kumo::nlp::NlpResult)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::kumo::nlp::_NlpSetting_default_instance_._instance,
    &::kumo::nlp::_NlpRequest_default_instance_._instance,
    &::kumo::nlp::_NlpResult_default_instance_._instance,
};
const char descriptor_table_protodef_gnef_2fproto_2fsearch_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\027gnef/proto/search.proto\022\010kumo.nlp\032\032gne"
    "f/proto/normalize.proto\032\030gnef/proto/segm"
    "ent.proto\032\024gnef/proto/ner.proto\032\031gnef/pr"
    "oto/embdding.proto\032\026gnef/proto/ngram.pro"
    "to\032\031gnef/proto/semantic.proto\032\030gnef/prot"
    "o/rewrite.proto\"\267\002\n\nNlpSetting\022\014\n\004name\030\001"
    " \001(\t\0225\n\021normalize_setting\030\002 \001(\0132\032.kumo.n"
    "lp.NormalizeSetting\0221\n\017segment_setting\030\003"
    " \001(\0132\030.kumo.nlp.SegmentSetting\022)\n\013ner_se"
    "tting\030\004 \001(\0132\024.kumo.nlp.NerSetting\0225\n\021emb"
    "edding_setting\030\005 \001(\0132\032.kumo.nlp.Embeddin"
    "gSetting\022$\n\rngram_setting\030\006 \001(\0132\r.NgramS"
    "etting\022)\n\007rewrite\030\007 \001(\0132\030.kumo.nlp.Rewri"
    "teSetting\"B\n\nNlpRequest\022\r\n\005query\030\001 \001(\t\022%"
    "\n\007setting\030\002 \001(\0132\024.kumo.nlp.NlpSetting\"\254\002"
    "\n\tNlpResult\022\021\n\traw_query\030\001 \001(\t\022\014\n\004lang\030\002"
    " \001(\t\022\r\n\005query\030\003 \001(\t\022\016\n\006pinyin\030\004 \001(\t\022\024\n\014p"
    "inyin_short\030\005 \001(\t\022&\n\005terms\030\006 \001(\0132\027.kumo."
    "nlp.SegmentResult\022#\n\010entities\030\007 \003(\0132\021.ku"
    "mo.nlp.NerInfo\022\017\n\007feature\030\010 \003(\002\022\031\n\005ngram"
    "\030\t \003(\0132\n.NgramInfo\022#\n\006tokens\030\n \003(\0132\023.kum"
    "o.nlp.TokenInfo\022+\n\007rewrite\030\013 \003(\0132\032.kumo."
    "nlp.RewriteQueryInfob\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_gnef_2fproto_2fsearch_2eproto_deps[7] =
    {
        &::descriptor_table_gnef_2fproto_2fembdding_2eproto,
        &::descriptor_table_gnef_2fproto_2fner_2eproto,
        &::descriptor_table_gnef_2fproto_2fngram_2eproto,
        &::descriptor_table_gnef_2fproto_2fnormalize_2eproto,
        &::descriptor_table_gnef_2fproto_2frewrite_2eproto,
        &::descriptor_table_gnef_2fproto_2fsegment_2eproto,
        &::descriptor_table_gnef_2fproto_2fsemantic_2eproto,
};
static ::absl::once_flag descriptor_table_gnef_2fproto_2fsearch_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_gnef_2fproto_2fsearch_2eproto = {
    false,
    false,
    908,
    descriptor_table_protodef_gnef_2fproto_2fsearch_2eproto,
    "gnef/proto/search.proto",
    &descriptor_table_gnef_2fproto_2fsearch_2eproto_once,
    descriptor_table_gnef_2fproto_2fsearch_2eproto_deps,
    7,
    3,
    schemas,
    file_default_instances,
    TableStruct_gnef_2fproto_2fsearch_2eproto::offsets,
    file_level_enum_descriptors_gnef_2fproto_2fsearch_2eproto,
    file_level_service_descriptors_gnef_2fproto_2fsearch_2eproto,
};
namespace kumo {
namespace nlp {
// ===================================================================

class NlpSetting::_Internal {
 public:
  using HasBits =
      decltype(std::declval<NlpSetting>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(NlpSetting, _impl_._has_bits_);
};

void NlpSetting::clear_normalize_setting() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.normalize_setting_ != nullptr) _impl_.normalize_setting_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
void NlpSetting::clear_segment_setting() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.segment_setting_ != nullptr) _impl_.segment_setting_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
void NlpSetting::clear_ner_setting() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.ner_setting_ != nullptr) _impl_.ner_setting_->Clear();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
void NlpSetting::clear_embedding_setting() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.embedding_setting_ != nullptr) _impl_.embedding_setting_->Clear();
  _impl_._has_bits_[0] &= ~0x00000008u;
}
void NlpSetting::clear_ngram_setting() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.ngram_setting_ != nullptr) _impl_.ngram_setting_->Clear();
  _impl_._has_bits_[0] &= ~0x00000010u;
}
void NlpSetting::clear_rewrite() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.rewrite_ != nullptr) _impl_.rewrite_->Clear();
  _impl_._has_bits_[0] &= ~0x00000020u;
}
NlpSetting::NlpSetting(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:kumo.nlp.NlpSetting)
}
inline PROTOBUF_NDEBUG_INLINE NlpSetting::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::kumo::nlp::NlpSetting& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        name_(arena, from.name_) {}

NlpSetting::NlpSetting(
    ::google::protobuf::Arena* arena,
    const NlpSetting& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  NlpSetting* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.normalize_setting_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::kumo::nlp::NormalizeSetting>(
                              arena, *from._impl_.normalize_setting_)
                        : nullptr;
  _impl_.segment_setting_ = (cached_has_bits & 0x00000002u) ? ::google::protobuf::Message::CopyConstruct<::kumo::nlp::SegmentSetting>(
                              arena, *from._impl_.segment_setting_)
                        : nullptr;
  _impl_.ner_setting_ = (cached_has_bits & 0x00000004u) ? ::google::protobuf::Message::CopyConstruct<::kumo::nlp::NerSetting>(
                              arena, *from._impl_.ner_setting_)
                        : nullptr;
  _impl_.embedding_setting_ = (cached_has_bits & 0x00000008u) ? ::google::protobuf::Message::CopyConstruct<::kumo::nlp::EmbeddingSetting>(
                              arena, *from._impl_.embedding_setting_)
                        : nullptr;
  _impl_.ngram_setting_ = (cached_has_bits & 0x00000010u) ? ::google::protobuf::Message::CopyConstruct<::NgramSetting>(
                              arena, *from._impl_.ngram_setting_)
                        : nullptr;
  _impl_.rewrite_ = (cached_has_bits & 0x00000020u) ? ::google::protobuf::Message::CopyConstruct<::kumo::nlp::RewriteSetting>(
                              arena, *from._impl_.rewrite_)
                        : nullptr;

  // @@protoc_insertion_point(copy_constructor:kumo.nlp.NlpSetting)
}
inline PROTOBUF_NDEBUG_INLINE NlpSetting::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        name_(arena) {}

inline void NlpSetting::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, normalize_setting_),
           0,
           offsetof(Impl_, rewrite_) -
               offsetof(Impl_, normalize_setting_) +
               sizeof(Impl_::rewrite_));
}
NlpSetting::~NlpSetting() {
  // @@protoc_insertion_point(destructor:kumo.nlp.NlpSetting)
  SharedDtor(*this);
}
inline void NlpSetting::SharedDtor(MessageLite& self) {
  NlpSetting& this_ = static_cast<NlpSetting&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.name_.Destroy();
  delete this_._impl_.normalize_setting_;
  delete this_._impl_.segment_setting_;
  delete this_._impl_.ner_setting_;
  delete this_._impl_.embedding_setting_;
  delete this_._impl_.ngram_setting_;
  delete this_._impl_.rewrite_;
  this_._impl_.~Impl_();
}

inline void* NlpSetting::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) NlpSetting(arena);
}
constexpr auto NlpSetting::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(NlpSetting),
                                            alignof(NlpSetting));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull NlpSetting::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_NlpSetting_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &NlpSetting::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<NlpSetting>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &NlpSetting::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<NlpSetting>(), &NlpSetting::ByteSizeLong,
            &NlpSetting::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(NlpSetting, _impl_._cached_size_),
        false,
    },
    &NlpSetting::kDescriptorMethods,
    &descriptor_table_gnef_2fproto_2fsearch_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* NlpSetting::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 7, 6, 32, 2> NlpSetting::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(NlpSetting, _impl_._has_bits_),
    0, // no _extensions_
    7, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967168,  // skipmap
    offsetof(decltype(_table_), field_entries),
    7,  // num_field_entries
    6,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::kumo::nlp::NlpSetting>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(NlpSetting, _impl_.name_)}},
    // .kumo.nlp.NormalizeSetting normalize_setting = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(NlpSetting, _impl_.normalize_setting_)}},
    // .kumo.nlp.SegmentSetting segment_setting = 3;
    {::_pbi::TcParser::FastMtS1,
     {26, 1, 1, PROTOBUF_FIELD_OFFSET(NlpSetting, _impl_.segment_setting_)}},
    // .kumo.nlp.NerSetting ner_setting = 4;
    {::_pbi::TcParser::FastMtS1,
     {34, 2, 2, PROTOBUF_FIELD_OFFSET(NlpSetting, _impl_.ner_setting_)}},
    // .kumo.nlp.EmbeddingSetting embedding_setting = 5;
    {::_pbi::TcParser::FastMtS1,
     {42, 3, 3, PROTOBUF_FIELD_OFFSET(NlpSetting, _impl_.embedding_setting_)}},
    // .NgramSetting ngram_setting = 6;
    {::_pbi::TcParser::FastMtS1,
     {50, 4, 4, PROTOBUF_FIELD_OFFSET(NlpSetting, _impl_.ngram_setting_)}},
    // .kumo.nlp.RewriteSetting rewrite = 7;
    {::_pbi::TcParser::FastMtS1,
     {58, 5, 5, PROTOBUF_FIELD_OFFSET(NlpSetting, _impl_.rewrite_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string name = 1;
    {PROTOBUF_FIELD_OFFSET(NlpSetting, _impl_.name_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .kumo.nlp.NormalizeSetting normalize_setting = 2;
    {PROTOBUF_FIELD_OFFSET(NlpSetting, _impl_.normalize_setting_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .kumo.nlp.SegmentSetting segment_setting = 3;
    {PROTOBUF_FIELD_OFFSET(NlpSetting, _impl_.segment_setting_), _Internal::kHasBitsOffset + 1, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .kumo.nlp.NerSetting ner_setting = 4;
    {PROTOBUF_FIELD_OFFSET(NlpSetting, _impl_.ner_setting_), _Internal::kHasBitsOffset + 2, 2,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .kumo.nlp.EmbeddingSetting embedding_setting = 5;
    {PROTOBUF_FIELD_OFFSET(NlpSetting, _impl_.embedding_setting_), _Internal::kHasBitsOffset + 3, 3,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .NgramSetting ngram_setting = 6;
    {PROTOBUF_FIELD_OFFSET(NlpSetting, _impl_.ngram_setting_), _Internal::kHasBitsOffset + 4, 4,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .kumo.nlp.RewriteSetting rewrite = 7;
    {PROTOBUF_FIELD_OFFSET(NlpSetting, _impl_.rewrite_), _Internal::kHasBitsOffset + 5, 5,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::kumo::nlp::NormalizeSetting>()},
    {::_pbi::TcParser::GetTable<::kumo::nlp::SegmentSetting>()},
    {::_pbi::TcParser::GetTable<::kumo::nlp::NerSetting>()},
    {::_pbi::TcParser::GetTable<::kumo::nlp::EmbeddingSetting>()},
    {::_pbi::TcParser::GetTable<::NgramSetting>()},
    {::_pbi::TcParser::GetTable<::kumo::nlp::RewriteSetting>()},
  }}, {{
    "\23\4\0\0\0\0\0\0"
    "kumo.nlp.NlpSetting"
    "name"
  }},
};

PROTOBUF_NOINLINE void NlpSetting::Clear() {
// @@protoc_insertion_point(message_clear_start:kumo.nlp.NlpSetting)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.name_.ClearToEmpty();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000003fu) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(_impl_.normalize_setting_ != nullptr);
      _impl_.normalize_setting_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(_impl_.segment_setting_ != nullptr);
      _impl_.segment_setting_->Clear();
    }
    if (cached_has_bits & 0x00000004u) {
      ABSL_DCHECK(_impl_.ner_setting_ != nullptr);
      _impl_.ner_setting_->Clear();
    }
    if (cached_has_bits & 0x00000008u) {
      ABSL_DCHECK(_impl_.embedding_setting_ != nullptr);
      _impl_.embedding_setting_->Clear();
    }
    if (cached_has_bits & 0x00000010u) {
      ABSL_DCHECK(_impl_.ngram_setting_ != nullptr);
      _impl_.ngram_setting_->Clear();
    }
    if (cached_has_bits & 0x00000020u) {
      ABSL_DCHECK(_impl_.rewrite_ != nullptr);
      _impl_.rewrite_->Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* NlpSetting::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const NlpSetting& this_ = static_cast<const NlpSetting&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* NlpSetting::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const NlpSetting& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:kumo.nlp.NlpSetting)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string name = 1;
          if (!this_._internal_name().empty()) {
            const std::string& _s = this_._internal_name();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "kumo.nlp.NlpSetting.name");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          cached_has_bits = this_._impl_._has_bits_[0];
          // .kumo.nlp.NormalizeSetting normalize_setting = 2;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                2, *this_._impl_.normalize_setting_, this_._impl_.normalize_setting_->GetCachedSize(), target,
                stream);
          }

          // .kumo.nlp.SegmentSetting segment_setting = 3;
          if (cached_has_bits & 0x00000002u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                3, *this_._impl_.segment_setting_, this_._impl_.segment_setting_->GetCachedSize(), target,
                stream);
          }

          // .kumo.nlp.NerSetting ner_setting = 4;
          if (cached_has_bits & 0x00000004u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                4, *this_._impl_.ner_setting_, this_._impl_.ner_setting_->GetCachedSize(), target,
                stream);
          }

          // .kumo.nlp.EmbeddingSetting embedding_setting = 5;
          if (cached_has_bits & 0x00000008u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                5, *this_._impl_.embedding_setting_, this_._impl_.embedding_setting_->GetCachedSize(), target,
                stream);
          }

          // .NgramSetting ngram_setting = 6;
          if (cached_has_bits & 0x00000010u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                6, *this_._impl_.ngram_setting_, this_._impl_.ngram_setting_->GetCachedSize(), target,
                stream);
          }

          // .kumo.nlp.RewriteSetting rewrite = 7;
          if (cached_has_bits & 0x00000020u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                7, *this_._impl_.rewrite_, this_._impl_.rewrite_->GetCachedSize(), target,
                stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:kumo.nlp.NlpSetting)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t NlpSetting::ByteSizeLong(const MessageLite& base) {
          const NlpSetting& this_ = static_cast<const NlpSetting&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t NlpSetting::ByteSizeLong() const {
          const NlpSetting& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:kumo.nlp.NlpSetting)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string name = 1;
            if (!this_._internal_name().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_name());
            }
          }
          cached_has_bits = this_._impl_._has_bits_[0];
          if (cached_has_bits & 0x0000003fu) {
            // .kumo.nlp.NormalizeSetting normalize_setting = 2;
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.normalize_setting_);
            }
            // .kumo.nlp.SegmentSetting segment_setting = 3;
            if (cached_has_bits & 0x00000002u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.segment_setting_);
            }
            // .kumo.nlp.NerSetting ner_setting = 4;
            if (cached_has_bits & 0x00000004u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.ner_setting_);
            }
            // .kumo.nlp.EmbeddingSetting embedding_setting = 5;
            if (cached_has_bits & 0x00000008u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.embedding_setting_);
            }
            // .NgramSetting ngram_setting = 6;
            if (cached_has_bits & 0x00000010u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.ngram_setting_);
            }
            // .kumo.nlp.RewriteSetting rewrite = 7;
            if (cached_has_bits & 0x00000020u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.rewrite_);
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void NlpSetting::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<NlpSetting*>(&to_msg);
  auto& from = static_cast<const NlpSetting&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:kumo.nlp.NlpSetting)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x0000003fu) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(from._impl_.normalize_setting_ != nullptr);
      if (_this->_impl_.normalize_setting_ == nullptr) {
        _this->_impl_.normalize_setting_ =
            ::google::protobuf::Message::CopyConstruct<::kumo::nlp::NormalizeSetting>(arena, *from._impl_.normalize_setting_);
      } else {
        _this->_impl_.normalize_setting_->MergeFrom(*from._impl_.normalize_setting_);
      }
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(from._impl_.segment_setting_ != nullptr);
      if (_this->_impl_.segment_setting_ == nullptr) {
        _this->_impl_.segment_setting_ =
            ::google::protobuf::Message::CopyConstruct<::kumo::nlp::SegmentSetting>(arena, *from._impl_.segment_setting_);
      } else {
        _this->_impl_.segment_setting_->MergeFrom(*from._impl_.segment_setting_);
      }
    }
    if (cached_has_bits & 0x00000004u) {
      ABSL_DCHECK(from._impl_.ner_setting_ != nullptr);
      if (_this->_impl_.ner_setting_ == nullptr) {
        _this->_impl_.ner_setting_ =
            ::google::protobuf::Message::CopyConstruct<::kumo::nlp::NerSetting>(arena, *from._impl_.ner_setting_);
      } else {
        _this->_impl_.ner_setting_->MergeFrom(*from._impl_.ner_setting_);
      }
    }
    if (cached_has_bits & 0x00000008u) {
      ABSL_DCHECK(from._impl_.embedding_setting_ != nullptr);
      if (_this->_impl_.embedding_setting_ == nullptr) {
        _this->_impl_.embedding_setting_ =
            ::google::protobuf::Message::CopyConstruct<::kumo::nlp::EmbeddingSetting>(arena, *from._impl_.embedding_setting_);
      } else {
        _this->_impl_.embedding_setting_->MergeFrom(*from._impl_.embedding_setting_);
      }
    }
    if (cached_has_bits & 0x00000010u) {
      ABSL_DCHECK(from._impl_.ngram_setting_ != nullptr);
      if (_this->_impl_.ngram_setting_ == nullptr) {
        _this->_impl_.ngram_setting_ =
            ::google::protobuf::Message::CopyConstruct<::NgramSetting>(arena, *from._impl_.ngram_setting_);
      } else {
        _this->_impl_.ngram_setting_->MergeFrom(*from._impl_.ngram_setting_);
      }
    }
    if (cached_has_bits & 0x00000020u) {
      ABSL_DCHECK(from._impl_.rewrite_ != nullptr);
      if (_this->_impl_.rewrite_ == nullptr) {
        _this->_impl_.rewrite_ =
            ::google::protobuf::Message::CopyConstruct<::kumo::nlp::RewriteSetting>(arena, *from._impl_.rewrite_);
      } else {
        _this->_impl_.rewrite_->MergeFrom(*from._impl_.rewrite_);
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void NlpSetting::CopyFrom(const NlpSetting& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:kumo.nlp.NlpSetting)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void NlpSetting::InternalSwap(NlpSetting* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(NlpSetting, _impl_.rewrite_)
      + sizeof(NlpSetting::_impl_.rewrite_)
      - PROTOBUF_FIELD_OFFSET(NlpSetting, _impl_.normalize_setting_)>(
          reinterpret_cast<char*>(&_impl_.normalize_setting_),
          reinterpret_cast<char*>(&other->_impl_.normalize_setting_));
}

::google::protobuf::Metadata NlpSetting::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class NlpRequest::_Internal {
 public:
  using HasBits =
      decltype(std::declval<NlpRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(NlpRequest, _impl_._has_bits_);
};

NlpRequest::NlpRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:kumo.nlp.NlpRequest)
}
inline PROTOBUF_NDEBUG_INLINE NlpRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::kumo::nlp::NlpRequest& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        query_(arena, from.query_) {}

NlpRequest::NlpRequest(
    ::google::protobuf::Arena* arena,
    const NlpRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  NlpRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.setting_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::kumo::nlp::NlpSetting>(
                              arena, *from._impl_.setting_)
                        : nullptr;

  // @@protoc_insertion_point(copy_constructor:kumo.nlp.NlpRequest)
}
inline PROTOBUF_NDEBUG_INLINE NlpRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        query_(arena) {}

inline void NlpRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.setting_ = {};
}
NlpRequest::~NlpRequest() {
  // @@protoc_insertion_point(destructor:kumo.nlp.NlpRequest)
  SharedDtor(*this);
}
inline void NlpRequest::SharedDtor(MessageLite& self) {
  NlpRequest& this_ = static_cast<NlpRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.query_.Destroy();
  delete this_._impl_.setting_;
  this_._impl_.~Impl_();
}

inline void* NlpRequest::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) NlpRequest(arena);
}
constexpr auto NlpRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(NlpRequest),
                                            alignof(NlpRequest));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull NlpRequest::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_NlpRequest_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &NlpRequest::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<NlpRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &NlpRequest::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<NlpRequest>(), &NlpRequest::ByteSizeLong,
            &NlpRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(NlpRequest, _impl_._cached_size_),
        false,
    },
    &NlpRequest::kDescriptorMethods,
    &descriptor_table_gnef_2fproto_2fsearch_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* NlpRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 33, 2> NlpRequest::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(NlpRequest, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::kumo::nlp::NlpRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .kumo.nlp.NlpSetting setting = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(NlpRequest, _impl_.setting_)}},
    // string query = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(NlpRequest, _impl_.query_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string query = 1;
    {PROTOBUF_FIELD_OFFSET(NlpRequest, _impl_.query_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .kumo.nlp.NlpSetting setting = 2;
    {PROTOBUF_FIELD_OFFSET(NlpRequest, _impl_.setting_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::kumo::nlp::NlpSetting>()},
  }}, {{
    "\23\5\0\0\0\0\0\0"
    "kumo.nlp.NlpRequest"
    "query"
  }},
};

PROTOBUF_NOINLINE void NlpRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:kumo.nlp.NlpRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.query_.ClearToEmpty();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.setting_ != nullptr);
    _impl_.setting_->Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* NlpRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const NlpRequest& this_ = static_cast<const NlpRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* NlpRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const NlpRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:kumo.nlp.NlpRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string query = 1;
          if (!this_._internal_query().empty()) {
            const std::string& _s = this_._internal_query();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "kumo.nlp.NlpRequest.query");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          cached_has_bits = this_._impl_._has_bits_[0];
          // .kumo.nlp.NlpSetting setting = 2;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                2, *this_._impl_.setting_, this_._impl_.setting_->GetCachedSize(), target,
                stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:kumo.nlp.NlpRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t NlpRequest::ByteSizeLong(const MessageLite& base) {
          const NlpRequest& this_ = static_cast<const NlpRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t NlpRequest::ByteSizeLong() const {
          const NlpRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:kumo.nlp.NlpRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string query = 1;
            if (!this_._internal_query().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_query());
            }
          }
           {
            // .kumo.nlp.NlpSetting setting = 2;
            cached_has_bits = this_._impl_._has_bits_[0];
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.setting_);
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void NlpRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<NlpRequest*>(&to_msg);
  auto& from = static_cast<const NlpRequest&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:kumo.nlp.NlpRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_query().empty()) {
    _this->_internal_set_query(from._internal_query());
  }
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(from._impl_.setting_ != nullptr);
    if (_this->_impl_.setting_ == nullptr) {
      _this->_impl_.setting_ =
          ::google::protobuf::Message::CopyConstruct<::kumo::nlp::NlpSetting>(arena, *from._impl_.setting_);
    } else {
      _this->_impl_.setting_->MergeFrom(*from._impl_.setting_);
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void NlpRequest::CopyFrom(const NlpRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:kumo.nlp.NlpRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void NlpRequest::InternalSwap(NlpRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.query_, &other->_impl_.query_, arena);
  swap(_impl_.setting_, other->_impl_.setting_);
}

::google::protobuf::Metadata NlpRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class NlpResult::_Internal {
 public:
  using HasBits =
      decltype(std::declval<NlpResult>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(NlpResult, _impl_._has_bits_);
};

void NlpResult::clear_terms() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.terms_ != nullptr) _impl_.terms_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
void NlpResult::clear_entities() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.entities_.Clear();
}
void NlpResult::clear_ngram() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ngram_.Clear();
}
void NlpResult::clear_tokens() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.tokens_.Clear();
}
void NlpResult::clear_rewrite() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rewrite_.Clear();
}
NlpResult::NlpResult(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:kumo.nlp.NlpResult)
}
inline PROTOBUF_NDEBUG_INLINE NlpResult::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::kumo::nlp::NlpResult& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        entities_{visibility, arena, from.entities_},
        feature_{visibility, arena, from.feature_},
        ngram_{visibility, arena, from.ngram_},
        tokens_{visibility, arena, from.tokens_},
        rewrite_{visibility, arena, from.rewrite_},
        raw_query_(arena, from.raw_query_),
        lang_(arena, from.lang_),
        query_(arena, from.query_),
        pinyin_(arena, from.pinyin_),
        pinyin_short_(arena, from.pinyin_short_) {}

NlpResult::NlpResult(
    ::google::protobuf::Arena* arena,
    const NlpResult& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  NlpResult* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.terms_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::kumo::nlp::SegmentResult>(
                              arena, *from._impl_.terms_)
                        : nullptr;

  // @@protoc_insertion_point(copy_constructor:kumo.nlp.NlpResult)
}
inline PROTOBUF_NDEBUG_INLINE NlpResult::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        entities_{visibility, arena},
        feature_{visibility, arena},
        ngram_{visibility, arena},
        tokens_{visibility, arena},
        rewrite_{visibility, arena},
        raw_query_(arena),
        lang_(arena),
        query_(arena),
        pinyin_(arena),
        pinyin_short_(arena) {}

inline void NlpResult::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.terms_ = {};
}
NlpResult::~NlpResult() {
  // @@protoc_insertion_point(destructor:kumo.nlp.NlpResult)
  SharedDtor(*this);
}
inline void NlpResult::SharedDtor(MessageLite& self) {
  NlpResult& this_ = static_cast<NlpResult&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.raw_query_.Destroy();
  this_._impl_.lang_.Destroy();
  this_._impl_.query_.Destroy();
  this_._impl_.pinyin_.Destroy();
  this_._impl_.pinyin_short_.Destroy();
  delete this_._impl_.terms_;
  this_._impl_.~Impl_();
}

inline void* NlpResult::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) NlpResult(arena);
}
constexpr auto NlpResult::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(NlpResult, _impl_.entities_) +
          decltype(NlpResult::_impl_.entities_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(NlpResult, _impl_.feature_) +
          decltype(NlpResult::_impl_.feature_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(NlpResult, _impl_.ngram_) +
          decltype(NlpResult::_impl_.ngram_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(NlpResult, _impl_.tokens_) +
          decltype(NlpResult::_impl_.tokens_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(NlpResult, _impl_.rewrite_) +
          decltype(NlpResult::_impl_.rewrite_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(NlpResult), alignof(NlpResult), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&NlpResult::PlacementNew_,
                                 sizeof(NlpResult),
                                 alignof(NlpResult));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull NlpResult::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_NlpResult_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &NlpResult::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<NlpResult>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &NlpResult::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<NlpResult>(), &NlpResult::ByteSizeLong,
            &NlpResult::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(NlpResult, _impl_._cached_size_),
        false,
    },
    &NlpResult::kDescriptorMethods,
    &descriptor_table_gnef_2fproto_2fsearch_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* NlpResult::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<4, 11, 5, 71, 2> NlpResult::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(NlpResult, _impl_._has_bits_),
    0, // no _extensions_
    11, 120,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294965248,  // skipmap
    offsetof(decltype(_table_), field_entries),
    11,  // num_field_entries
    5,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::kumo::nlp::NlpResult>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string raw_query = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(NlpResult, _impl_.raw_query_)}},
    // string lang = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(NlpResult, _impl_.lang_)}},
    // string query = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(NlpResult, _impl_.query_)}},
    // string pinyin = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(NlpResult, _impl_.pinyin_)}},
    // string pinyin_short = 5;
    {::_pbi::TcParser::FastUS1,
     {42, 63, 0, PROTOBUF_FIELD_OFFSET(NlpResult, _impl_.pinyin_short_)}},
    // .kumo.nlp.SegmentResult terms = 6;
    {::_pbi::TcParser::FastMtS1,
     {50, 0, 0, PROTOBUF_FIELD_OFFSET(NlpResult, _impl_.terms_)}},
    // repeated .kumo.nlp.NerInfo entities = 7;
    {::_pbi::TcParser::FastMtR1,
     {58, 63, 1, PROTOBUF_FIELD_OFFSET(NlpResult, _impl_.entities_)}},
    // repeated float feature = 8;
    {::_pbi::TcParser::FastF32P1,
     {66, 63, 0, PROTOBUF_FIELD_OFFSET(NlpResult, _impl_.feature_)}},
    // repeated .NgramInfo ngram = 9;
    {::_pbi::TcParser::FastMtR1,
     {74, 63, 2, PROTOBUF_FIELD_OFFSET(NlpResult, _impl_.ngram_)}},
    // repeated .kumo.nlp.TokenInfo tokens = 10;
    {::_pbi::TcParser::FastMtR1,
     {82, 63, 3, PROTOBUF_FIELD_OFFSET(NlpResult, _impl_.tokens_)}},
    // repeated .kumo.nlp.RewriteQueryInfo rewrite = 11;
    {::_pbi::TcParser::FastMtR1,
     {90, 63, 4, PROTOBUF_FIELD_OFFSET(NlpResult, _impl_.rewrite_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // string raw_query = 1;
    {PROTOBUF_FIELD_OFFSET(NlpResult, _impl_.raw_query_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string lang = 2;
    {PROTOBUF_FIELD_OFFSET(NlpResult, _impl_.lang_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string query = 3;
    {PROTOBUF_FIELD_OFFSET(NlpResult, _impl_.query_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string pinyin = 4;
    {PROTOBUF_FIELD_OFFSET(NlpResult, _impl_.pinyin_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string pinyin_short = 5;
    {PROTOBUF_FIELD_OFFSET(NlpResult, _impl_.pinyin_short_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .kumo.nlp.SegmentResult terms = 6;
    {PROTOBUF_FIELD_OFFSET(NlpResult, _impl_.terms_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // repeated .kumo.nlp.NerInfo entities = 7;
    {PROTOBUF_FIELD_OFFSET(NlpResult, _impl_.entities_), -1, 1,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // repeated float feature = 8;
    {PROTOBUF_FIELD_OFFSET(NlpResult, _impl_.feature_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedFloat)},
    // repeated .NgramInfo ngram = 9;
    {PROTOBUF_FIELD_OFFSET(NlpResult, _impl_.ngram_), -1, 2,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // repeated .kumo.nlp.TokenInfo tokens = 10;
    {PROTOBUF_FIELD_OFFSET(NlpResult, _impl_.tokens_), -1, 3,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // repeated .kumo.nlp.RewriteQueryInfo rewrite = 11;
    {PROTOBUF_FIELD_OFFSET(NlpResult, _impl_.rewrite_), -1, 4,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::kumo::nlp::SegmentResult>()},
    {::_pbi::TcParser::GetTable<::kumo::nlp::NerInfo>()},
    {::_pbi::TcParser::GetTable<::NgramInfo>()},
    {::_pbi::TcParser::GetTable<::kumo::nlp::TokenInfo>()},
    {::_pbi::TcParser::GetTable<::kumo::nlp::RewriteQueryInfo>()},
  }}, {{
    "\22\11\4\5\6\14\0\0\0\0\0\0\0\0\0\0"
    "kumo.nlp.NlpResult"
    "raw_query"
    "lang"
    "query"
    "pinyin"
    "pinyin_short"
  }},
};

PROTOBUF_NOINLINE void NlpResult::Clear() {
// @@protoc_insertion_point(message_clear_start:kumo.nlp.NlpResult)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.entities_.Clear();
  _impl_.feature_.Clear();
  _impl_.ngram_.Clear();
  _impl_.tokens_.Clear();
  _impl_.rewrite_.Clear();
  _impl_.raw_query_.ClearToEmpty();
  _impl_.lang_.ClearToEmpty();
  _impl_.query_.ClearToEmpty();
  _impl_.pinyin_.ClearToEmpty();
  _impl_.pinyin_short_.ClearToEmpty();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.terms_ != nullptr);
    _impl_.terms_->Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* NlpResult::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const NlpResult& this_ = static_cast<const NlpResult&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* NlpResult::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const NlpResult& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:kumo.nlp.NlpResult)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string raw_query = 1;
          if (!this_._internal_raw_query().empty()) {
            const std::string& _s = this_._internal_raw_query();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "kumo.nlp.NlpResult.raw_query");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // string lang = 2;
          if (!this_._internal_lang().empty()) {
            const std::string& _s = this_._internal_lang();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "kumo.nlp.NlpResult.lang");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          // string query = 3;
          if (!this_._internal_query().empty()) {
            const std::string& _s = this_._internal_query();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "kumo.nlp.NlpResult.query");
            target = stream->WriteStringMaybeAliased(3, _s, target);
          }

          // string pinyin = 4;
          if (!this_._internal_pinyin().empty()) {
            const std::string& _s = this_._internal_pinyin();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "kumo.nlp.NlpResult.pinyin");
            target = stream->WriteStringMaybeAliased(4, _s, target);
          }

          // string pinyin_short = 5;
          if (!this_._internal_pinyin_short().empty()) {
            const std::string& _s = this_._internal_pinyin_short();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "kumo.nlp.NlpResult.pinyin_short");
            target = stream->WriteStringMaybeAliased(5, _s, target);
          }

          cached_has_bits = this_._impl_._has_bits_[0];
          // .kumo.nlp.SegmentResult terms = 6;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                6, *this_._impl_.terms_, this_._impl_.terms_->GetCachedSize(), target,
                stream);
          }

          // repeated .kumo.nlp.NerInfo entities = 7;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_entities_size());
               i < n; i++) {
            const auto& repfield = this_._internal_entities().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    7, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          // repeated float feature = 8;
          if (this_._internal_feature_size() > 0) {
            target = stream->WriteFixedPacked(8, this_._internal_feature(), target);
          }

          // repeated .NgramInfo ngram = 9;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_ngram_size());
               i < n; i++) {
            const auto& repfield = this_._internal_ngram().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    9, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          // repeated .kumo.nlp.TokenInfo tokens = 10;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_tokens_size());
               i < n; i++) {
            const auto& repfield = this_._internal_tokens().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    10, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          // repeated .kumo.nlp.RewriteQueryInfo rewrite = 11;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_rewrite_size());
               i < n; i++) {
            const auto& repfield = this_._internal_rewrite().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    11, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:kumo.nlp.NlpResult)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t NlpResult::ByteSizeLong(const MessageLite& base) {
          const NlpResult& this_ = static_cast<const NlpResult&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t NlpResult::ByteSizeLong() const {
          const NlpResult& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:kumo.nlp.NlpResult)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated .kumo.nlp.NerInfo entities = 7;
            {
              total_size += 1UL * this_._internal_entities_size();
              for (const auto& msg : this_._internal_entities()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
            // repeated float feature = 8;
            {
              std::size_t data_size = std::size_t{4} *
                  ::_pbi::FromIntSize(this_._internal_feature_size());
              std::size_t tag_size = data_size == 0
                  ? 0
                  : 1 + ::_pbi::WireFormatLite::Int32Size(
                                      static_cast<int32_t>(data_size));
              total_size += tag_size + data_size;
            }
            // repeated .NgramInfo ngram = 9;
            {
              total_size += 1UL * this_._internal_ngram_size();
              for (const auto& msg : this_._internal_ngram()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
            // repeated .kumo.nlp.TokenInfo tokens = 10;
            {
              total_size += 1UL * this_._internal_tokens_size();
              for (const auto& msg : this_._internal_tokens()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
            // repeated .kumo.nlp.RewriteQueryInfo rewrite = 11;
            {
              total_size += 1UL * this_._internal_rewrite_size();
              for (const auto& msg : this_._internal_rewrite()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
          }
           {
            // string raw_query = 1;
            if (!this_._internal_raw_query().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_raw_query());
            }
            // string lang = 2;
            if (!this_._internal_lang().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_lang());
            }
            // string query = 3;
            if (!this_._internal_query().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_query());
            }
            // string pinyin = 4;
            if (!this_._internal_pinyin().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_pinyin());
            }
            // string pinyin_short = 5;
            if (!this_._internal_pinyin_short().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_pinyin_short());
            }
          }
           {
            // .kumo.nlp.SegmentResult terms = 6;
            cached_has_bits = this_._impl_._has_bits_[0];
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.terms_);
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void NlpResult::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<NlpResult*>(&to_msg);
  auto& from = static_cast<const NlpResult&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:kumo.nlp.NlpResult)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_entities()->MergeFrom(
      from._internal_entities());
  _this->_internal_mutable_feature()->MergeFrom(from._internal_feature());
  _this->_internal_mutable_ngram()->MergeFrom(
      from._internal_ngram());
  _this->_internal_mutable_tokens()->MergeFrom(
      from._internal_tokens());
  _this->_internal_mutable_rewrite()->MergeFrom(
      from._internal_rewrite());
  if (!from._internal_raw_query().empty()) {
    _this->_internal_set_raw_query(from._internal_raw_query());
  }
  if (!from._internal_lang().empty()) {
    _this->_internal_set_lang(from._internal_lang());
  }
  if (!from._internal_query().empty()) {
    _this->_internal_set_query(from._internal_query());
  }
  if (!from._internal_pinyin().empty()) {
    _this->_internal_set_pinyin(from._internal_pinyin());
  }
  if (!from._internal_pinyin_short().empty()) {
    _this->_internal_set_pinyin_short(from._internal_pinyin_short());
  }
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(from._impl_.terms_ != nullptr);
    if (_this->_impl_.terms_ == nullptr) {
      _this->_impl_.terms_ =
          ::google::protobuf::Message::CopyConstruct<::kumo::nlp::SegmentResult>(arena, *from._impl_.terms_);
    } else {
      _this->_impl_.terms_->MergeFrom(*from._impl_.terms_);
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void NlpResult::CopyFrom(const NlpResult& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:kumo.nlp.NlpResult)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void NlpResult::InternalSwap(NlpResult* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.entities_.InternalSwap(&other->_impl_.entities_);
  _impl_.feature_.InternalSwap(&other->_impl_.feature_);
  _impl_.ngram_.InternalSwap(&other->_impl_.ngram_);
  _impl_.tokens_.InternalSwap(&other->_impl_.tokens_);
  _impl_.rewrite_.InternalSwap(&other->_impl_.rewrite_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.raw_query_, &other->_impl_.raw_query_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.lang_, &other->_impl_.lang_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.query_, &other->_impl_.query_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.pinyin_, &other->_impl_.pinyin_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.pinyin_short_, &other->_impl_.pinyin_short_, arena);
  swap(_impl_.terms_, other->_impl_.terms_);
}

::google::protobuf::Metadata NlpResult::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace nlp
}  // namespace kumo
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_gnef_2fproto_2fsearch_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
