// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: gnef/proto/segment.proto
// Protobuf C++ Version: 5.29.5

#ifndef gnef_2fproto_2fsegment_2eproto_2epb_2eh
#define gnef_2fproto_2fsegment_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029005
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_gnef_2fproto_2fsegment_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_gnef_2fproto_2fsegment_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_gnef_2fproto_2fsegment_2eproto;
namespace kumo {
namespace nlp {
class SegmentRequest;
struct SegmentRequestDefaultTypeInternal;
extern SegmentRequestDefaultTypeInternal _SegmentRequest_default_instance_;
class SegmentResponse;
struct SegmentResponseDefaultTypeInternal;
extern SegmentResponseDefaultTypeInternal _SegmentResponse_default_instance_;
class SegmentResult;
struct SegmentResultDefaultTypeInternal;
extern SegmentResultDefaultTypeInternal _SegmentResult_default_instance_;
class SegmentSetting;
struct SegmentSettingDefaultTypeInternal;
extern SegmentSettingDefaultTypeInternal _SegmentSetting_default_instance_;
class SegmentTerm;
struct SegmentTermDefaultTypeInternal;
extern SegmentTermDefaultTypeInternal _SegmentTerm_default_instance_;
class TermBasicWeight;
struct TermBasicWeightDefaultTypeInternal;
extern TermBasicWeightDefaultTypeInternal _TermBasicWeight_default_instance_;
class TermInfo;
struct TermInfoDefaultTypeInternal;
extern TermInfoDefaultTypeInternal _TermInfo_default_instance_;
}  // namespace nlp
}  // namespace kumo
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace kumo {
namespace nlp {

// ===================================================================


// -------------------------------------------------------------------

class TermInfo final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:kumo.nlp.TermInfo) */ {
 public:
  inline TermInfo() : TermInfo(nullptr) {}
  ~TermInfo() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(TermInfo* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(TermInfo));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR TermInfo(
      ::google::protobuf::internal::ConstantInitialized);

  inline TermInfo(const TermInfo& from) : TermInfo(nullptr, from) {}
  inline TermInfo(TermInfo&& from) noexcept
      : TermInfo(nullptr, std::move(from)) {}
  inline TermInfo& operator=(const TermInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline TermInfo& operator=(TermInfo&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TermInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const TermInfo* internal_default_instance() {
    return reinterpret_cast<const TermInfo*>(
        &_TermInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(TermInfo& a, TermInfo& b) { a.Swap(&b); }
  inline void Swap(TermInfo* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TermInfo* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TermInfo* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<TermInfo>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const TermInfo& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const TermInfo& from) { TermInfo::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(TermInfo* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "kumo.nlp.TermInfo"; }

 protected:
  explicit TermInfo(::google::protobuf::Arena* arena);
  TermInfo(::google::protobuf::Arena* arena, const TermInfo& from);
  TermInfo(::google::protobuf::Arena* arena, TermInfo&& from) noexcept
      : TermInfo(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTermFieldNumber = 1,
    kPosFieldNumber = 2,
    kOffsetFieldNumber = 3,
    kLengthFieldNumber = 4,
    kIdfFieldNumber = 5,
    kCharOffsetFieldNumber = 6,
    kCharLengthFieldNumber = 7,
  };
  // string term = 1;
  void clear_term() ;
  const std::string& term() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_term(Arg_&& arg, Args_... args);
  std::string* mutable_term();
  PROTOBUF_NODISCARD std::string* release_term();
  void set_allocated_term(std::string* value);

  private:
  const std::string& _internal_term() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_term(
      const std::string& value);
  std::string* _internal_mutable_term();

  public:
  // string pos = 2;
  void clear_pos() ;
  const std::string& pos() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_pos(Arg_&& arg, Args_... args);
  std::string* mutable_pos();
  PROTOBUF_NODISCARD std::string* release_pos();
  void set_allocated_pos(std::string* value);

  private:
  const std::string& _internal_pos() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_pos(
      const std::string& value);
  std::string* _internal_mutable_pos();

  public:
  // int32 offset = 3;
  void clear_offset() ;
  ::int32_t offset() const;
  void set_offset(::int32_t value);

  private:
  ::int32_t _internal_offset() const;
  void _internal_set_offset(::int32_t value);

  public:
  // int32 length = 4;
  void clear_length() ;
  ::int32_t length() const;
  void set_length(::int32_t value);

  private:
  ::int32_t _internal_length() const;
  void _internal_set_length(::int32_t value);

  public:
  // double idf = 5;
  void clear_idf() ;
  double idf() const;
  void set_idf(double value);

  private:
  double _internal_idf() const;
  void _internal_set_idf(double value);

  public:
  // int32 char_offset = 6;
  void clear_char_offset() ;
  ::int32_t char_offset() const;
  void set_char_offset(::int32_t value);

  private:
  ::int32_t _internal_char_offset() const;
  void _internal_set_char_offset(::int32_t value);

  public:
  // int32 char_length = 7;
  void clear_char_length() ;
  ::int32_t char_length() const;
  void set_char_length(::int32_t value);

  private:
  ::int32_t _internal_char_length() const;
  void _internal_set_char_length(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:kumo.nlp.TermInfo)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 7, 0,
      33, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const TermInfo& from_msg);
    ::google::protobuf::internal::ArenaStringPtr term_;
    ::google::protobuf::internal::ArenaStringPtr pos_;
    ::int32_t offset_;
    ::int32_t length_;
    double idf_;
    ::int32_t char_offset_;
    ::int32_t char_length_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_gnef_2fproto_2fsegment_2eproto;
};
// -------------------------------------------------------------------

class TermBasicWeight final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:kumo.nlp.TermBasicWeight) */ {
 public:
  inline TermBasicWeight() : TermBasicWeight(nullptr) {}
  ~TermBasicWeight() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(TermBasicWeight* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(TermBasicWeight));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR TermBasicWeight(
      ::google::protobuf::internal::ConstantInitialized);

  inline TermBasicWeight(const TermBasicWeight& from) : TermBasicWeight(nullptr, from) {}
  inline TermBasicWeight(TermBasicWeight&& from) noexcept
      : TermBasicWeight(nullptr, std::move(from)) {}
  inline TermBasicWeight& operator=(const TermBasicWeight& from) {
    CopyFrom(from);
    return *this;
  }
  inline TermBasicWeight& operator=(TermBasicWeight&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TermBasicWeight& default_instance() {
    return *internal_default_instance();
  }
  static inline const TermBasicWeight* internal_default_instance() {
    return reinterpret_cast<const TermBasicWeight*>(
        &_TermBasicWeight_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(TermBasicWeight& a, TermBasicWeight& b) { a.Swap(&b); }
  inline void Swap(TermBasicWeight* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TermBasicWeight* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TermBasicWeight* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<TermBasicWeight>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const TermBasicWeight& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const TermBasicWeight& from) { TermBasicWeight::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(TermBasicWeight* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "kumo.nlp.TermBasicWeight"; }

 protected:
  explicit TermBasicWeight(::google::protobuf::Arena* arena);
  TermBasicWeight(::google::protobuf::Arena* arena, const TermBasicWeight& from);
  TermBasicWeight(::google::protobuf::Arena* arena, TermBasicWeight&& from) noexcept
      : TermBasicWeight(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTermFieldNumber = 1,
    kQtWeightFieldNumber = 2,
    kTqWeightFieldNumber = 3,
    kQtTightFieldNumber = 4,
    kTqTightFieldNumber = 5,
  };
  // string term = 1;
  void clear_term() ;
  const std::string& term() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_term(Arg_&& arg, Args_... args);
  std::string* mutable_term();
  PROTOBUF_NODISCARD std::string* release_term();
  void set_allocated_term(std::string* value);

  private:
  const std::string& _internal_term() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_term(
      const std::string& value);
  std::string* _internal_mutable_term();

  public:
  // double qt_weight = 2;
  void clear_qt_weight() ;
  double qt_weight() const;
  void set_qt_weight(double value);

  private:
  double _internal_qt_weight() const;
  void _internal_set_qt_weight(double value);

  public:
  // double tq_weight = 3;
  void clear_tq_weight() ;
  double tq_weight() const;
  void set_tq_weight(double value);

  private:
  double _internal_tq_weight() const;
  void _internal_set_tq_weight(double value);

  public:
  // double qt_tight = 4;
  void clear_qt_tight() ;
  double qt_tight() const;
  void set_qt_tight(double value);

  private:
  double _internal_qt_tight() const;
  void _internal_set_qt_tight(double value);

  public:
  // double tq_tight = 5;
  void clear_tq_tight() ;
  double tq_tight() const;
  void set_tq_tight(double value);

  private:
  double _internal_tq_tight() const;
  void _internal_set_tq_tight(double value);

  public:
  // @@protoc_insertion_point(class_scope:kumo.nlp.TermBasicWeight)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 5, 0,
      37, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const TermBasicWeight& from_msg);
    ::google::protobuf::internal::ArenaStringPtr term_;
    double qt_weight_;
    double tq_weight_;
    double qt_tight_;
    double tq_tight_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_gnef_2fproto_2fsegment_2eproto;
};
// -------------------------------------------------------------------

class SegmentSetting final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:kumo.nlp.SegmentSetting) */ {
 public:
  inline SegmentSetting() : SegmentSetting(nullptr) {}
  ~SegmentSetting() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SegmentSetting* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SegmentSetting));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SegmentSetting(
      ::google::protobuf::internal::ConstantInitialized);

  inline SegmentSetting(const SegmentSetting& from) : SegmentSetting(nullptr, from) {}
  inline SegmentSetting(SegmentSetting&& from) noexcept
      : SegmentSetting(nullptr, std::move(from)) {}
  inline SegmentSetting& operator=(const SegmentSetting& from) {
    CopyFrom(from);
    return *this;
  }
  inline SegmentSetting& operator=(SegmentSetting&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SegmentSetting& default_instance() {
    return *internal_default_instance();
  }
  static inline const SegmentSetting* internal_default_instance() {
    return reinterpret_cast<const SegmentSetting*>(
        &_SegmentSetting_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(SegmentSetting& a, SegmentSetting& b) { a.Swap(&b); }
  inline void Swap(SegmentSetting* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SegmentSetting* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SegmentSetting* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SegmentSetting>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SegmentSetting& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SegmentSetting& from) { SegmentSetting::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SegmentSetting* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "kumo.nlp.SegmentSetting"; }

 protected:
  explicit SegmentSetting(::google::protobuf::Arena* arena);
  SegmentSetting(::google::protobuf::Arena* arena, const SegmentSetting& from);
  SegmentSetting(::google::protobuf::Arena* arena, SegmentSetting&& from) noexcept
      : SegmentSetting(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kEnablePosFieldNumber = 1,
    kPhraseFieldNumber = 2,
  };
  // bool enable_pos = 1;
  void clear_enable_pos() ;
  bool enable_pos() const;
  void set_enable_pos(bool value);

  private:
  bool _internal_enable_pos() const;
  void _internal_set_enable_pos(bool value);

  public:
  // bool phrase = 2;
  void clear_phrase() ;
  bool phrase() const;
  void set_phrase(bool value);

  private:
  bool _internal_phrase() const;
  void _internal_set_phrase(bool value);

  public:
  // @@protoc_insertion_point(class_scope:kumo.nlp.SegmentSetting)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const SegmentSetting& from_msg);
    bool enable_pos_;
    bool phrase_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_gnef_2fproto_2fsegment_2eproto;
};
// -------------------------------------------------------------------

class SegmentTerm final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:kumo.nlp.SegmentTerm) */ {
 public:
  inline SegmentTerm() : SegmentTerm(nullptr) {}
  ~SegmentTerm() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SegmentTerm* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SegmentTerm));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SegmentTerm(
      ::google::protobuf::internal::ConstantInitialized);

  inline SegmentTerm(const SegmentTerm& from) : SegmentTerm(nullptr, from) {}
  inline SegmentTerm(SegmentTerm&& from) noexcept
      : SegmentTerm(nullptr, std::move(from)) {}
  inline SegmentTerm& operator=(const SegmentTerm& from) {
    CopyFrom(from);
    return *this;
  }
  inline SegmentTerm& operator=(SegmentTerm&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SegmentTerm& default_instance() {
    return *internal_default_instance();
  }
  static inline const SegmentTerm* internal_default_instance() {
    return reinterpret_cast<const SegmentTerm*>(
        &_SegmentTerm_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(SegmentTerm& a, SegmentTerm& b) { a.Swap(&b); }
  inline void Swap(SegmentTerm* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SegmentTerm* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SegmentTerm* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SegmentTerm>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SegmentTerm& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SegmentTerm& from) { SegmentTerm::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SegmentTerm* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "kumo.nlp.SegmentTerm"; }

 protected:
  explicit SegmentTerm(::google::protobuf::Arena* arena);
  SegmentTerm(::google::protobuf::Arena* arena, const SegmentTerm& from);
  SegmentTerm(::google::protobuf::Arena* arena, SegmentTerm&& from) noexcept
      : SegmentTerm(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTermInfosFieldNumber = 2,
    kMainTermFieldNumber = 1,
  };
  // repeated .kumo.nlp.TermInfo term_infos = 2;
  int term_infos_size() const;
  private:
  int _internal_term_infos_size() const;

  public:
  void clear_term_infos() ;
  ::kumo::nlp::TermInfo* mutable_term_infos(int index);
  ::google::protobuf::RepeatedPtrField<::kumo::nlp::TermInfo>* mutable_term_infos();

  private:
  const ::google::protobuf::RepeatedPtrField<::kumo::nlp::TermInfo>& _internal_term_infos() const;
  ::google::protobuf::RepeatedPtrField<::kumo::nlp::TermInfo>* _internal_mutable_term_infos();
  public:
  const ::kumo::nlp::TermInfo& term_infos(int index) const;
  ::kumo::nlp::TermInfo* add_term_infos();
  const ::google::protobuf::RepeatedPtrField<::kumo::nlp::TermInfo>& term_infos() const;
  // .kumo.nlp.TermInfo main_term = 1;
  bool has_main_term() const;
  void clear_main_term() ;
  const ::kumo::nlp::TermInfo& main_term() const;
  PROTOBUF_NODISCARD ::kumo::nlp::TermInfo* release_main_term();
  ::kumo::nlp::TermInfo* mutable_main_term();
  void set_allocated_main_term(::kumo::nlp::TermInfo* value);
  void unsafe_arena_set_allocated_main_term(::kumo::nlp::TermInfo* value);
  ::kumo::nlp::TermInfo* unsafe_arena_release_main_term();

  private:
  const ::kumo::nlp::TermInfo& _internal_main_term() const;
  ::kumo::nlp::TermInfo* _internal_mutable_main_term();

  public:
  // @@protoc_insertion_point(class_scope:kumo.nlp.SegmentTerm)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 2,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const SegmentTerm& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::kumo::nlp::TermInfo > term_infos_;
    ::kumo::nlp::TermInfo* main_term_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_gnef_2fproto_2fsegment_2eproto;
};
// -------------------------------------------------------------------

class SegmentRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:kumo.nlp.SegmentRequest) */ {
 public:
  inline SegmentRequest() : SegmentRequest(nullptr) {}
  ~SegmentRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SegmentRequest* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SegmentRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SegmentRequest(
      ::google::protobuf::internal::ConstantInitialized);

  inline SegmentRequest(const SegmentRequest& from) : SegmentRequest(nullptr, from) {}
  inline SegmentRequest(SegmentRequest&& from) noexcept
      : SegmentRequest(nullptr, std::move(from)) {}
  inline SegmentRequest& operator=(const SegmentRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline SegmentRequest& operator=(SegmentRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SegmentRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const SegmentRequest* internal_default_instance() {
    return reinterpret_cast<const SegmentRequest*>(
        &_SegmentRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 5;
  friend void swap(SegmentRequest& a, SegmentRequest& b) { a.Swap(&b); }
  inline void Swap(SegmentRequest* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SegmentRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SegmentRequest* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SegmentRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SegmentRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SegmentRequest& from) { SegmentRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SegmentRequest* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "kumo.nlp.SegmentRequest"; }

 protected:
  explicit SegmentRequest(::google::protobuf::Arena* arena);
  SegmentRequest(::google::protobuf::Arena* arena, const SegmentRequest& from);
  SegmentRequest(::google::protobuf::Arena* arena, SegmentRequest&& from) noexcept
      : SegmentRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kQueryFieldNumber = 1,
    kSettingFieldNumber = 2,
  };
  // string query = 1;
  void clear_query() ;
  const std::string& query() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_query(Arg_&& arg, Args_... args);
  std::string* mutable_query();
  PROTOBUF_NODISCARD std::string* release_query();
  void set_allocated_query(std::string* value);

  private:
  const std::string& _internal_query() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_query(
      const std::string& value);
  std::string* _internal_mutable_query();

  public:
  // .kumo.nlp.SegmentSetting setting = 2;
  bool has_setting() const;
  void clear_setting() ;
  const ::kumo::nlp::SegmentSetting& setting() const;
  PROTOBUF_NODISCARD ::kumo::nlp::SegmentSetting* release_setting();
  ::kumo::nlp::SegmentSetting* mutable_setting();
  void set_allocated_setting(::kumo::nlp::SegmentSetting* value);
  void unsafe_arena_set_allocated_setting(::kumo::nlp::SegmentSetting* value);
  ::kumo::nlp::SegmentSetting* unsafe_arena_release_setting();

  private:
  const ::kumo::nlp::SegmentSetting& _internal_setting() const;
  ::kumo::nlp::SegmentSetting* _internal_mutable_setting();

  public:
  // @@protoc_insertion_point(class_scope:kumo.nlp.SegmentRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 1,
      37, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const SegmentRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr query_;
    ::kumo::nlp::SegmentSetting* setting_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_gnef_2fproto_2fsegment_2eproto;
};
// -------------------------------------------------------------------

class SegmentResult final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:kumo.nlp.SegmentResult) */ {
 public:
  inline SegmentResult() : SegmentResult(nullptr) {}
  ~SegmentResult() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SegmentResult* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SegmentResult));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SegmentResult(
      ::google::protobuf::internal::ConstantInitialized);

  inline SegmentResult(const SegmentResult& from) : SegmentResult(nullptr, from) {}
  inline SegmentResult(SegmentResult&& from) noexcept
      : SegmentResult(nullptr, std::move(from)) {}
  inline SegmentResult& operator=(const SegmentResult& from) {
    CopyFrom(from);
    return *this;
  }
  inline SegmentResult& operator=(SegmentResult&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SegmentResult& default_instance() {
    return *internal_default_instance();
  }
  static inline const SegmentResult* internal_default_instance() {
    return reinterpret_cast<const SegmentResult*>(
        &_SegmentResult_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(SegmentResult& a, SegmentResult& b) { a.Swap(&b); }
  inline void Swap(SegmentResult* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SegmentResult* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SegmentResult* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SegmentResult>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SegmentResult& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SegmentResult& from) { SegmentResult::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SegmentResult* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "kumo.nlp.SegmentResult"; }

 protected:
  explicit SegmentResult(::google::protobuf::Arena* arena);
  SegmentResult(::google::protobuf::Arena* arena, const SegmentResult& from);
  SegmentResult(::google::protobuf::Arena* arena, SegmentResult&& from) noexcept
      : SegmentResult(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTermsFieldNumber = 1,
    kWeightsFieldNumber = 2,
  };
  // repeated .kumo.nlp.SegmentTerm terms = 1;
  int terms_size() const;
  private:
  int _internal_terms_size() const;

  public:
  void clear_terms() ;
  ::kumo::nlp::SegmentTerm* mutable_terms(int index);
  ::google::protobuf::RepeatedPtrField<::kumo::nlp::SegmentTerm>* mutable_terms();

  private:
  const ::google::protobuf::RepeatedPtrField<::kumo::nlp::SegmentTerm>& _internal_terms() const;
  ::google::protobuf::RepeatedPtrField<::kumo::nlp::SegmentTerm>* _internal_mutable_terms();
  public:
  const ::kumo::nlp::SegmentTerm& terms(int index) const;
  ::kumo::nlp::SegmentTerm* add_terms();
  const ::google::protobuf::RepeatedPtrField<::kumo::nlp::SegmentTerm>& terms() const;
  // repeated .kumo.nlp.TermBasicWeight weights = 2;
  int weights_size() const;
  private:
  int _internal_weights_size() const;

  public:
  void clear_weights() ;
  ::kumo::nlp::TermBasicWeight* mutable_weights(int index);
  ::google::protobuf::RepeatedPtrField<::kumo::nlp::TermBasicWeight>* mutable_weights();

  private:
  const ::google::protobuf::RepeatedPtrField<::kumo::nlp::TermBasicWeight>& _internal_weights() const;
  ::google::protobuf::RepeatedPtrField<::kumo::nlp::TermBasicWeight>* _internal_mutable_weights();
  public:
  const ::kumo::nlp::TermBasicWeight& weights(int index) const;
  ::kumo::nlp::TermBasicWeight* add_weights();
  const ::google::protobuf::RepeatedPtrField<::kumo::nlp::TermBasicWeight>& weights() const;
  // @@protoc_insertion_point(class_scope:kumo.nlp.SegmentResult)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 2,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const SegmentResult& from_msg);
    ::google::protobuf::RepeatedPtrField< ::kumo::nlp::SegmentTerm > terms_;
    ::google::protobuf::RepeatedPtrField< ::kumo::nlp::TermBasicWeight > weights_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_gnef_2fproto_2fsegment_2eproto;
};
// -------------------------------------------------------------------

class SegmentResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:kumo.nlp.SegmentResponse) */ {
 public:
  inline SegmentResponse() : SegmentResponse(nullptr) {}
  ~SegmentResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SegmentResponse* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SegmentResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SegmentResponse(
      ::google::protobuf::internal::ConstantInitialized);

  inline SegmentResponse(const SegmentResponse& from) : SegmentResponse(nullptr, from) {}
  inline SegmentResponse(SegmentResponse&& from) noexcept
      : SegmentResponse(nullptr, std::move(from)) {}
  inline SegmentResponse& operator=(const SegmentResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline SegmentResponse& operator=(SegmentResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SegmentResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const SegmentResponse* internal_default_instance() {
    return reinterpret_cast<const SegmentResponse*>(
        &_SegmentResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 6;
  friend void swap(SegmentResponse& a, SegmentResponse& b) { a.Swap(&b); }
  inline void Swap(SegmentResponse* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SegmentResponse* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SegmentResponse* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SegmentResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SegmentResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SegmentResponse& from) { SegmentResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SegmentResponse* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "kumo.nlp.SegmentResponse"; }

 protected:
  explicit SegmentResponse(::google::protobuf::Arena* arena);
  SegmentResponse(::google::protobuf::Arena* arena, const SegmentResponse& from);
  SegmentResponse(::google::protobuf::Arena* arena, SegmentResponse&& from) noexcept
      : SegmentResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kResultFieldNumber = 1,
  };
  // .kumo.nlp.SegmentResult result = 1;
  bool has_result() const;
  void clear_result() ;
  const ::kumo::nlp::SegmentResult& result() const;
  PROTOBUF_NODISCARD ::kumo::nlp::SegmentResult* release_result();
  ::kumo::nlp::SegmentResult* mutable_result();
  void set_allocated_result(::kumo::nlp::SegmentResult* value);
  void unsafe_arena_set_allocated_result(::kumo::nlp::SegmentResult* value);
  ::kumo::nlp::SegmentResult* unsafe_arena_release_result();

  private:
  const ::kumo::nlp::SegmentResult& _internal_result() const;
  ::kumo::nlp::SegmentResult* _internal_mutable_result();

  public:
  // @@protoc_insertion_point(class_scope:kumo.nlp.SegmentResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 1,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const SegmentResponse& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::kumo::nlp::SegmentResult* result_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_gnef_2fproto_2fsegment_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// SegmentSetting

// bool enable_pos = 1;
inline void SegmentSetting::clear_enable_pos() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.enable_pos_ = false;
}
inline bool SegmentSetting::enable_pos() const {
  // @@protoc_insertion_point(field_get:kumo.nlp.SegmentSetting.enable_pos)
  return _internal_enable_pos();
}
inline void SegmentSetting::set_enable_pos(bool value) {
  _internal_set_enable_pos(value);
  // @@protoc_insertion_point(field_set:kumo.nlp.SegmentSetting.enable_pos)
}
inline bool SegmentSetting::_internal_enable_pos() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.enable_pos_;
}
inline void SegmentSetting::_internal_set_enable_pos(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.enable_pos_ = value;
}

// bool phrase = 2;
inline void SegmentSetting::clear_phrase() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.phrase_ = false;
}
inline bool SegmentSetting::phrase() const {
  // @@protoc_insertion_point(field_get:kumo.nlp.SegmentSetting.phrase)
  return _internal_phrase();
}
inline void SegmentSetting::set_phrase(bool value) {
  _internal_set_phrase(value);
  // @@protoc_insertion_point(field_set:kumo.nlp.SegmentSetting.phrase)
}
inline bool SegmentSetting::_internal_phrase() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.phrase_;
}
inline void SegmentSetting::_internal_set_phrase(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.phrase_ = value;
}

// -------------------------------------------------------------------

// TermBasicWeight

// string term = 1;
inline void TermBasicWeight::clear_term() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.term_.ClearToEmpty();
}
inline const std::string& TermBasicWeight::term() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:kumo.nlp.TermBasicWeight.term)
  return _internal_term();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void TermBasicWeight::set_term(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.term_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:kumo.nlp.TermBasicWeight.term)
}
inline std::string* TermBasicWeight::mutable_term() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_term();
  // @@protoc_insertion_point(field_mutable:kumo.nlp.TermBasicWeight.term)
  return _s;
}
inline const std::string& TermBasicWeight::_internal_term() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.term_.Get();
}
inline void TermBasicWeight::_internal_set_term(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.term_.Set(value, GetArena());
}
inline std::string* TermBasicWeight::_internal_mutable_term() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.term_.Mutable( GetArena());
}
inline std::string* TermBasicWeight::release_term() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:kumo.nlp.TermBasicWeight.term)
  return _impl_.term_.Release();
}
inline void TermBasicWeight::set_allocated_term(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.term_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.term_.IsDefault()) {
    _impl_.term_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:kumo.nlp.TermBasicWeight.term)
}

// double qt_weight = 2;
inline void TermBasicWeight::clear_qt_weight() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.qt_weight_ = 0;
}
inline double TermBasicWeight::qt_weight() const {
  // @@protoc_insertion_point(field_get:kumo.nlp.TermBasicWeight.qt_weight)
  return _internal_qt_weight();
}
inline void TermBasicWeight::set_qt_weight(double value) {
  _internal_set_qt_weight(value);
  // @@protoc_insertion_point(field_set:kumo.nlp.TermBasicWeight.qt_weight)
}
inline double TermBasicWeight::_internal_qt_weight() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.qt_weight_;
}
inline void TermBasicWeight::_internal_set_qt_weight(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.qt_weight_ = value;
}

// double tq_weight = 3;
inline void TermBasicWeight::clear_tq_weight() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.tq_weight_ = 0;
}
inline double TermBasicWeight::tq_weight() const {
  // @@protoc_insertion_point(field_get:kumo.nlp.TermBasicWeight.tq_weight)
  return _internal_tq_weight();
}
inline void TermBasicWeight::set_tq_weight(double value) {
  _internal_set_tq_weight(value);
  // @@protoc_insertion_point(field_set:kumo.nlp.TermBasicWeight.tq_weight)
}
inline double TermBasicWeight::_internal_tq_weight() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.tq_weight_;
}
inline void TermBasicWeight::_internal_set_tq_weight(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.tq_weight_ = value;
}

// double qt_tight = 4;
inline void TermBasicWeight::clear_qt_tight() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.qt_tight_ = 0;
}
inline double TermBasicWeight::qt_tight() const {
  // @@protoc_insertion_point(field_get:kumo.nlp.TermBasicWeight.qt_tight)
  return _internal_qt_tight();
}
inline void TermBasicWeight::set_qt_tight(double value) {
  _internal_set_qt_tight(value);
  // @@protoc_insertion_point(field_set:kumo.nlp.TermBasicWeight.qt_tight)
}
inline double TermBasicWeight::_internal_qt_tight() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.qt_tight_;
}
inline void TermBasicWeight::_internal_set_qt_tight(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.qt_tight_ = value;
}

// double tq_tight = 5;
inline void TermBasicWeight::clear_tq_tight() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.tq_tight_ = 0;
}
inline double TermBasicWeight::tq_tight() const {
  // @@protoc_insertion_point(field_get:kumo.nlp.TermBasicWeight.tq_tight)
  return _internal_tq_tight();
}
inline void TermBasicWeight::set_tq_tight(double value) {
  _internal_set_tq_tight(value);
  // @@protoc_insertion_point(field_set:kumo.nlp.TermBasicWeight.tq_tight)
}
inline double TermBasicWeight::_internal_tq_tight() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.tq_tight_;
}
inline void TermBasicWeight::_internal_set_tq_tight(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.tq_tight_ = value;
}

// -------------------------------------------------------------------

// TermInfo

// string term = 1;
inline void TermInfo::clear_term() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.term_.ClearToEmpty();
}
inline const std::string& TermInfo::term() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:kumo.nlp.TermInfo.term)
  return _internal_term();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void TermInfo::set_term(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.term_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:kumo.nlp.TermInfo.term)
}
inline std::string* TermInfo::mutable_term() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_term();
  // @@protoc_insertion_point(field_mutable:kumo.nlp.TermInfo.term)
  return _s;
}
inline const std::string& TermInfo::_internal_term() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.term_.Get();
}
inline void TermInfo::_internal_set_term(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.term_.Set(value, GetArena());
}
inline std::string* TermInfo::_internal_mutable_term() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.term_.Mutable( GetArena());
}
inline std::string* TermInfo::release_term() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:kumo.nlp.TermInfo.term)
  return _impl_.term_.Release();
}
inline void TermInfo::set_allocated_term(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.term_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.term_.IsDefault()) {
    _impl_.term_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:kumo.nlp.TermInfo.term)
}

// string pos = 2;
inline void TermInfo::clear_pos() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pos_.ClearToEmpty();
}
inline const std::string& TermInfo::pos() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:kumo.nlp.TermInfo.pos)
  return _internal_pos();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void TermInfo::set_pos(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pos_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:kumo.nlp.TermInfo.pos)
}
inline std::string* TermInfo::mutable_pos() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_pos();
  // @@protoc_insertion_point(field_mutable:kumo.nlp.TermInfo.pos)
  return _s;
}
inline const std::string& TermInfo::_internal_pos() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pos_.Get();
}
inline void TermInfo::_internal_set_pos(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pos_.Set(value, GetArena());
}
inline std::string* TermInfo::_internal_mutable_pos() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.pos_.Mutable( GetArena());
}
inline std::string* TermInfo::release_pos() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:kumo.nlp.TermInfo.pos)
  return _impl_.pos_.Release();
}
inline void TermInfo::set_allocated_pos(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pos_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.pos_.IsDefault()) {
    _impl_.pos_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:kumo.nlp.TermInfo.pos)
}

// int32 offset = 3;
inline void TermInfo::clear_offset() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.offset_ = 0;
}
inline ::int32_t TermInfo::offset() const {
  // @@protoc_insertion_point(field_get:kumo.nlp.TermInfo.offset)
  return _internal_offset();
}
inline void TermInfo::set_offset(::int32_t value) {
  _internal_set_offset(value);
  // @@protoc_insertion_point(field_set:kumo.nlp.TermInfo.offset)
}
inline ::int32_t TermInfo::_internal_offset() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.offset_;
}
inline void TermInfo::_internal_set_offset(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.offset_ = value;
}

// int32 length = 4;
inline void TermInfo::clear_length() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.length_ = 0;
}
inline ::int32_t TermInfo::length() const {
  // @@protoc_insertion_point(field_get:kumo.nlp.TermInfo.length)
  return _internal_length();
}
inline void TermInfo::set_length(::int32_t value) {
  _internal_set_length(value);
  // @@protoc_insertion_point(field_set:kumo.nlp.TermInfo.length)
}
inline ::int32_t TermInfo::_internal_length() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.length_;
}
inline void TermInfo::_internal_set_length(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.length_ = value;
}

// double idf = 5;
inline void TermInfo::clear_idf() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.idf_ = 0;
}
inline double TermInfo::idf() const {
  // @@protoc_insertion_point(field_get:kumo.nlp.TermInfo.idf)
  return _internal_idf();
}
inline void TermInfo::set_idf(double value) {
  _internal_set_idf(value);
  // @@protoc_insertion_point(field_set:kumo.nlp.TermInfo.idf)
}
inline double TermInfo::_internal_idf() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.idf_;
}
inline void TermInfo::_internal_set_idf(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.idf_ = value;
}

// int32 char_offset = 6;
inline void TermInfo::clear_char_offset() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.char_offset_ = 0;
}
inline ::int32_t TermInfo::char_offset() const {
  // @@protoc_insertion_point(field_get:kumo.nlp.TermInfo.char_offset)
  return _internal_char_offset();
}
inline void TermInfo::set_char_offset(::int32_t value) {
  _internal_set_char_offset(value);
  // @@protoc_insertion_point(field_set:kumo.nlp.TermInfo.char_offset)
}
inline ::int32_t TermInfo::_internal_char_offset() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.char_offset_;
}
inline void TermInfo::_internal_set_char_offset(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.char_offset_ = value;
}

// int32 char_length = 7;
inline void TermInfo::clear_char_length() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.char_length_ = 0;
}
inline ::int32_t TermInfo::char_length() const {
  // @@protoc_insertion_point(field_get:kumo.nlp.TermInfo.char_length)
  return _internal_char_length();
}
inline void TermInfo::set_char_length(::int32_t value) {
  _internal_set_char_length(value);
  // @@protoc_insertion_point(field_set:kumo.nlp.TermInfo.char_length)
}
inline ::int32_t TermInfo::_internal_char_length() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.char_length_;
}
inline void TermInfo::_internal_set_char_length(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.char_length_ = value;
}

// -------------------------------------------------------------------

// SegmentTerm

// .kumo.nlp.TermInfo main_term = 1;
inline bool SegmentTerm::has_main_term() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.main_term_ != nullptr);
  return value;
}
inline void SegmentTerm::clear_main_term() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.main_term_ != nullptr) _impl_.main_term_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::kumo::nlp::TermInfo& SegmentTerm::_internal_main_term() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::kumo::nlp::TermInfo* p = _impl_.main_term_;
  return p != nullptr ? *p : reinterpret_cast<const ::kumo::nlp::TermInfo&>(::kumo::nlp::_TermInfo_default_instance_);
}
inline const ::kumo::nlp::TermInfo& SegmentTerm::main_term() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:kumo.nlp.SegmentTerm.main_term)
  return _internal_main_term();
}
inline void SegmentTerm::unsafe_arena_set_allocated_main_term(::kumo::nlp::TermInfo* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.main_term_);
  }
  _impl_.main_term_ = reinterpret_cast<::kumo::nlp::TermInfo*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:kumo.nlp.SegmentTerm.main_term)
}
inline ::kumo::nlp::TermInfo* SegmentTerm::release_main_term() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::kumo::nlp::TermInfo* released = _impl_.main_term_;
  _impl_.main_term_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::kumo::nlp::TermInfo* SegmentTerm::unsafe_arena_release_main_term() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:kumo.nlp.SegmentTerm.main_term)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::kumo::nlp::TermInfo* temp = _impl_.main_term_;
  _impl_.main_term_ = nullptr;
  return temp;
}
inline ::kumo::nlp::TermInfo* SegmentTerm::_internal_mutable_main_term() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.main_term_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::kumo::nlp::TermInfo>(GetArena());
    _impl_.main_term_ = reinterpret_cast<::kumo::nlp::TermInfo*>(p);
  }
  return _impl_.main_term_;
}
inline ::kumo::nlp::TermInfo* SegmentTerm::mutable_main_term() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::kumo::nlp::TermInfo* _msg = _internal_mutable_main_term();
  // @@protoc_insertion_point(field_mutable:kumo.nlp.SegmentTerm.main_term)
  return _msg;
}
inline void SegmentTerm::set_allocated_main_term(::kumo::nlp::TermInfo* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete (_impl_.main_term_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = (value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.main_term_ = reinterpret_cast<::kumo::nlp::TermInfo*>(value);
  // @@protoc_insertion_point(field_set_allocated:kumo.nlp.SegmentTerm.main_term)
}

// repeated .kumo.nlp.TermInfo term_infos = 2;
inline int SegmentTerm::_internal_term_infos_size() const {
  return _internal_term_infos().size();
}
inline int SegmentTerm::term_infos_size() const {
  return _internal_term_infos_size();
}
inline void SegmentTerm::clear_term_infos() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.term_infos_.Clear();
}
inline ::kumo::nlp::TermInfo* SegmentTerm::mutable_term_infos(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:kumo.nlp.SegmentTerm.term_infos)
  return _internal_mutable_term_infos()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::kumo::nlp::TermInfo>* SegmentTerm::mutable_term_infos()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:kumo.nlp.SegmentTerm.term_infos)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_term_infos();
}
inline const ::kumo::nlp::TermInfo& SegmentTerm::term_infos(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:kumo.nlp.SegmentTerm.term_infos)
  return _internal_term_infos().Get(index);
}
inline ::kumo::nlp::TermInfo* SegmentTerm::add_term_infos() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::kumo::nlp::TermInfo* _add = _internal_mutable_term_infos()->Add();
  // @@protoc_insertion_point(field_add:kumo.nlp.SegmentTerm.term_infos)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::kumo::nlp::TermInfo>& SegmentTerm::term_infos() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:kumo.nlp.SegmentTerm.term_infos)
  return _internal_term_infos();
}
inline const ::google::protobuf::RepeatedPtrField<::kumo::nlp::TermInfo>&
SegmentTerm::_internal_term_infos() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.term_infos_;
}
inline ::google::protobuf::RepeatedPtrField<::kumo::nlp::TermInfo>*
SegmentTerm::_internal_mutable_term_infos() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.term_infos_;
}

// -------------------------------------------------------------------

// SegmentResult

// repeated .kumo.nlp.SegmentTerm terms = 1;
inline int SegmentResult::_internal_terms_size() const {
  return _internal_terms().size();
}
inline int SegmentResult::terms_size() const {
  return _internal_terms_size();
}
inline void SegmentResult::clear_terms() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.terms_.Clear();
}
inline ::kumo::nlp::SegmentTerm* SegmentResult::mutable_terms(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:kumo.nlp.SegmentResult.terms)
  return _internal_mutable_terms()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::kumo::nlp::SegmentTerm>* SegmentResult::mutable_terms()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:kumo.nlp.SegmentResult.terms)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_terms();
}
inline const ::kumo::nlp::SegmentTerm& SegmentResult::terms(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:kumo.nlp.SegmentResult.terms)
  return _internal_terms().Get(index);
}
inline ::kumo::nlp::SegmentTerm* SegmentResult::add_terms() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::kumo::nlp::SegmentTerm* _add = _internal_mutable_terms()->Add();
  // @@protoc_insertion_point(field_add:kumo.nlp.SegmentResult.terms)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::kumo::nlp::SegmentTerm>& SegmentResult::terms() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:kumo.nlp.SegmentResult.terms)
  return _internal_terms();
}
inline const ::google::protobuf::RepeatedPtrField<::kumo::nlp::SegmentTerm>&
SegmentResult::_internal_terms() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.terms_;
}
inline ::google::protobuf::RepeatedPtrField<::kumo::nlp::SegmentTerm>*
SegmentResult::_internal_mutable_terms() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.terms_;
}

// repeated .kumo.nlp.TermBasicWeight weights = 2;
inline int SegmentResult::_internal_weights_size() const {
  return _internal_weights().size();
}
inline int SegmentResult::weights_size() const {
  return _internal_weights_size();
}
inline void SegmentResult::clear_weights() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.weights_.Clear();
}
inline ::kumo::nlp::TermBasicWeight* SegmentResult::mutable_weights(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:kumo.nlp.SegmentResult.weights)
  return _internal_mutable_weights()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::kumo::nlp::TermBasicWeight>* SegmentResult::mutable_weights()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:kumo.nlp.SegmentResult.weights)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_weights();
}
inline const ::kumo::nlp::TermBasicWeight& SegmentResult::weights(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:kumo.nlp.SegmentResult.weights)
  return _internal_weights().Get(index);
}
inline ::kumo::nlp::TermBasicWeight* SegmentResult::add_weights() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::kumo::nlp::TermBasicWeight* _add = _internal_mutable_weights()->Add();
  // @@protoc_insertion_point(field_add:kumo.nlp.SegmentResult.weights)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::kumo::nlp::TermBasicWeight>& SegmentResult::weights() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:kumo.nlp.SegmentResult.weights)
  return _internal_weights();
}
inline const ::google::protobuf::RepeatedPtrField<::kumo::nlp::TermBasicWeight>&
SegmentResult::_internal_weights() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.weights_;
}
inline ::google::protobuf::RepeatedPtrField<::kumo::nlp::TermBasicWeight>*
SegmentResult::_internal_mutable_weights() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.weights_;
}

// -------------------------------------------------------------------

// SegmentRequest

// string query = 1;
inline void SegmentRequest::clear_query() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.query_.ClearToEmpty();
}
inline const std::string& SegmentRequest::query() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:kumo.nlp.SegmentRequest.query)
  return _internal_query();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void SegmentRequest::set_query(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.query_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:kumo.nlp.SegmentRequest.query)
}
inline std::string* SegmentRequest::mutable_query() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_query();
  // @@protoc_insertion_point(field_mutable:kumo.nlp.SegmentRequest.query)
  return _s;
}
inline const std::string& SegmentRequest::_internal_query() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.query_.Get();
}
inline void SegmentRequest::_internal_set_query(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.query_.Set(value, GetArena());
}
inline std::string* SegmentRequest::_internal_mutable_query() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.query_.Mutable( GetArena());
}
inline std::string* SegmentRequest::release_query() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:kumo.nlp.SegmentRequest.query)
  return _impl_.query_.Release();
}
inline void SegmentRequest::set_allocated_query(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.query_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.query_.IsDefault()) {
    _impl_.query_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:kumo.nlp.SegmentRequest.query)
}

// .kumo.nlp.SegmentSetting setting = 2;
inline bool SegmentRequest::has_setting() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.setting_ != nullptr);
  return value;
}
inline void SegmentRequest::clear_setting() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.setting_ != nullptr) _impl_.setting_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::kumo::nlp::SegmentSetting& SegmentRequest::_internal_setting() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::kumo::nlp::SegmentSetting* p = _impl_.setting_;
  return p != nullptr ? *p : reinterpret_cast<const ::kumo::nlp::SegmentSetting&>(::kumo::nlp::_SegmentSetting_default_instance_);
}
inline const ::kumo::nlp::SegmentSetting& SegmentRequest::setting() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:kumo.nlp.SegmentRequest.setting)
  return _internal_setting();
}
inline void SegmentRequest::unsafe_arena_set_allocated_setting(::kumo::nlp::SegmentSetting* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.setting_);
  }
  _impl_.setting_ = reinterpret_cast<::kumo::nlp::SegmentSetting*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:kumo.nlp.SegmentRequest.setting)
}
inline ::kumo::nlp::SegmentSetting* SegmentRequest::release_setting() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::kumo::nlp::SegmentSetting* released = _impl_.setting_;
  _impl_.setting_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::kumo::nlp::SegmentSetting* SegmentRequest::unsafe_arena_release_setting() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:kumo.nlp.SegmentRequest.setting)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::kumo::nlp::SegmentSetting* temp = _impl_.setting_;
  _impl_.setting_ = nullptr;
  return temp;
}
inline ::kumo::nlp::SegmentSetting* SegmentRequest::_internal_mutable_setting() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.setting_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::kumo::nlp::SegmentSetting>(GetArena());
    _impl_.setting_ = reinterpret_cast<::kumo::nlp::SegmentSetting*>(p);
  }
  return _impl_.setting_;
}
inline ::kumo::nlp::SegmentSetting* SegmentRequest::mutable_setting() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::kumo::nlp::SegmentSetting* _msg = _internal_mutable_setting();
  // @@protoc_insertion_point(field_mutable:kumo.nlp.SegmentRequest.setting)
  return _msg;
}
inline void SegmentRequest::set_allocated_setting(::kumo::nlp::SegmentSetting* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete (_impl_.setting_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = (value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.setting_ = reinterpret_cast<::kumo::nlp::SegmentSetting*>(value);
  // @@protoc_insertion_point(field_set_allocated:kumo.nlp.SegmentRequest.setting)
}

// -------------------------------------------------------------------

// SegmentResponse

// .kumo.nlp.SegmentResult result = 1;
inline bool SegmentResponse::has_result() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.result_ != nullptr);
  return value;
}
inline void SegmentResponse::clear_result() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.result_ != nullptr) _impl_.result_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::kumo::nlp::SegmentResult& SegmentResponse::_internal_result() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::kumo::nlp::SegmentResult* p = _impl_.result_;
  return p != nullptr ? *p : reinterpret_cast<const ::kumo::nlp::SegmentResult&>(::kumo::nlp::_SegmentResult_default_instance_);
}
inline const ::kumo::nlp::SegmentResult& SegmentResponse::result() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:kumo.nlp.SegmentResponse.result)
  return _internal_result();
}
inline void SegmentResponse::unsafe_arena_set_allocated_result(::kumo::nlp::SegmentResult* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.result_);
  }
  _impl_.result_ = reinterpret_cast<::kumo::nlp::SegmentResult*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:kumo.nlp.SegmentResponse.result)
}
inline ::kumo::nlp::SegmentResult* SegmentResponse::release_result() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::kumo::nlp::SegmentResult* released = _impl_.result_;
  _impl_.result_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::kumo::nlp::SegmentResult* SegmentResponse::unsafe_arena_release_result() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:kumo.nlp.SegmentResponse.result)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::kumo::nlp::SegmentResult* temp = _impl_.result_;
  _impl_.result_ = nullptr;
  return temp;
}
inline ::kumo::nlp::SegmentResult* SegmentResponse::_internal_mutable_result() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.result_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::kumo::nlp::SegmentResult>(GetArena());
    _impl_.result_ = reinterpret_cast<::kumo::nlp::SegmentResult*>(p);
  }
  return _impl_.result_;
}
inline ::kumo::nlp::SegmentResult* SegmentResponse::mutable_result() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::kumo::nlp::SegmentResult* _msg = _internal_mutable_result();
  // @@protoc_insertion_point(field_mutable:kumo.nlp.SegmentResponse.result)
  return _msg;
}
inline void SegmentResponse::set_allocated_result(::kumo::nlp::SegmentResult* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete (_impl_.result_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = (value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.result_ = reinterpret_cast<::kumo::nlp::SegmentResult*>(value);
  // @@protoc_insertion_point(field_set_allocated:kumo.nlp.SegmentResponse.result)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace nlp
}  // namespace kumo


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // gnef_2fproto_2fsegment_2eproto_2epb_2eh
